//Add watch window variables
expRemoveAll()
expAdd("fError1", getNatural())
expAdd("fError2", getNatural())
expAdd("fail", getNatural())
expAdd("pass", getNatural())
expAdd("Cla1Regs._MR0.i32", getNatural())
expAdd("Cla1Regs._MR0.f32", getNatural())
expAdd("Cla1Regs._MR0.f32", getHex())
expAdd("Cla1Regs._MR1.i32", getNatural())
expAdd("Cla1Regs._MR1.f32", getNatural())
expAdd("Cla1Regs._MR1.f32", getHex())
expAdd("Cla1Regs._MR2.i32", getNatural())
expAdd("Cla1Regs._MR2.f32", getNatural())
expAdd("Cla1Regs._MR2.f32", getHex())
expAdd("Cla1Regs._MR3.i32", getNatural())
expAdd("Cla1Regs._MR3.f32", getNatural())
expAdd("Cla1Regs._MR3.f32", getHex())

openAnalysisView('Dual Time','C:/ti/c2000/C2000Ware_1_00_04_00/libraries/math/CLAmath/c28/examples/acos/acos.graphProp')
