/* Note: this linker command file only defines CRC-specific algorithm directives, other parts of the device linker file are generated by sysconfig */

SECTIONS
{
   .TI.crctab	    : > RAMLS3
   /* Test specific sections */
   UNION (TEST_INPUT_CRC) : RUN = RAMLS3, RUN_START(testInputRunStart){
      testInput     :{} LOAD = RAMLS3,
                        LOAD_START(testInputLoadStart),
                        LOAD_SIZE(testInputLoadSize),
                        crc_table(linkerCrcTable, algorithm = CRC16_802_15_4)
         }crc_table(linkerCrcTable, algorithm = CRC16_ALT)

}


/*
//===========================================================================
// End of file.
//===========================================================================
*/
