SET CLB_SIM_COMPILER=C:\TDM-GCC-64\bin
SET C2000WARE_ROOT=\
SET SYSTEMC_INSTALL=%C2000WARE_ROOT%\systemc-2.3.3
SET BuildDirectory=%C2000WARE_ROOT%\systemc\src

SET MODEL_HEADERS_DIR=%C2000WARE_ROOT%\systemc\include
SET MODEL_SOURCE_DIR=%C2000WARE_ROOT%\systemc\src
SET MODEL_HEADERS_DIR_TYPE2=%C2000WARE_ROOT%\systemc\include\type2
SET MODEL_SOURCE_DIR_TYPE2=%C2000WARE_ROOT%\systemc\src\type2
SET MODEL_HEADERS_DIR_TYPE3=%C2000WARE_ROOT%\systemc\include\type3
SET MODEL_SOURCE_DIR_TYPE3=%C2000WARE_ROOT%\systemc\src\type3

%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\CLB_LUT4_SC_model.d		-MT%BuildDirectory%\CLB_LUT4_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\CLB_LUT4_SC_model.o 		%MODEL_SOURCE_DIR%\CLB_LUT4_SC_model.cpp 1> lut4_compile_result0.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\CLB_FSM_SC_model.d		-MT%BuildDirectory%\CLB_FSM_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\CLB_FSM_SC_model.o		%MODEL_SOURCE_DIR%\CLB_FSM_SC_model.cpp 1> fsm_compile_result0.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\CLB_counter_SC_model.d	-MT%BuildDirectory%\CLB_counter_SC_model.o 	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\CLB_counter_SC_model.o		%MODEL_SOURCE_DIR%\CLB_counter_SC_model.cpp 1> counter_compile_result0.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\CLB_HLC_SC_model.d		-MT%BuildDirectory%\CLB_HLC_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\CLB_HLC_SC_model.o		%MODEL_SOURCE_DIR%\CLB_HLC_SC_model.cpp 1> hlc_compile_result0.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\CLB_OutputLUT_SC_model.d	-MT%BuildDirectory%\CLB_OutputLUT_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\CLB_OutputLUT_SC_model.o	%MODEL_SOURCE_DIR%\CLB_OutputLUT_SC_model.cpp 1> outlut_compile_result0.txt 2>&1

%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_LUT4_SC_model.d		-MT%BuildDirectory%\type2\CLB_LUT4_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_LUT4_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_LUT4_SC_model.cpp 1> lut4_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_FSM_SC_model.d		-MT%BuildDirectory%\type2\CLB_FSM_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_FSM_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_FSM_SC_model.cpp 1> fsm_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_counter_SC_model.d		-MT%BuildDirectory%\type2\CLB_counter_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_counter_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_counter_SC_model.cpp 1> counter_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_HLC_SC_model.d		-MT%BuildDirectory%\type2\CLB_HLC_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_HLC_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_HLC_SC_model.cpp 1> hlc_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_OutputLUT_SC_model.d		-MT%BuildDirectory%\type2\CLB_OutputLUT_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_OutputLUT_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_OutputLUT_SC_model.cpp 1> outlut_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_LUT4_top_SC_model.d		-MT%BuildDirectory%\type2\CLB_LUT4_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_LUT4_top_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_LUT4_top_SC_model.cpp 1> lut4_top_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_FSM_top_SC_model.d		-MT%BuildDirectory%\type2\CLB_FSM_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_FSM_top_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_FSM_top_SC_model.cpp 1> fsm_top_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_counter_top_SC_model.d	-MT%BuildDirectory%\type2\CLB_counter_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_counter_top_SC_model.o	%MODEL_SOURCE_DIR_TYPE2%\CLB_counter_top_SC_model.cpp 1> counter_top_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_OutputLUT_top_SC_model.d	-MT%BuildDirectory%\type2\CLB_OutputLUT_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_OutputLUT_top_SC_model.o	%MODEL_SOURCE_DIR_TYPE2%\CLB_OutputLUT_top_SC_model.cpp 1> outlut_top_compile_result1.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE2% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type2\CLB_AOC_SC_model.d		-MT%BuildDirectory%\type2\CLB_AOC_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type2\CLB_AOC_SC_model.o		%MODEL_SOURCE_DIR_TYPE2%\CLB_AOC_SC_model.cpp 1> aoc_compile_result1.txt 2>&1

%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_LUT4_SC_model.d		-MT%BuildDirectory%\type3\CLB_LUT4_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_LUT4_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_LUT4_SC_model.cpp 1> lut4_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_FSM_SC_model.d		-MT%BuildDirectory%\type3\CLB_FSM_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_FSM_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_FSM_SC_model.cpp 1> fsm_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_counter_SC_model.d	-MT%BuildDirectory%\type3\CLB_counter_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_counter_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_counter_SC_model.cpp 1> counter_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_HLC_SC_model.d		-MT%BuildDirectory%\type3\CLB_HLC_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_HLC_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_HLC_SC_model.cpp 1> hlc_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_OutputLUT_SC_model.d	-MT%BuildDirectory%\type3\CLB_OutputLUT_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_OutputLUT_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_OutputLUT_SC_model.cpp 1> outlut_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_LUT4_top_SC_model.d	-MT%BuildDirectory%\type3\CLB_LUT4_top_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_LUT4_top_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_LUT4_top_SC_model.cpp 1> lut4_top_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_FSM_top_SC_model.d	-MT%BuildDirectory%\type3\CLB_FSM_top_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_FSM_top_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_FSM_top_SC_model.cpp 1> fsm_top_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_counter_top_SC_model.d	-MT%BuildDirectory%\type3\CLB_counter_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_counter_top_SC_model.o	%MODEL_SOURCE_DIR_TYPE3%\CLB_counter_top_SC_model.cpp 1> counter_top_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_OutputLUT_top_SC_model.d -MT%BuildDirectory%\type3\CLB_OutputLUT_top_SC_model.o	-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_OutputLUT_top_SC_model.o	%MODEL_SOURCE_DIR_TYPE3%\CLB_OutputLUT_top_SC_model.cpp 1> outlut_top_compile_result2.txt 2>&1
%CLB_SIM_COMPILER%\g++  -c -DCLB_SIM -I%SYSTEMC_INSTALL%\src -I%MODEL_HEADERS_DIR_TYPE3% -I%CLB_SIM_COMPILER%\include -Og -g -gdwarf-3 -gstrict-dwarf -Wall -MMD -MP -MF%BuildDirectory%\type3\CLB_AOC_SC_model.d		-MT%BuildDirectory%\type3\CLB_AOC_SC_model.o		-I%BuildDirectory%\syscfg   -fno-threadsafe-statics  -o%BuildDirectory%\type3\CLB_AOC_SC_model.o		%MODEL_SOURCE_DIR_TYPE3%\CLB_AOC_SC_model.cpp 1> aoc_compile_result2.txt 2>&1

PAUSE
