let f280013x_sect = [
	{ name: 'SECT0', displayName: 'FLASH Sector 0',  description : 'FLASH Sector 0 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT1', displayName: 'FLASH Sector 1',  description : 'FLASH Sector 1 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT2', displayName: 'FLASH Sector 2',  description : 'FLASH Sector 2 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT3', displayName: 'FLASH Sector 3',  description : 'FLASH Sector 3 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT4', displayName: 'FLASH Sector 4',  description : 'FLASH Sector 4 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT5', displayName: 'FLASH Sector 5',  description : 'FLASH Sector 5 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT6', displayName: 'FLASH Sector 6',  description : 'FLASH Sector 6 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT7', displayName: 'FLASH Sector 7',  description : 'FLASH Sector 7 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT8', displayName: 'FLASH Sector 8',  description : 'FLASH Sector 8 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT9', displayName: 'FLASH Sector 9',  description : 'FLASH Sector 9 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT10', displayName: 'FLASH Sector 10',  description : 'FLASH Sector 10 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT11', displayName: 'FLASH Sector 11',  description : 'FLASH Sector 11 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT12', displayName: 'FLASH Sector 12',  description : 'FLASH Sector 12 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT13', displayName: 'FLASH Sector 13',  description : 'FLASH Sector 13 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT14', displayName: 'FLASH Sector 14',  description : 'FLASH Sector 14 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT15', displayName: 'FLASH Sector 15',  description : 'FLASH Sector 15 Zone Selections.',  default: 'UNSECURE' },
	
	{ name: 'SECT16', displayName: 'FLASH Sector 16',  description : 'FLASH Sector 16 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT17', displayName: 'FLASH Sector 17',  description : 'FLASH Sector 17 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT18', displayName: 'FLASH Sector 18',  description : 'FLASH Sector 18 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT19', displayName: 'FLASH Sector 19',  description : 'FLASH Sector 19 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT20', displayName: 'FLASH Sector 20',  description : 'FLASH Sector 20 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT21', displayName: 'FLASH Sector 21',  description : 'FLASH Sector 21 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT22', displayName: 'FLASH Sector 22',  description : 'FLASH Sector 22 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT23', displayName: 'FLASH Sector 23',  description : 'FLASH Sector 23 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT24', displayName: 'FLASH Sector 24',  description : 'FLASH Sector 24 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT25', displayName: 'FLASH Sector 25',  description : 'FLASH Sector 25 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT26', displayName: 'FLASH Sector 26',  description : 'FLASH Sector 26 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT27', displayName: 'FLASH Sector 27',  description : 'FLASH Sector 27 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT28', displayName: 'FLASH Sector 28',  description : 'FLASH Sector 28 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT29', displayName: 'FLASH Sector 29',  description : 'FLASH Sector 29 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT30', displayName: 'FLASH Sector 30',  description : 'FLASH Sector 30 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT31', displayName: 'FLASH Sector 31',  description : 'FLASH Sector 31 Zone Selections.',  default: 'UNSECURE' },

	{ name: 'SECT32_39',  displayName: 'FLASH Sector 32 to 39',  description : 'FLASH Sector 32 to 39 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT40_47',  displayName: 'FLASH Sector 40 to 47',  description : 'FLASH Sector 40 to 47 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT48_55',  displayName: 'FLASH Sector 48 to 55',  description : 'FLASH Sector 48 to 55 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT56_63',  displayName: 'FLASH Sector 56 to 63',  description : 'FLASH Sector 56 to 63 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT64_71',  displayName: 'FLASH Sector 64 to 71',  description : 'FLASH Sector 64 to 71 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT72_79',  displayName: 'FLASH Sector 72 to 79',  description : 'FLASH Sector 72 to 79 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT80_87',  displayName: 'FLASH Sector 80 to 87',  description : 'FLASH Sector 80 to 87 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT88_95',  displayName: 'FLASH Sector 88 to 95',  description : 'FLASH Sector 88 to 95 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT96_103', displayName: 'FLASH Sector 96 to 103', description : 'FLASH Sector 96 to 103 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT104_111', displayName: 'FLASH Sector 104 to 111',  description : 'FLASH Sector 104 to 111 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT112_119', displayName: 'FLASH Sector 112 to 119',  description : 'FLASH Sector 112 to 119 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT120_127', displayName: 'FLASH Sector 120 to 127',  description : 'FLASH Sector 120 to 127 Zone Selections.',  default: 'UNSECURE' },
]
exports={
	f280013x_sect : f280013x_sect
};
