let f2838x_sect = [
	{ name: 'SECT0', displayName: 'CPU1 FLASH Sector 0',  description : 'CPU1 FLASH Sector 0 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT1', displayName: 'CPU1 FLASH Sector 1',  description : 'CPU1 FLASH Sector 1 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT2', displayName: 'CPU1 FLASH Sector 2',  description : 'CPU1 FLASH Sector 2 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT3', displayName: 'CPU1 FLASH Sector 3',  description : 'CPU1 FLASH Sector 3 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT4', displayName: 'CPU1 FLASH Sector 4',  description : 'CPU1 FLASH Sector 4 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT5', displayName: 'CPU1 FLASH Sector 5',  description : 'CPU1 FLASH Sector 5 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT6', displayName: 'CPU1 FLASH Sector 6',  description : 'CPU1 FLASH Sector 6 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT7', displayName: 'CPU1 FLASH Sector 7',  description : 'CPU1 FLASH Sector 7 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT8', displayName: 'CPU1 FLASH Sector 8',  description : 'CPU1 FLASH Sector 8 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT9', displayName: 'CPU1 FLASH Sector 9',  description : 'CPU1 FLASH Sector 9 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT10', displayName: 'CPU1 FLASH Sector 10',  description : 'CPU1 FLASH Sector 10 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT11', displayName: 'CPU1 FLASH Sector 11',  description : 'CPU1 FLASH Sector 11 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT12', displayName: 'CPU1 FLASH Sector 12',  description : 'CPU1 FLASH Sector 12 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'SECT13', displayName: 'CPU1 FLASH Sector 13',  description : 'CPU1 FLASH Sector 13 Zone Selections.',  default: 'UNSECURE' },

	{ name: 'CM_SECT0', displayName: 'CM FLASH Sector 0',  description : 'CM FLASH Sector 0 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT1', displayName: 'CM FLASH Sector 1',  description : 'CM FLASH Sector 1 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT2', displayName: 'CM FLASH Sector 2',  description : 'CM FLASH Sector 2 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT3', displayName: 'CM FLASH Sector 3',  description : 'CM FLASH Sector 3 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT4', displayName: 'CM FLASH Sector 4',  description : 'CM FLASH Sector 4 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT5', displayName: 'CM FLASH Sector 5',  description : 'CM FLASH Sector 5 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT6', displayName: 'CM FLASH Sector 6',  description : 'CM FLASH Sector 6 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT7', displayName: 'CM FLASH Sector 7',  description : 'CM FLASH Sector 7 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT8', displayName: 'CM FLASH Sector 8',  description : 'CM FLASH Sector 8 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT9', displayName: 'CM FLASH Sector 9',  description : 'CM FLASH Sector 9 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT10', displayName: 'CM FLASH Sector 10',  description : 'CM FLASH Sector 10 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT11', displayName: 'CM FLASH Sector 11',  description : 'CM FLASH Sector 11 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT12', displayName: 'CM FLASH Sector 12',  description : 'CM FLASH Sector 12 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CM_SECT13', displayName: 'CM FLASH Sector 13',  description : 'CM FLASH Sector 13 Zone Selections.',  default: 'UNSECURE' },
	
	{ name: 'CPU2_SECT0', displayName: 'CPU2 FLASH Sector 0',  description : 'CPU2 FLASH Sector 0 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT1', displayName: 'CPU2 FLASH Sector 1',  description : 'CPU2 FLASH Sector 1 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT2', displayName: 'CPU2 FLASH Sector 2',  description : 'CPU2 FLASH Sector 2 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT3', displayName: 'CPU2 FLASH Sector 3',  description : 'CPU2 FLASH Sector 3 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT4', displayName: 'CPU2 FLASH Sector 4',  description : 'CPU2 FLASH Sector 4 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT5', displayName: 'CPU2 FLASH Sector 5',  description : 'CPU2 FLASH Sector 5 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT6', displayName: 'CPU2 FLASH Sector 6',  description : 'CPU2 FLASH Sector 6 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT7', displayName: 'CPU2 FLASH Sector 7',  description : 'CPU2 FLASH Sector 7 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT8', displayName: 'CPU2 FLASH Sector 8',  description : 'CPU2 FLASH Sector 8 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT9', displayName: 'CPU2 FLASH Sector 9',  description : 'CPU2 FLASH Sector 9 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT10', displayName: 'CPU2 FLASH Sector 10',  description : 'CPU2 FLASH Sector 10 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT11', displayName: 'CPU2 FLASH Sector 11',  description : 'CPU2 FLASH Sector 11 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT12', displayName: 'CPU2 FLASH Sector 12',  description : 'CPU2 FLASH Sector 12 Zone Selections.',  default: 'UNSECURE' },
	{ name: 'CPU2_SECT13', displayName: 'CPU2 FLASH Sector 13',  description : 'CPU2 FLASH Sector 13 Zone Selections.',  default: 'UNSECURE' },

]
exports={
	f2838x_sect : f2838x_sect
};
