let CLA_TaskNumber = [
	{ name: "CLA_TASK_1", displayName: "CLA Task 1" },
	{ name: "CLA_TASK_2", displayName: "CLA Task 2" },
	{ name: "CLA_TASK_3", displayName: "CLA Task 3" },
	{ name: "CLA_TASK_4", displayName: "CLA Task 4" },
	{ name: "CLA_TASK_5", displayName: "CLA Task 5" },
	{ name: "CLA_TASK_6", displayName: "CLA Task 6" },
	{ name: "CLA_TASK_7", displayName: "CLA Task 7" },
	{ name: "CLA_TASK_8", displayName: "CLA Task 8" },
]
let CLA_MVECTNumber = [
	{ name: "CLA_MVECT_1", displayName: "Task Interrupt Vector 1" },
	{ name: "CLA_MVECT_2", displayName: "Task Interrupt Vector 2" },
	{ name: "CLA_MVECT_3", displayName: "Task Interrupt Vector 3" },
	{ name: "CLA_MVECT_4", displayName: "Task Interrupt Vector 4" },
	{ name: "CLA_MVECT_5", displayName: "Task Interrupt Vector 5" },
	{ name: "CLA_MVECT_6", displayName: "Task Interrupt Vector 6" },
	{ name: "CLA_MVECT_7", displayName: "Task Interrupt Vector 7" },
	{ name: "CLA_MVECT_8", displayName: "Task Interrupt Vector 8" },
]
let CLA_Trigger = [
	{ name: "CLA_TRIGGER_SOFTWARE", displayName: "CLA Task Trigger Source is Software" },
	{ name: "CLA_TRIGGER_ADCA1", displayName: "CLA Task Trigger Source is ADCA1" },
	{ name: "CLA_TRIGGER_ADCA2", displayName: "CLA Task Trigger Source is ADCA2" },
	{ name: "CLA_TRIGGER_ADCA3", displayName: "CLA Task Trigger Source is ADCA3" },
	{ name: "CLA_TRIGGER_ADCA4", displayName: "CLA Task Trigger Source is ADCA4" },
	{ name: "CLA_TRIGGER_ADCAEVT", displayName: "CLA Task Trigger Source is ADCAEVT" },
	{ name: "CLA_TRIGGER_ADCB1", displayName: "CLA Task Trigger Source is ADCB1" },
	{ name: "CLA_TRIGGER_ADCB2", displayName: "CLA Task Trigger Source is ADCB2" },
	{ name: "CLA_TRIGGER_ADCB3", displayName: "CLA Task Trigger Source is ADCB3" },
	{ name: "CLA_TRIGGER_ADCB4", displayName: "CLA Task Trigger Source is ADCB4" },
	{ name: "CLA_TRIGGER_ADCBEVT", displayName: "CLA Task Trigger Source is ADCBEVT" },
	{ name: "CLA_TRIGGER_ADCD1", displayName: "CLA Task Trigger Source is ADCD1" },
	{ name: "CLA_TRIGGER_ADCD2", displayName: "CLA Task Trigger Source is ADCD2" },
	{ name: "CLA_TRIGGER_ADCD3", displayName: "CLA Task Trigger Source is ADCD3" },
	{ name: "CLA_TRIGGER_ADCD4", displayName: "CLA Task Trigger Source is ADCD4" },
	{ name: "CLA_TRIGGER_ADCDEVT", displayName: "CLA Task Trigger Source is ADCDEVT" },
	{ name: "CLA_TRIGGER_XINT1", displayName: "CLA Task Trigger Source is XINT1" },
	{ name: "CLA_TRIGGER_XINT2", displayName: "CLA Task Trigger Source is XINT2" },
	{ name: "CLA_TRIGGER_XINT3", displayName: "CLA Task Trigger Source is XINT3" },
	{ name: "CLA_TRIGGER_XINT4", displayName: "CLA Task Trigger Source is XINT4" },
	{ name: "CLA_TRIGGER_XINT5", displayName: "CLA Task Trigger Source is XINT5" },
	{ name: "CLA_TRIGGER_EPWM1INT", displayName: "CLA Task Trigger Source is EPWM1INT" },
	{ name: "CLA_TRIGGER_EPWM2INT", displayName: "CLA Task Trigger Source is EPWM2INT" },
	{ name: "CLA_TRIGGER_EPWM3INT", displayName: "CLA Task Trigger Source is EPWM3INT" },
	{ name: "CLA_TRIGGER_EPWM4INT", displayName: "CLA Task Trigger Source is EPWM4INT" },
	{ name: "CLA_TRIGGER_EPWM5INT", displayName: "CLA Task Trigger Source is EPWM5INT" },
	{ name: "CLA_TRIGGER_EPWM6INT", displayName: "CLA Task Trigger Source is EPWM6INT" },
	{ name: "CLA_TRIGGER_EPWM7INT", displayName: "CLA Task Trigger Source is EPWM7INT" },
	{ name: "CLA_TRIGGER_EPWM8INT", displayName: "CLA Task Trigger Source is EPWM8INT" },
	{ name: "CLA_TRIGGER_EPWM9INT", displayName: "CLA Task Trigger Source is EPWM9INT" },
	{ name: "CLA_TRIGGER_EPWM10INT", displayName: "CLA Task Trigger Source is EPWM10INT" },
	{ name: "CLA_TRIGGER_EPWM11INT", displayName: "CLA Task Trigger Source is EPWM11INT" },
	{ name: "CLA_TRIGGER_EPWM12INT", displayName: "CLA Task Trigger Source is EPWM12INT" },
	{ name: "CLA_TRIGGER_TINT0", displayName: "CLA Task Trigger Source is TINT0" },
	{ name: "CLA_TRIGGER_TINT1", displayName: "CLA Task Trigger Source is TINT1" },
	{ name: "CLA_TRIGGER_TINT2", displayName: "CLA Task Trigger Source is TINT2" },
	{ name: "CLA_TRIGGER_MXINTA", displayName: "CLA Task Trigger Source is MXINTA" },
	{ name: "CLA_TRIGGER_MRINTA", displayName: "CLA Task Trigger Source is MRINTA" },
	{ name: "CLA_TRIGGER_MXINTB", displayName: "CLA Task Trigger Source is MXINTB" },
	{ name: "CLA_TRIGGER_MRINTB", displayName: "CLA Task Trigger Source is MRINTB" },
	{ name: "CLA_TRIGGER_ECAP1INT", displayName: "CLA Task Trigger Source is ECAP1INT" },
	{ name: "CLA_TRIGGER_ECAP2INT", displayName: "CLA Task Trigger Source is ECAP2INT" },
	{ name: "CLA_TRIGGER_ECAP3INT", displayName: "CLA Task Trigger Source is ECAP3INT" },
	{ name: "CLA_TRIGGER_ECAP4INT", displayName: "CLA Task Trigger Source is ECAP4INT" },
	{ name: "CLA_TRIGGER_ECAP5INT", displayName: "CLA Task Trigger Source is ECAP5INT" },
	{ name: "CLA_TRIGGER_ECAP6INT", displayName: "CLA Task Trigger Source is ECAP6INT" },
	{ name: "CLA_TRIGGER_EQEP1INT", displayName: "CLA Task Trigger Source is EQEP1INT" },
	{ name: "CLA_TRIGGER_EQEP2INT", displayName: "CLA Task Trigger Source is EQEP2INT" },
	{ name: "CLA_TRIGGER_EQEP3INT", displayName: "CLA Task Trigger Source is EQEP3INT" },
	{ name: "CLA_TRIGGER_SDFM1INT", displayName: "CLA Task Trigger Source is SDFM1INT" },
	{ name: "CLA_TRIGGER_SDFM2INT", displayName: "CLA Task Trigger Source is SDFM2INT" },
	{ name: "CLA_TRIGGER_UPP1INT", displayName: "CLA Task Trigger Source is UPP1INT" },
	{ name: "CLA_TRIGGER_SPITXAINT", displayName: "CLA Task Trigger Source is SPITXAINT" },
	{ name: "CLA_TRIGGER_SPIRXAINT", displayName: "CLA Task Trigger Source is SPIRXAINT" },
	{ name: "CLA_TRIGGER_SPITXBINT", displayName: "CLA Task Trigger Source is SPITXBINT" },
	{ name: "CLA_TRIGGER_SPIRXBINT", displayName: "CLA Task Trigger Source is SPIRXBINT" },
	{ name: "CLA_TRIGGER_SPITXCINT", displayName: "CLA Task Trigger Source is SPITXCINT" },
	{ name: "CLA_TRIGGER_SPIRXCINT", displayName: "CLA Task Trigger Source is SPIRXCINT" },
	{ name: "CLA_TRIGGER_CLB1INT", displayName: "CLA Task Trigger Source is CLB1INT" },
	{ name: "CLA_TRIGGER_CLB2INT", displayName: "CLA Task Trigger Source is CLB2INT" },
	{ name: "CLA_TRIGGER_CLB3INT", displayName: "CLA Task Trigger Source is CLB3INT" },
	{ name: "CLA_TRIGGER_CLB4INT", displayName: "CLA Task Trigger Source is CLB4INT" },
]
let CLA_NUM_EOT_INTERRUPTS = [
	{ name: "CLA_NUM_EOT_INTERRUPTS", displayName: "NUM EOT INTERRUPTS" },
]
let CLA_TASKFLAG = [
	{ name: "CLA_TASKFLAG_1", displayName: "CLA Task 1 Flag" },
	{ name: "CLA_TASKFLAG_2", displayName: "CLA Task 2 Flag" },
	{ name: "CLA_TASKFLAG_3", displayName: "CLA Task 3 Flag" },
	{ name: "CLA_TASKFLAG_4", displayName: "CLA Task 4 Flag" },
	{ name: "CLA_TASKFLAG_5", displayName: "CLA Task 5 Flag" },
	{ name: "CLA_TASKFLAG_6", displayName: "CLA Task 6 Flag" },
	{ name: "CLA_TASKFLAG_7", displayName: "CLA Task 7 Flag" },
	{ name: "CLA_TASKFLAG_8", displayName: "CLA Task 8 Flag" },
	{ name: "CLA_TASKFLAG_ALL", displayName: "CLA All Task Flag" },
]
module.exports = {
	CLA_TaskNumber: CLA_TaskNumber,
	CLA_MVECTNumber: CLA_MVECTNumber,
	CLA_Trigger: CLA_Trigger,
	CLA_NUM_EOT_INTERRUPTS: CLA_NUM_EOT_INTERRUPTS,
	CLA_TASKFLAG: CLA_TASKFLAG,
}
