let interrupts = [
	{ int_define_name: "INT_TIMER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 1 Interrupt" },
	{ int_define_name: "INT_TIMER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 2 Interrupt" },
	{ int_define_name: "INT_DATALOG", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Datalogging Interrupt" },
	{ int_define_name: "INT_RTOS", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "RTOS Interrupt from ERAD" },
	{ int_define_name: "INT_EMU", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Emulation Interrupt" },
	{ int_define_name: "INT_NMI", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Non-Maskable Interrupt" },
	{ int_define_name: "INT_ILLEGAL", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Illegal Operation Trap" },
	{ int_define_name: "INT_USER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 1" },
	{ int_define_name: "INT_USER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 2" },
	{ int_define_name: "INT_USER3", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 3" },
	{ int_define_name: "INT_USER4", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 4" },
	{ int_define_name: "INT_USER5", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 5" },
	{ int_define_name: "INT_USER6", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 6" },
	{ int_define_name: "INT_USER7", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 7" },
	{ int_define_name: "INT_USER8", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 8" },
	{ int_define_name: "INT_USER9", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 9" },
	{ int_define_name: "INT_USER10", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 10" },
	{ int_define_name: "INT_USER11", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 11" },
	{ int_define_name: "INT_USER12", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 12" },
	{ int_define_name: "INT_ADCA1", int_group_channel_number: "1.1", int_group_number: "1", int_channel_number: "1", int_description: "ADCA Interrupt 1" },
	{ int_define_name: "INT_ADCC1", int_group_channel_number: "1.2", int_group_number: "1", int_channel_number: "2", int_description: "ADCC Interrupt 1" },
	{ int_define_name: "INT_XINT1", int_group_channel_number: "1.4", int_group_number: "1", int_channel_number: "4", int_description: "XINT1 Interrupt" },
	{ int_define_name: "INT_XINT2", int_group_channel_number: "1.5", int_group_number: "1", int_channel_number: "5", int_description: "XINT2 Interrupt" },
	{ int_define_name: "INT_SYS_ERR", int_group_channel_number: "1.6", int_group_number: "1", int_channel_number: "6", int_description: "SYS_ERR Interrupt" },
	{ int_define_name: "INT_TIMER0", int_group_channel_number: "1.7", int_group_number: "1", int_channel_number: "7", int_description: "Timer 0 Interrupt" },
	{ int_define_name: "INT_WAKE", int_group_channel_number: "1.8", int_group_number: "1", int_channel_number: "8", int_description: "Standby and Halt Wakeup Interrupt" },
	{ int_define_name: "INT_EPWM1_TZ", int_group_channel_number: "2.1", int_group_number: "2", int_channel_number: "1", int_description: "ePWM1 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM2_TZ", int_group_channel_number: "2.2", int_group_number: "2", int_channel_number: "2", int_description: "ePWM2 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM3_TZ", int_group_channel_number: "2.3", int_group_number: "2", int_channel_number: "3", int_description: "ePWM3 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM4_TZ", int_group_channel_number: "2.4", int_group_number: "2", int_channel_number: "4", int_description: "ePWM4 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM5_TZ", int_group_channel_number: "2.5", int_group_number: "2", int_channel_number: "5", int_description: "ePWM5 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM6_TZ", int_group_channel_number: "2.6", int_group_number: "2", int_channel_number: "6", int_description: "ePWM6 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM7_TZ", int_group_channel_number: "2.7", int_group_number: "2", int_channel_number: "7", int_description: "ePWM7 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM1", int_group_channel_number: "3.1", int_group_number: "3", int_channel_number: "1", int_description: "ePWM1 Interrupt" },
	{ int_define_name: "INT_EPWM2", int_group_channel_number: "3.2", int_group_number: "3", int_channel_number: "2", int_description: "ePWM2 Interrupt" },
	{ int_define_name: "INT_EPWM3", int_group_channel_number: "3.3", int_group_number: "3", int_channel_number: "3", int_description: "ePWM3 Interrupt" },
	{ int_define_name: "INT_EPWM4", int_group_channel_number: "3.4", int_group_number: "3", int_channel_number: "4", int_description: "ePWM4 Interrupt" },
	{ int_define_name: "INT_EPWM5", int_group_channel_number: "3.5", int_group_number: "3", int_channel_number: "5", int_description: "ePWM5 Interrupt" },
	{ int_define_name: "INT_EPWM6", int_group_channel_number: "3.6", int_group_number: "3", int_channel_number: "6", int_description: "ePWM6 Interrupt" },
	{ int_define_name: "INT_EPWM7", int_group_channel_number: "3.7", int_group_number: "3", int_channel_number: "7", int_description: "ePWM7 Interrupt" },
	{ int_define_name: "INT_ECAP1", int_group_channel_number: "4.1", int_group_number: "4", int_channel_number: "1", int_description: "eCAP1 Interrupt" },
	{ int_define_name: "INT_ECAP2", int_group_channel_number: "4.2", int_group_number: "4", int_channel_number: "2", int_description: "eCAP2 Interrupt" },
	{ int_define_name: "INT_ECAP3", int_group_channel_number: "4.3", int_group_number: "4", int_channel_number: "3", int_description: "eCAP3 Interrupt" },
	{ int_define_name: "INT_EQEP1", int_group_channel_number: "5.1", int_group_number: "5", int_channel_number: "1", int_description: "eQEP1 Interrupt" },
	{ int_define_name: "INT_EQEP2", int_group_channel_number: "5.2", int_group_number: "5", int_channel_number: "2", int_description: "eQEP2 Interrupt" },
	{ int_define_name: "INT_SPIA_RX", int_group_channel_number: "6.1", int_group_number: "6", int_channel_number: "1", int_description: "SPIA Receive Interrupt" },
	{ int_define_name: "INT_SPIA_TX", int_group_channel_number: "6.2", int_group_number: "6", int_channel_number: "2", int_description: "SPIA Transmit Interrupt" },
	{ int_define_name: "INT_LINA_0", int_group_channel_number: "6.5", int_group_number: "6", int_channel_number: "5", int_description: "LINA_0 Interrupt" },
	{ int_define_name: "INT_LINA_1", int_group_channel_number: "6.6", int_group_number: "6", int_channel_number: "6", int_description: "LINA_1 Interrupt" },
	{ int_define_name: "INT_DCC0", int_group_channel_number: "6.7", int_group_number: "6", int_channel_number: "7", int_description: "DCC0 Interrupt" },
	{ int_define_name: "INT_PMBUSA", int_group_channel_number: "7.7", int_group_number: "7", int_channel_number: "7", int_description: "PMBUSA Interrupt" },
	{ int_define_name: "INT_I2CA", int_group_channel_number: "8.1", int_group_number: "8", int_channel_number: "1", int_description: "I2CA Interrupt 1" },
	{ int_define_name: "INT_I2CA_FIFO", int_group_channel_number: "8.2", int_group_number: "8", int_channel_number: "2", int_description: "I2CA Interrupt 2" },
	{ int_define_name: "INT_I2CB", int_group_channel_number: "8.3", int_group_number: "8", int_channel_number: "3", int_description: "I2CB Interrupt 1" },
	{ int_define_name: "INT_I2CB_FIFO", int_group_channel_number: "8.4", int_group_number: "8", int_channel_number: "4", int_description: "I2CB Interrupt 2" },
	{ int_define_name: "INT_SCIC_RX", int_group_channel_number: "8.5", int_group_number: "8", int_channel_number: "5", int_description: "SCIC Receive Interrupt" },
	{ int_define_name: "INT_SCIC_TX", int_group_channel_number: "8.6", int_group_number: "8", int_channel_number: "6", int_description: "SCIC Transmit Interrupt" },
	{ int_define_name: "INT_SCIA_RX", int_group_channel_number: "9.1", int_group_number: "9", int_channel_number: "1", int_description: "SCIA Receive Interrupt" },
	{ int_define_name: "INT_SCIA_TX", int_group_channel_number: "9.2", int_group_number: "9", int_channel_number: "2", int_description: "SCIA Transmit Interrupt" },
	{ int_define_name: "INT_SCIB_RX", int_group_channel_number: "9.3", int_group_number: "9", int_channel_number: "3", int_description: "SCIB Receive Interrupt" },
	{ int_define_name: "INT_SCIB_TX", int_group_channel_number: "9.4", int_group_number: "9", int_channel_number: "4", int_description: "SCIB Transmit Interrupt" },
	{ int_define_name: "INT_CANA0", int_group_channel_number: "9.5", int_group_number: "9", int_channel_number: "5", int_description: "CANA Interrupt 0" },
	{ int_define_name: "INT_CANA1", int_group_channel_number: "9.6", int_group_number: "9", int_channel_number: "6", int_description: "CANA Interrupt 1" },
	{ int_define_name: "INT_MCANA_0", int_group_channel_number: "9.7", int_group_number: "9", int_channel_number: "7", int_description: "MCAN Sub-System Interrupt 0" },
	{ int_define_name: "INT_MCANA_1", int_group_channel_number: "9.8", int_group_number: "9", int_channel_number: "8", int_description: "MCAN Sub-System Interrupt 1" },
	{ int_define_name: "INT_ADCA_EVT", int_group_channel_number: "10.1", int_group_number: "10", int_channel_number: "1", int_description: "ADCA Event Interrupt" },
	{ int_define_name: "INT_ADCA2", int_group_channel_number: "10.2", int_group_number: "10", int_channel_number: "2", int_description: "ADCA Interrupt 2" },
	{ int_define_name: "INT_ADCA3", int_group_channel_number: "10.3", int_group_number: "10", int_channel_number: "3", int_description: "ADCA Interrupt 3" },
	{ int_define_name: "INT_ADCA4", int_group_channel_number: "10.4", int_group_number: "10", int_channel_number: "4", int_description: "ADCA Interrupt 4" },
	{ int_define_name: "INT_ADCC_EVT", int_group_channel_number: "10.5", int_group_number: "10", int_channel_number: "5", int_description: "ADCC Event Interrupt" },
	{ int_define_name: "INT_ADCC2", int_group_channel_number: "10.6", int_group_number: "10", int_channel_number: "6", int_description: "ADCC Interrupt 2" },
	{ int_define_name: "INT_ADCC3", int_group_channel_number: "10.7", int_group_number: "10", int_channel_number: "7", int_description: "ADCC Interrupt 3" },
	{ int_define_name: "INT_ADCC4", int_group_channel_number: "10.8", int_group_number: "10", int_channel_number: "8", int_description: "ADCC Interrupt 4" },
	{ int_define_name: "INT_XINT3", int_group_channel_number: "12.1", int_group_number: "12", int_channel_number: "1", int_description: "XINT3 Interrupt" },
	{ int_define_name: "INT_XINT4", int_group_channel_number: "12.2", int_group_number: "12", int_channel_number: "2", int_description: "XINT4 Interrupt" },
	{ int_define_name: "INT_XINT5", int_group_channel_number: "12.3", int_group_number: "12", int_channel_number: "3", int_description: "XINT5 Interrupt" },
	{ int_define_name: "INT_FLSS", int_group_channel_number: "12.5", int_group_number: "12", int_channel_number: "5", int_description: "Interrupt from flash sub-system" },
	{ int_define_name: "INT_VCU", int_group_channel_number: "12.6", int_group_number: "12", int_channel_number: "6", int_description: "VCU Interrupt (VCRC)" },
	{ int_define_name: "INT_MCANA_ECC", int_group_channel_number: "12.7", int_group_number: "12", int_channel_number: "7", int_description: "MCAN Sub-System ECC error Interrupt" },
	{ int_define_name: "INT_MCANA_WAKE", int_group_channel_number: "12.8", int_group_number: "12", int_channel_number: "8", int_description: "MCAN Sub-System wakeup Interrupt" },
];
module.exports = {
	interrupts: interrupts,
}
