let SysCtl_PeripheralPCLOCKCR = [
	{ name: "SYSCTL_PERIPH_CLK_DMA", displayName: "DMA clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER0", displayName: "CPUTIMER0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER1", displayName: "CPUTIMER1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER2", displayName: "CPUTIMER2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CPUBGCRC", displayName: "CPUBGCRC clock" },
	{ name: "SYSCTL_PERIPH_CLK_HRCAL", displayName: "HRCAL clock" },
	{ name: "SYSCTL_PERIPH_CLK_TBCLKSYNC", displayName: "TBCLKSYNC clock" },
	{ name: "SYSCTL_PERIPH_CLK_ERAD", displayName: "ERAD clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM1", displayName: "EPWM1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM2", displayName: "EPWM2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM3", displayName: "EPWM3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM4", displayName: "EPWM4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM5", displayName: "EPWM5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM6", displayName: "EPWM6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM7", displayName: "EPWM7 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP1", displayName: "ECAP1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP2", displayName: "ECAP2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP3", displayName: "ECAP3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP1", displayName: "EQEP1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP2", displayName: "EQEP2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SCIA", displayName: "SCI_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPIA", displayName: "SPI_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPIB", displayName: "SPI_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_I2CA", displayName: "I2C_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_I2CB", displayName: "I2C_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_CANA", displayName: "CAN_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCA", displayName: "ADC_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCC", displayName: "ADC_C clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS1", displayName: "CMPSS1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS2", displayName: "CMPSS2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS3", displayName: "CMPSS3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS4", displayName: "CMPSS4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB1", displayName: "CLB1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB2", displayName: "CLB2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSITXA", displayName: "FSITX_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSIRXA", displayName: "FSIRX_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_LINA", displayName: "LIN_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_LINB", displayName: "LIN_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_PMBUSA", displayName: "PMBUS_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_DCC0", displayName: "DCC0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_DCC1", displayName: "DCC1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_MPOST0", displayName: "MPOST0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_HICA", displayName: "HICA clock" },
]
let SysCtl_PeripheralSOFTPRES = [
	{ name: "SYSCTL_PERIPH_RES_CPU1CPUBGCRC", displayName: "Reset CPU1_CPUBGCRC clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU1ERAD", displayName: "Reset CPU1_ERAD clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM1", displayName: "Reset EPWM1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM2", displayName: "Reset EPWM2 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM3", displayName: "Reset EPWM3 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM4", displayName: "Reset EPWM4 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM5", displayName: "Reset EPWM5 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM6", displayName: "Reset EPWM6 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM7", displayName: "Reset EPWM7 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP1", displayName: "Reset ECAP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP2", displayName: "Reset ECAP2 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP3", displayName: "Reset ECAP3 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP1", displayName: "Reset EQEP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP2", displayName: "Reset EQEP2 clock" },
	{ name: "SYSCTL_PERIPH_RES_SCIA", displayName: "Reset SCI_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIA", displayName: "Reset SPI_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIB", displayName: "Reset SPI_B clock" },
	{ name: "SYSCTL_PERIPH_RES_I2CA", displayName: "Reset I2C_A clock" },
	{ name: "SYSCTL_PERIPH_RES_I2CB", displayName: "Reset I2C_B clock" },
	{ name: "SYSCTL_PERIPH_RES_CANA", displayName: "Reset CAN_A clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCA", displayName: "Reset ADC_A clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCC", displayName: "Reset ADC_C clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS1", displayName: "Reset CMPSS1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS2", displayName: "Reset CMPSS2 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS3", displayName: "Reset CMPSS3 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS4", displayName: "Reset CMPSS4 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB1", displayName: "Reset CLB1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB2", displayName: "Reset CLB2 clock" },
	{ name: "SYSCTL_PERIPH_RES_FSITXA", displayName: "Reset FSITX_A clock" },
	{ name: "SYSCTL_PERIPH_RES_FSIRXA", displayName: "Reset FSIRX_A clock" },
	{ name: "SYSCTL_PERIPH_RES_LINA", displayName: "Reset LIN_A clock" },
	{ name: "SYSCTL_PERIPH_RES_LINB", displayName: "Reset LIN_B clock" },
	{ name: "SYSCTL_PERIPH_RES_PMBUSA", displayName: "Reset PMBUS_A clock" },
	{ name: "SYSCTL_PERIPH_RES_DCC0", displayName: "Reset DCC0 clock" },
	{ name: "SYSCTL_PERIPH_RES_DCC1", displayName: "Reset DCC1 clock" },
	{ name: "SYSCTL_PERIPH_RES_HICA", displayName: "Reset HIC_A clock" },
]
let SysCtl_WDPredivider = [
	{ name: "SYSCTL_WD_PREDIV_2", displayName: "PREDIVCLK = INTOSC1 / 2" },
	{ name: "SYSCTL_WD_PREDIV_4", displayName: "PREDIVCLK = INTOSC1 / 4" },
	{ name: "SYSCTL_WD_PREDIV_8", displayName: "PREDIVCLK = INTOSC1 / 8" },
	{ name: "SYSCTL_WD_PREDIV_16", displayName: "PREDIVCLK = INTOSC1 / 16" },
	{ name: "SYSCTL_WD_PREDIV_32", displayName: "PREDIVCLK = INTOSC1 / 32" },
	{ name: "SYSCTL_WD_PREDIV_64", displayName: "PREDIVCLK = INTOSC1 / 64" },
	{ name: "SYSCTL_WD_PREDIV_128", displayName: "PREDIVCLK = INTOSC1 / 128" },
	{ name: "SYSCTL_WD_PREDIV_256", displayName: "PREDIVCLK = INTOSC1 / 256" },
	{ name: "SYSCTL_WD_PREDIV_512", displayName: "PREDIVCLK = INTOSC1 / 512" },
	{ name: "SYSCTL_WD_PREDIV_1024", displayName: "PREDIVCLK = INTOSC1 / 1024" },
	{ name: "SYSCTL_WD_PREDIV_2048", displayName: "PREDIVCLK = INTOSC1 / 2048" },
	{ name: "SYSCTL_WD_PREDIV_4096", displayName: "PREDIVCLK = INTOSC1 / 4096" },
]
let SysCtl_WDPrescaler = [
	{ name: "SYSCTL_WD_PRESCALE_1", displayName: "WDCLK = PREDIVCLK / 1" },
	{ name: "SYSCTL_WD_PRESCALE_2", displayName: "WDCLK = PREDIVCLK / 2" },
	{ name: "SYSCTL_WD_PRESCALE_4", displayName: "WDCLK = PREDIVCLK / 4" },
	{ name: "SYSCTL_WD_PRESCALE_8", displayName: "WDCLK = PREDIVCLK / 8" },
	{ name: "SYSCTL_WD_PRESCALE_16", displayName: "WDCLK = PREDIVCLK / 16" },
	{ name: "SYSCTL_WD_PRESCALE_32", displayName: "WDCLK = PREDIVCLK / 32" },
	{ name: "SYSCTL_WD_PRESCALE_64", displayName: "WDCLK = PREDIVCLK / 64" },
]
let SysCtl_WDMode = [
	{ name: "SYSCTL_WD_MODE_RESET", displayName: "Watchdog can generate a reset signal" },
	{ name: "SYSCTL_WD_MODE_INTERRUPT", displayName: "Watchdog can generate an interrupt signal; reset signal is disabled" },
]
let SysCtl_LSPCLKPrescaler = [
	{ name: "SYSCTL_LSPCLK_PRESCALE_1", displayName: "LSPCLK = SYSCLK / 1" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_2", displayName: "LSPCLK = SYSCLK / 2" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_4", displayName: "LSPCLK = SYSCLK / 4 (default)" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_6", displayName: "LSPCLK = SYSCLK / 6" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_8", displayName: "LSPCLK = SYSCLK / 8" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_10", displayName: "LSPCLK = SYSCLK / 10" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_12", displayName: "LSPCLK = SYSCLK / 12" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_14", displayName: "LSPCLK = SYSCLK / 14" },
]
let SysCtl_AccessPeripheral = [
	{ name: "SYSCTL_ACCESS_ADCA", displayName: "ADCA access" },
	{ name: "SYSCTL_ACCESS_ADCC", displayName: "ADCC access" },
	{ name: "SYSCTL_ACCESS_CMPSS1", displayName: "CMPSS1 access" },
	{ name: "SYSCTL_ACCESS_CMPSS2", displayName: "CMPSS2 access" },
	{ name: "SYSCTL_ACCESS_CMPSS3", displayName: "CMPSS3 access" },
	{ name: "SYSCTL_ACCESS_CMPSS4", displayName: "CMPSS4 access" },
	{ name: "SYSCTL_ACCESS_EPWM1", displayName: "EPWM1 access" },
	{ name: "SYSCTL_ACCESS_EPWM2", displayName: "EPWM2 access" },
	{ name: "SYSCTL_ACCESS_EPWM3", displayName: "EPWM3 access" },
	{ name: "SYSCTL_ACCESS_EPWM4", displayName: "EPWM4 access" },
	{ name: "SYSCTL_ACCESS_EPWM5", displayName: "EPWM5 access" },
	{ name: "SYSCTL_ACCESS_EPWM6", displayName: "EPWM6 access" },
	{ name: "SYSCTL_ACCESS_EPWM7", displayName: "EPWM7 access" },
	{ name: "SYSCTL_ACCESS_EQEP1", displayName: "EQEP1 access" },
	{ name: "SYSCTL_ACCESS_EQEP2", displayName: "EQEP2 access" },
	{ name: "SYSCTL_ACCESS_ECAP1", displayName: "ECAP1 access" },
	{ name: "SYSCTL_ACCESS_ECAP2", displayName: "ECAP2 access" },
	{ name: "SYSCTL_ACCESS_ECAP3", displayName: "ECAP3 access" },
	{ name: "SYSCTL_ACCESS_CLB1", displayName: "CLB1 access" },
	{ name: "SYSCTL_ACCESS_CLB2", displayName: "CLB2 access" },
	{ name: "SYSCTL_ACCESS_SCIA", displayName: "SCIA access" },
	{ name: "SYSCTL_ACCESS_SPIA", displayName: "SPIA access" },
	{ name: "SYSCTL_ACCESS_SPIB", displayName: "SPIB access" },
	{ name: "SYSCTL_ACCESS_I2CA", displayName: "I2CA access" },
	{ name: "SYSCTL_ACCESS_I2CB", displayName: "I2CB access" },
	{ name: "SYSCTL_ACCESS_PMBUSA", displayName: "PMBUS_A access" },
	{ name: "SYSCTL_ACCESS_LINA", displayName: "LIN_A access" },
	{ name: "SYSCTL_ACCESS_LINB", displayName: "LIN_B access" },
	{ name: "SYSCTL_ACCESS_CANA", displayName: "DCANA access" },
	{ name: "SYSCTL_ACCESS_FSIATX", displayName: "FSIATX access" },
	{ name: "SYSCTL_ACCESS_FSIARX", displayName: "FSIARX access" },
	{ name: "SYSCTL_ACCESS_HRPWMA", displayName: "HRPWM_A access" },
	{ name: "SYSCTL_ACCESS_HICA", displayName: "HIC_A access" },
]
let SysCtl_AccessController = [
	{ name: "SYSCTL_ACCESS_CPU1", displayName: "CPU access to the peripheral" },
	{ name: "SYSCTL_ACCESS_DMA1", displayName: "DMA access to the peripheral" },
	{ name: "SYSCTL_ACCESS_HIC", displayName: "HICA access to the peripheral", legacyNames: ["SYSCTL_ACCESS_HICMASTER"]},
]
let SysCtl_AccessPermission = [
	{ name: "SYSCTL_ACCESS_FULL", displayName: "Full Access for both read and write." },
	{ name: "SYSCTL_ACCESS_PROTECTED", displayName: "Protected RD access such that FIFOs. Clear on read, registers are not changed and no write access." },
	{ name: "SYSCTL_ACCESS_NONE", displayName: "No read or write access." },
]
let SysCtl_ClockOut = [
	{ name: "SYSCTL_CLOCKOUT_PLLSYS", displayName: "PLL System Clock post SYSCLKDIV" },
	{ name: "SYSCTL_CLOCKOUT_PLLRAW", displayName: "PLL Clock after Bypass Mux" },
	{ name: "SYSCTL_CLOCKOUT_SYSCLK", displayName: "CPU System Clock" },
	{ name: "SYSCTL_CLOCKOUT_INTOSC1", displayName: "Internal Oscillator 1" },
	{ name: "SYSCTL_CLOCKOUT_INTOSC2", displayName: "Internal Oscillator 2" },
	{ name: "SYSCTL_CLOCKOUT_XTALOSC", displayName: "External Oscillator" },
	{ name: "SYSCTL_CLOCKOUT_PUMPOSC", displayName: "PUMPOSC" },
	{ name: "SYSCTL_SYSPLLCLK_AUX", displayName: "Test Clk of the System APLL" },
	{ name: "SYSCTL_SYSPLLCLKOUT", displayName: "PLL System Clock pre SYSCLKDIV" },
]
let SysCtl_ExternalOscMode = [
	{ name: "SYSCTL_XTALMODE_CRYSTAL", displayName: "XTAL Oscillator Crystal Mode" },
	{ name: "SYSCTL_XTALMODE_SINGLE", displayName: "XTAL Oscillator Single-Ended Mode" },
]
let SysCtl_SyncOutputSource = [
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM1SYNCOUT", displayName: "EPWM1SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM2SYNCOUT", displayName: "EPWM2SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM3SYNCOUT", displayName: "EPWM3SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM4SYNCOUT", displayName: "EPWM4SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM5SYNCOUT", displayName: "EPWM5SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM6SYNCOUT", displayName: "EPWM6SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM7SYNCOUT", displayName: "EPWM7SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP1SYNCOUT", displayName: "ECAP1SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP2SYNCOUT", displayName: "ECAP2SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP3SYNCOUT", displayName: "ECAP3SYNCOUT --> EXTSYNCOUT" },
]
let SysCtl_DeviceParametric = [
	{ name: "SYSCTL_DEVICE_QUAL", displayName: "Device Qualification Status" },
	{ name: "SYSCTL_DEVICE_PINCOUNT", displayName: "Device Pin Count" },
	{ name: "SYSCTL_DEVICE_INSTASPIN", displayName: "Device InstaSPIN Feature Set" },
	{ name: "SYSCTL_DEVICE_FLASH", displayName: "Device Flash size (KB)" },
	{ name: "SYSCTL_DEVICE_FAMILY", displayName: "Device Family" },
	{ name: "SYSCTL_DEVICE_PARTNO", displayName: "Device Part Number" },
	{ name: "SYSCTL_DEVICE_CLASSID", displayName: "Device Class ID" },
]
let SysCtl_SelType = [
	{ name: "SYSCTL_ECAPTYPE", displayName: "Configure ECAP Type : - Type 0 : No EALLOW protection for ECAP registers - Type 1 : ECAP registers are EALLOW protected" },
]
let SysCtl_XClkDivider = [
	{ name: "SYSCTL_XCLKOUT_DIV_1", displayName: "XCLKOUT =  XCLKOUT / 1" },
	{ name: "SYSCTL_XCLKOUT_DIV_2", displayName: "XCLKOUT =  XCLKOUT / 2" },
	{ name: "SYSCTL_XCLKOUT_DIV_4", displayName: "XCLKOUT =  XCLKOUT / 4" },
	{ name: "SYSCTL_XCLKOUT_DIV_8", displayName: "XCLKOUT =  XCLKOUT / 8" },
]
let SysCtl_Cputimer2ClkDivider = [
	{ name: "SYSCTL_TMR2CLKPRESCALE_1", displayName: "Cputimer2 clock =  Cputimer2 clock / 1" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_2", displayName: "Cputimer2 clock =  Cputimer2 clock / 2" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_4", displayName: "Cputimer2 clock =  Cputimer2 clock / 4" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_8", displayName: "Cputimer2 clock =  Cputimer2 clock / 8" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_16", displayName: "Cputimer2 clock =  Cputimer2 clock / 16" },
]
let SysCtl_Cputimer2ClkSource = [
	{ name: "SYSCTL_TMR2CLKSRCSEL_SYSCLK", displayName: "System Clock" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_INTOSC1", displayName: "Internal Oscillator 1" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_INTOSC2", displayName: "Internal Oscillator 2" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_XTAL", displayName: "Crystal oscillator" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_AUXPLLCLK", displayName: "Aux PLL CLock" },
]
let SysCtl_ClkRegSel = [
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL1", displayName: "CLKSRCCTL1 lock" },
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL2", displayName: "CLKSRCCTL2 lock" },
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL3", displayName: "CLKSRCCTL3 lock" },
	{ name: "SYSCTL_REG_SEL_SYSPLLCTL1", displayName: "SYSPLLCTL1 lock" },
	{ name: "SYSCTL_REG_SEL_SYSPLLMULT", displayName: "SYSPLLMULT lock" },
	{ name: "SYSCTL_REG_SEL_SYSCLKDIVSEL", displayName: "SYSCLKDIVSEL lock" },
	{ name: "SYSCTL_REG_SEL_PERCLKDIVSEL", displayName: "PERCLKDIVSEL lock" },
	{ name: "SYSCTL_REG_SEL_CLBCLKCTL", displayName: "CLBCLKCTL lock" },
	{ name: "SYSCTL_REG_SEL_LOSPCP", displayName: "LOSPCP lock" },
	{ name: "SYSCTL_REG_SEL_XTALCR", displayName: "XTALCR lock" },
]
let SysCtl_CpuRegSel = [
	{ name: "SYSCTL_REG_SEL_PIEVERRADDR", displayName: "PIEVERRADDR lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR0", displayName: "PCLKCR0 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR2", displayName: "PCLKCR2 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR3", displayName: "PCLKCR3 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR4", displayName: "PCLKCR4 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR7", displayName: "PCLKCR7 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR8", displayName: "PCLKCR8 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR9", displayName: "PCLKCR9 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR10", displayName: "PCLKCR10 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR13", displayName: "PCLKCR13 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR14", displayName: "PCLKCR14 lock" },
	{ name: "SYSCTL_REG_SEL_LPMCR", displayName: "LPMCR lock" },
	{ name: "SYSCTL_REG_SEL_GPIOLPMSEL0", displayName: "GPIOLPMSEL0 lock" },
	{ name: "SYSCTL_REG_SEL_GPIOLPMSEL1", displayName: "GPIOLPMSEL1 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR17", displayName: "PCLKCR17 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR18", displayName: "PCLKCR18 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR19", displayName: "PCLKCR19 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR20", displayName: "PCLKCR20 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR21", displayName: "PCLKCR21 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR22", displayName: "PCLKCR22 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR24", displayName: "PCLKCR24 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR25", displayName: "PCLKCR25 lock" },
]
let SysCtl_CLBClkDivider = [
	{ name: "SYSCTL_CLBCLKOUT_DIV_1", displayName: "CLB clock =  CLB clock / 1" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_2", displayName: "CLB clock =  CLB clock / 2" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_3", displayName: "CLB clock =  CLB clock / 3" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_4", displayName: "CLB clock =  CLB clock / 4" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_5", displayName: "CLB clock =  CLB clock / 5" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_6", displayName: "CLB clock =  CLB clock / 6" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_7", displayName: "CLB clock =  CLB clock / 7" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_8", displayName: "CLB clock =  CLB clock / 8" },
]
let SysCtl_CLBTClkDivider = [
	{ name: "SYSCTL_CLBTCLKOUT_DIV_1", displayName: "CLBTCLKOUT =  CLB clock / 1" },
	{ name: "SYSCTL_CLBTCLKOUT_DIV_2", displayName: "CLBTCLKOUT =  CLB clock / 2" },
]
let SysCtl_CLBInst = [
	{ name: "SYSCTL_CLB1", displayName: "CLB 1 instance" },
	{ name: "SYSCTL_CLB2", displayName: "CLB 2 instance" },
]
let SysCtl_CLBClkm = [
	{ name: "SYSCTL_CLBCLK_SYNC", displayName: "CLB is synchronous to SYSCLK" },
	{ name: "SYSCTL_CLBCLK_ASYNC", displayName: "CLB runs of asynchronous clock" },
]
let SYSCTL_NMI = [
	{ name: "SYSCTL_NMI_NMIINT", displayName: "NMI Interrupt Flag" },
	{ name: "SYSCTL_NMI_CLOCKFAIL", displayName: "Clock Fail Interrupt Flag" },
	{ name: "SYSCTL_NMI_RAMUNCERR", displayName: "RAM Uncorrectable Error NMI Flag" },
	{ name: "SYSCTL_NMI_FLUNCERR", displayName: "Flash Uncorrectable Error NMI Flag" },
	{ name: "SYSCTL_NMI_CPU1HWBISTERR", displayName: "HW BIST Error NMI Flag" },
	{ name: "SYSCTL_NMI_SYSDBGNMI", displayName: "System Debug Module NMI Flag" },
	{ name: "SYSCTL_NMI_CLBNMI", displayName: "Reconfigurable Logic NMI Flag" },
	{ name: "SYSCTL_NMI_SWERR", displayName: "SW Error Force NMI Flag" },
	{ name: "SYSCTL_NMI_CRC_FAIL", displayName: "BGCRC calculation failed." },
]
let SYSCTL_CAUSE = [
	{ name: "SYSCTL_CAUSE_POR", displayName: "Power-on reset" },
	{ name: "SYSCTL_CAUSE_XRS", displayName: "External reset pin" },
	{ name: "SYSCTL_CAUSE_WDRS", displayName: "Watchdog reset" },
	{ name: "SYSCTL_CAUSE_NMIWDRS", displayName: "NMI watchdog reset" },
	{ name: "SYSCTL_CAUSE_SCCRESET", displayName: "SCCRESETn by DCSM" },
	{ name: "SYSCTL_CAUSE_HWBISTN", displayName: "HWBISTn Reset" },
	{ name: "SYSCTL_CAUSE_SIMRESET_CPU1RSN", displayName: "SIMRESET_CPU1RSn" },
	{ name: "SYSCTL_CAUSE_SIMRESET_XRSN", displayName: "SIMRESET_XRSn" },
]
let SYSCTL_ADCSOC_SRC = [
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCA", displayName: "ePWM1 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM2SOCA", displayName: "ePWM2 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCA", displayName: "ePWM3 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM4SOCA", displayName: "ePWM4 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM5SOCA", displayName: "ePWM5 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM6SOCA", displayName: "ePWM6 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM7SOCA", displayName: "ePWM7 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCB", displayName: "ePWM1 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM2SOCB", displayName: "ePWM2 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCB", displayName: "ePWM3 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM4SOCB", displayName: "ePWM4 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM5SOCB", displayName: "ePWM5 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM6SOCB", displayName: "ePWM6 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM7SOCB", displayName: "ePWM7 SOCB for ADCSOCBO" },
]
module.exports = {
	SysCtl_PeripheralPCLOCKCR: SysCtl_PeripheralPCLOCKCR,
	SysCtl_PeripheralSOFTPRES: SysCtl_PeripheralSOFTPRES,
	SysCtl_WDPredivider: SysCtl_WDPredivider,
	SysCtl_WDPrescaler: SysCtl_WDPrescaler,
	SysCtl_WDMode: SysCtl_WDMode,
	SysCtl_LSPCLKPrescaler: SysCtl_LSPCLKPrescaler,
	SysCtl_AccessPeripheral: SysCtl_AccessPeripheral,
	SysCtl_AccessController: SysCtl_AccessController,
	SysCtl_AccessPermission: SysCtl_AccessPermission,
	SysCtl_ClockOut: SysCtl_ClockOut,
	SysCtl_ExternalOscMode: SysCtl_ExternalOscMode,
	SysCtl_SyncOutputSource: SysCtl_SyncOutputSource,
	SysCtl_DeviceParametric: SysCtl_DeviceParametric,
	SysCtl_SelType: SysCtl_SelType,
	SysCtl_XClkDivider: SysCtl_XClkDivider,
	SysCtl_Cputimer2ClkDivider: SysCtl_Cputimer2ClkDivider,
	SysCtl_Cputimer2ClkSource: SysCtl_Cputimer2ClkSource,
	SysCtl_ClkRegSel: SysCtl_ClkRegSel,
	SysCtl_CpuRegSel: SysCtl_CpuRegSel,
	SysCtl_CLBClkDivider: SysCtl_CLBClkDivider,
	SysCtl_CLBTClkDivider: SysCtl_CLBTClkDivider,
	SysCtl_CLBInst: SysCtl_CLBInst,
	SysCtl_CLBClkm: SysCtl_CLBClkm,
	SYSCTL_NMI: SYSCTL_NMI,
	SYSCTL_CAUSE: SYSCTL_CAUSE,
	SYSCTL_ADCSOC_SRC: SYSCTL_ADCSOC_SRC,
}
