let ERAD_Owner = [
	{ name: "ERAD_OWNER_NOOWNER", displayName: "No owner" },
	{ name: "ERAD_OWNER_APPLICATION", displayName: "Application owned" },
	{ name: "ERAD_OWNER_DEBUGGER", displayName: "Debugger owned" },
]
let ERAD_Status = [
	{ name: "ERAD_STATE_IDLE", displayName: "Module is idle" },
	{ name: "ERAD_STATE_ENABLED", displayName: "Module is enabled" },
	{ name: "ERAD_STATE_COMPLETED", displayName: "Module was enabled and an event occurred" },
]
let ERAD_BusComp_Bus_Select = [
	{ name: "ERAD_BUSCOMP_BUS_PAB", displayName: "Use the Program Address Bus" },
	{ name: "ERAD_BUSCOMP_BUS_VPC", displayName: "Use the Virtual Program Counter" },
	{ name: "ERAD_BUSCOMP_BUS_DWAB", displayName: "Use the Data Write Address Bus" },
	{ name: "ERAD_BUSCOMP_BUS_DRAB", displayName: "Use the Data Read Address Bus" },
	{ name: "ERAD_BUSCOMP_BUS_DWDB", displayName: "Use the Data Write Data Bus" },
	{ name: "ERAD_BUSCOMP_BUS_DRDB", displayName: "Use the Data Read Data Bus" },
	{ name: "ERAD_BUSCOMP_BUS_VPC_I_ALIGNED", displayName: "Use VPC Instruction aligned match" },
	{ name: "ERAD_BUSCOMP_BUS_VPC_R1_ALIGNED", displayName: "Use VPC R1 aligned match" },
	{ name: "ERAD_BUSCOMP_BUS_VPC_R2_ALIGNED", displayName: "Use VPC R2 aligned match" },
	{ name: "ERAD_BUSCOMP_BUS_VPC_W_ALIGNED", displayName: "Use VPC Word aligned match" },
]
let ERAD_BusComp_Comp_Mode = [
	{ name: "ERAD_BUSCOMP_COMPMODE_GT", displayName: "Check for greater than" },
	{ name: "ERAD_BUSCOMP_COMPMODE_GE", displayName: "Check for greater than equal to" },
	{ name: "ERAD_BUSCOMP_COMPMODE_LT", displayName: "Check for lesser than" },
	{ name: "ERAD_BUSCOMP_COMPMODE_LE", displayName: "Check for lesser than equal to" },
	{ name: "ERAD_BUSCOMP_COMPMODE_EQ", displayName: "Check for only equality" },
]
let ERAD_Counter_Event_Mode = [
	{ name: "ERAD_COUNTER_MODE_ACTIVE", displayName: "Count number of CPU" },
	{ name: "ERAD_COUNTER_MODE_RISING_EDGE", displayName: "Count number of Rising" },
]
let ERAD_Counter_Input_Event = [
	{ name: "ERAD_EVENT_HWBP1", displayName: "EVENT HWBP1" },
	{ name: "ERAD_EVENT_HWBP2", displayName: "EVENT HWBP2" },
	{ name: "ERAD_EVENT_HWBP3", displayName: "EVENT HWBP3" },
	{ name: "ERAD_EVENT_HWBP4", displayName: "EVENT HWBP4" },
	{ name: "ERAD_EVENT_HWBP5", displayName: "EVENT HWBP5" },
	{ name: "ERAD_EVENT_HWBP6", displayName: "EVENT HWBP6" },
	{ name: "ERAD_EVENT_HWBP7", displayName: "EVENT HWBP7" },
	{ name: "ERAD_EVENT_HWBP8", displayName: "EVENT HWBP8" },
	{ name: "ERAD_EVENT_COUNTER1_EVENT", displayName: "EVENT COUNTER1 EVENT" },
	{ name: "ERAD_EVENT_COUNTER2_EVENT", displayName: "EVENT COUNTER2 EVENT" },
	{ name: "ERAD_EVENT_COUNTER3_EVENT", displayName: "EVENT COUNTER3 EVENT" },
	{ name: "ERAD_EVENT_COUNTER4_EVENT", displayName: "EVENT COUNTER4 EVENT" },
	{ name: "ERAD_EVENT_ERAD_OR_MASK0", displayName: "EVENT ERAD OR MASK0" },
	{ name: "ERAD_EVENT_ERAD_OR_MASK1", displayName: "EVENT ERAD OR MASK1" },
	{ name: "ERAD_EVENT_ERAD_OR_MASK2", displayName: "EVENT ERAD OR MASK2" },
	{ name: "ERAD_EVENT_ERAD_OR_MASK3", displayName: "EVENT ERAD OR MASK3" },
	{ name: "ERAD_EVENT_ERAD_AND_MASK0", displayName: "EVENT ERAD AND MASK0" },
	{ name: "ERAD_EVENT_ERAD_AND_MASK1", displayName: "EVENT ERAD AND MASK1" },
	{ name: "ERAD_EVENT_ERAD_AND_MASK2", displayName: "EVENT ERAD AND MASK2" },
	{ name: "ERAD_EVENT_ERAD_AND_MASK3", displayName: "EVENT ERAD AND MASK3" },
	{ name: "ERAD_EVENT_PIE_INT1", displayName: "EVENT PIE INT1" },
	{ name: "ERAD_EVENT_PIE_INT2", displayName: "EVENT PIE INT2" },
	{ name: "ERAD_EVENT_PIE_INT3", displayName: "EVENT PIE INT3" },
	{ name: "ERAD_EVENT_PIE_INT4", displayName: "EVENT PIE INT4" },
	{ name: "ERAD_EVENT_PIE_INT5", displayName: "EVENT PIE INT5" },
	{ name: "ERAD_EVENT_PIE_INT6", displayName: "EVENT PIE INT6" },
	{ name: "ERAD_EVENT_PIE_INT7", displayName: "EVENT PIE INT7" },
	{ name: "ERAD_EVENT_PIE_INT8", displayName: "EVENT PIE INT8" },
	{ name: "ERAD_EVENT_PIE_INT9", displayName: "EVENT PIE INT9" },
	{ name: "ERAD_EVENT_PIE_INT10", displayName: "EVENT PIE INT10" },
	{ name: "ERAD_EVENT_PIE_INT11", displayName: "EVENT PIE INT11" },
	{ name: "ERAD_EVENT_PIE_INT12", displayName: "EVENT PIE INT12" },
	{ name: "ERAD_EVENT_TIMER0_TINT0", displayName: "EVENT TIMER0 TINT0" },
	{ name: "ERAD_EVENT_TIMER1_TINT1", displayName: "EVENT TIMER1 TINT1" },
	{ name: "ERAD_EVENT_TIMER2_TINT2", displayName: "EVENT TIMER2 TINT2" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT1", displayName: "EVENT CLA INTERRUPT1" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT2", displayName: "EVENT CLA INTERRUPT2" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT3", displayName: "EVENT CLA INTERRUPT3" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT4", displayName: "EVENT CLA INTERRUPT4" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT5", displayName: "EVENT CLA INTERRUPT5" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT6", displayName: "EVENT CLA INTERRUPT6" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT7", displayName: "EVENT CLA INTERRUPT7" },
	{ name: "ERAD_EVENT_CLA_INTERRUPT8", displayName: "EVENT CLA INTERRUPT8" },
	{ name: "ERAD_EVENT_ECAT_PDI_SOF", displayName: "EVENT ECAT PDI SOF" },
	{ name: "ERAD_EVENT_ECAT_PDI_EOF", displayName: "EVENT ECAT PDI EOF" },
	{ name: "ERAD_EVENT_ECAT_PCI_WD_TRIGGER", displayName: "EVENT ECAT PCI WD TRIGGER" },
	{ name: "ERAD_EVENT_ECAT_PDI_UC_IRQ", displayName: "EVENT ECAT PDI UC IRQ" },
	{ name: "ERAD_EVENT_ECAT_SYNC_OUT0", displayName: "EVENT ECAT SYNC OUT0" },
	{ name: "ERAD_EVENT_ECAT_SYNC_OUT1", displayName: "EVENT ECAT SYNC OUT1" },
	{ name: "ERAD_EVENT_ECAT_DRAM_PARITY_ERROR", displayName: "EVENT ECAT DRAM PARITY ERROR" },
	{ name: "ERAD_EVENT_MCANA_EVT0", displayName: "EVENT MCANA EVT0" },
	{ name: "ERAD_EVENT_MCANA_EVT1", displayName: "EVENT MCANA EVT1" },
	{ name: "ERAD_EVENT_MCANA_EVT2", displayName: "EVENT MCANA EVT2" },
	{ name: "ERAD_EVENT_ADCSOCA", displayName: "EVENT ADCSOCA" },
	{ name: "ERAD_EVENT_ADCSOCB", displayName: "EVENT ADCSOCB" },
	{ name: "ERAD_EVENT_CLATASKRUN1", displayName: "EVENT CLATASKRUN1" },
	{ name: "ERAD_EVENT_CLATASKRUN2", displayName: "EVENT CLATASKRUN2" },
	{ name: "ERAD_EVENT_CLATASKRUN3", displayName: "EVENT CLATASKRUN3" },
	{ name: "ERAD_EVENT_CLATASKRUN4", displayName: "EVENT CLATASKRUN4" },
	{ name: "ERAD_EVENT_CLATASKRUN5", displayName: "EVENT CLATASKRUN5" },
	{ name: "ERAD_EVENT_CLATASKRUN6", displayName: "EVENT CLATASKRUN6" },
	{ name: "ERAD_EVENT_CLATASKRUN7", displayName: "EVENT CLATASKRUN7" },
	{ name: "ERAD_EVENT_CLATASKRUN8", displayName: "EVENT CLATASKRUN8" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT1", displayName: "EVENT EPWMXBAR OUT1" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT2", displayName: "EVENT EPWMXBAR OUT2" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT3", displayName: "EVENT EPWMXBAR OUT3" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT4", displayName: "EVENT EPWMXBAR OUT4" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT5", displayName: "EVENT EPWMXBAR OUT5" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT6", displayName: "EVENT EPWMXBAR OUT6" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT7", displayName: "EVENT EPWMXBAR OUT7" },
	{ name: "ERAD_EVENT_EPWMXBAR_OUT8", displayName: "EVENT EPWMXBAR OUT8" },
	{ name: "ERAD_EVENT_INPUTXBAR0", displayName: "EVENT INPUTXBAR0" },
	{ name: "ERAD_EVENT_INPUTXBAR1", displayName: "EVENT INPUTXBAR1" },
	{ name: "ERAD_EVENT_INPUTXBAR2", displayName: "EVENT INPUTXBAR2" },
	{ name: "ERAD_EVENT_INPUTXBAR3", displayName: "EVENT INPUTXBAR3" },
	{ name: "ERAD_EVENT_INPUTXBAR4", displayName: "EVENT INPUTXBAR4" },
	{ name: "ERAD_EVENT_INPUTXBAR5", displayName: "EVENT INPUTXBAR5" },
	{ name: "ERAD_EVENT_INPUTXBAR6", displayName: "EVENT INPUTXBAR6" },
	{ name: "ERAD_EVENT_INPUTXBAR7", displayName: "EVENT INPUTXBAR7" },
	{ name: "ERAD_EVENT_INPUTXBAR8", displayName: "EVENT INPUTXBAR8" },
	{ name: "ERAD_EVENT_INPUTXBAR9", displayName: "EVENT INPUTXBAR9" },
	{ name: "ERAD_EVENT_INPUTXBAR10", displayName: "EVENT INPUTXBAR10" },
	{ name: "ERAD_EVENT_INPUTXBAR11", displayName: "EVENT INPUTXBAR11" },
	{ name: "ERAD_EVENT_INPUTXBAR12", displayName: "EVENT INPUTXBAR12" },
	{ name: "ERAD_EVENT_INPUTXBAR13", displayName: "EVENT INPUTXBAR13" },
	{ name: "ERAD_EVENT_INPUTXBAR14", displayName: "EVENT INPUTXBAR14" },
	{ name: "ERAD_EVENT_INPUTXBAR15", displayName: "EVENT INPUTXBAR15" },
	{ name: "ERAD_EVENT_CPUx_CPUSTAT", displayName: "EVENT CPUX CPUSTAT" },
	{ name: "ERAD_EVENT_CPUx_DBGACK", displayName: "EVENT CPUX DBGACK" },
	{ name: "ERAD_EVENT_CPUx_NMI", displayName: "EVENT CPUX NMI" },
	{ name: "ERAD_EVENT_CMPSS1_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS1 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS2_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS2 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS3_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS3 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS4_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS4 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS5_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS5 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS6_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS6 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS7_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS7 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_CMPSS8_CTRIPH_OR_CTRIPL", displayName: "EVENT CMPSS8 CTRIPH OR CTRIPL" },
	{ name: "ERAD_EVENT_SD1FLT1_COMPH_OR_COMPL", displayName: "EVENT SD1FLT1 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD1FLT2_COMPH_OR_COMPL", displayName: "EVENT SD1FLT2 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD1FLT3_COMPH_OR_COMPL", displayName: "EVENT SD1FLT3 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD1FLT4_COMPH_OR_COMPL", displayName: "EVENT SD1FLT4 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD2FLT1_COMPH_OR_COMPL", displayName: "EVENT SD2FLT1 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD2FLT2_COMPH_OR_COMPL", displayName: "EVENT SD2FLT2 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD2FLT3_COMPH_OR_COMPL", displayName: "EVENT SD2FLT3 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_SD2FLT4_COMPH_OR_COMPL", displayName: "EVENT SD2FLT4 COMPH OR COMPL" },
	{ name: "ERAD_EVENT_ADCAINT1", displayName: "EVENT ADCAINT1" },
	{ name: "ERAD_EVENT_ADCAINT2", displayName: "EVENT ADCAINT2" },
	{ name: "ERAD_EVENT_ADCAINT3", displayName: "EVENT ADCAINT3" },
	{ name: "ERAD_EVENT_ADCAINT4", displayName: "EVENT ADCAINT4" },
	{ name: "ERAD_EVENT_ADCBINT1", displayName: "EVENT ADCBINT1" },
	{ name: "ERAD_EVENT_ADCBINT2", displayName: "EVENT ADCBINT2" },
	{ name: "ERAD_EVENT_ADCBINT3", displayName: "EVENT ADCBINT3" },
	{ name: "ERAD_EVENT_ADCBINT4", displayName: "EVENT ADCBINT4" },
	{ name: "ERAD_EVENT_ADCCINT1", displayName: "EVENT ADCCINT1" },
	{ name: "ERAD_EVENT_ADCCINT2", displayName: "EVENT ADCCINT2" },
	{ name: "ERAD_EVENT_ADCCINT3", displayName: "EVENT ADCCINT3" },
	{ name: "ERAD_EVENT_ADCCINT4", displayName: "EVENT ADCCINT4" },
	{ name: "ERAD_EVENT_ADCDINT1", displayName: "EVENT ADCDINT1" },
	{ name: "ERAD_EVENT_ADCDINT2", displayName: "EVENT ADCDINT2" },
	{ name: "ERAD_EVENT_ADCDINT3", displayName: "EVENT ADCDINT3" },
	{ name: "ERAD_EVENT_ADCDINT4", displayName: "EVENT ADCDINT4" },
	{ name: "ERAD_EVENT_NO_EVENT", displayName: "EVENT NO EVENT" },
]
let ERAD_Mask = [
	{ name: "ERAD_AND_MASK1", displayName: "AND MASK1" },
	{ name: "ERAD_AND_MASK2", displayName: "AND MASK2" },
	{ name: "ERAD_AND_MASK3", displayName: "AND MASK3" },
	{ name: "ERAD_AND_MASK4", displayName: "AND MASK4" },
	{ name: "ERAD_OR_MASK1", displayName: "OR MASK1" },
	{ name: "ERAD_OR_MASK2", displayName: "OR MASK2" },
	{ name: "ERAD_OR_MASK3", displayName: "OR MASK3" },
	{ name: "ERAD_OR_MASK4", displayName: "OR MASK4" },
]
let ERAD_CRC_Qualifiers = [
	{ name: "ERAD_CRC_QUAL_NONE", displayName: "Use every valid event as qualifier" },
	{ name: "ERAD_CRC_QUAL_HWBP1", displayName: "CRC Compute Qualified by HWBP_EVENT1" },
	{ name: "ERAD_CRC_QUAL_HWBP2", displayName: "CRC Compute Qualified by HWBP_EVENT2" },
	{ name: "ERAD_CRC_QUAL_HWBP3", displayName: "CRC Compute Qualified by HWBP_EVENT3" },
	{ name: "ERAD_CRC_QUAL_HWBP4", displayName: "CRC Compute Qualified by HWBP_EVENT4" },
	{ name: "ERAD_CRC_QUAL_HWBP5", displayName: "CRC Compute Qualified by HWBP_EVENT5" },
	{ name: "ERAD_CRC_QUAL_HWBP6", displayName: "CRC Compute Qualified by HWBP_EVENT6" },
	{ name: "ERAD_CRC_QUAL_HWBP7", displayName: "CRC Compute Qualified by HWBP_EVENT7" },
	{ name: "ERAD_CRC_QUAL_HWBP8", displayName: "CRC Compute Qualified by HWBP_EVENT8" },
	{ name: "ERAD_CRC_QUAL_HWBP_OR1", displayName: "CRC Compute Qualified by HWBP_EVENT_OR1" },
	{ name: "ERAD_CRC_QUAL_HWBP_OR2", displayName: "CRC Compute Qualified by HWBP_EVENT_OR1" },
	{ name: "ERAD_CRC_QUAL_HWBP_OR3", displayName: "CRC Compute Qualified by HWBP_EVENT_OR1" },
	{ name: "ERAD_CRC_QUAL_HWBP_OR4", displayName: "CRC Compute Qualified by HWBP_EVENT_OR1" },
	{ name: "ERAD_CRC_QUAL_HWBP_AND1", displayName: "CRC Compute Qualified by HWBP_EVENT_AND2" },
	{ name: "ERAD_CRC_QUAL_HWBP_AND2", displayName: "CRC Compute Qualified by HWBP_EVENT_AND2" },
	{ name: "ERAD_CRC_QUAL_HWBP_AND3", displayName: "CRC Compute Qualified by HWBP_EVENT_AND2" },
	{ name: "ERAD_CRC_QUAL_HWBP_AND4", displayName: "CRC Compute Qualified by HWBP_EVENT_AND2" },
]
let ERAD_Counter_Input_Type = [
	{ name: "ERAD_COUNTER_COUNT_INPUT", displayName: "COUNTER COUNT INPUT" },
	{ name: "ERAD_COUNTER_START_INPUT", displayName: "COUNTER START INPUT" },
	{ name: "ERAD_COUNTER_STOP_INPUT", displayName: "COUNTER STOP INPUT" },
	{ name: "ERAD_COUNTER_RESET_INPUT", displayName: "COUNTER RESET INPUT" },
]
let ERAD_INST = [
	{ name: "ERAD_INST_BUSCOMP1", displayName: "Instance for bus comparator 1" },
	{ name: "ERAD_INST_BUSCOMP2", displayName: "Instance for bus comparator 2" },
	{ name: "ERAD_INST_BUSCOMP3", displayName: "Instance for bus comparator 3" },
	{ name: "ERAD_INST_BUSCOMP4", displayName: "Instance for bus comparator 4" },
	{ name: "ERAD_INST_BUSCOMP5", displayName: "Instance for bus comparator 5" },
	{ name: "ERAD_INST_BUSCOMP6", displayName: "Instance for bus comparator 6" },
	{ name: "ERAD_INST_BUSCOMP7", displayName: "Instance for bus comparator 7" },
	{ name: "ERAD_INST_BUSCOMP8", displayName: "Instance for bus comparator 8" },
	{ name: "ERAD_INST_COUNTER1", displayName: "Instance for counter 1" },
	{ name: "ERAD_INST_COUNTER2", displayName: "Instance for counter 2" },
	{ name: "ERAD_INST_COUNTER3", displayName: "Instance for counter 3" },
	{ name: "ERAD_INST_COUNTER4", displayName: "Instance for counter 4" },
	{ name: "ERAD_INST_CRC1", displayName: "Instance for CRC unit 1" },
	{ name: "ERAD_INST_CRC2", displayName: "Instance for CRC unit 2" },
	{ name: "ERAD_INST_CRC3", displayName: "Instance for CRC unit 3" },
	{ name: "ERAD_INST_CRC4", displayName: "Instance for CRC unit 4" },
	{ name: "ERAD_INST_CRC5", displayName: "Instance for CRC unit 5" },
	{ name: "ERAD_INST_CRC6", displayName: "Instance for CRC unit 6" },
	{ name: "ERAD_INST_CRC7", displayName: "Instance for CRC unit 7" },
	{ name: "ERAD_INST_CRC8", displayName: "Instance for CRC unit 8" },
]
let ERAD_INPUT = [
	{ name: "ERAD_INPUT_INVERT_DISABLE", displayName: "Do not invert the input" },
	{ name: "ERAD_INPUT_INVERT_ENABLE", displayName: "Invert the input" },
	{ name: "ERAD_INPUT_SYNC_DISABLE", displayName: "Disable 2-stage synchronizer" },
	{ name: "ERAD_INPUT_SYNC_ENABLE", displayName: "Enable 2-stage synchronizer" },
]
module.exports = {
	ERAD_Owner: ERAD_Owner,
	ERAD_Status: ERAD_Status,
	ERAD_BusComp_Bus_Select: ERAD_BusComp_Bus_Select,
	ERAD_BusComp_Comp_Mode: ERAD_BusComp_Comp_Mode,
	ERAD_Counter_Event_Mode: ERAD_Counter_Event_Mode,
	ERAD_Counter_Input_Event: ERAD_Counter_Input_Event,
	ERAD_Mask: ERAD_Mask,
	ERAD_CRC_Qualifiers: ERAD_CRC_Qualifiers,
	ERAD_Counter_Input_Type: ERAD_Counter_Input_Type,
	ERAD_INST: ERAD_INST,
	ERAD_INPUT: ERAD_INPUT,
}
