let interrupts = [
	{ int_define_name: "INT_TIMER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 1 Interrupt" },
	{ int_define_name: "INT_TIMER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 2 Interrupt" },
	{ int_define_name: "INT_DATALOG", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Datalogging Interrupt" },
	{ int_define_name: "INT_RTOS", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "RTOS Interrupt from ERAD" },
	{ int_define_name: "INT_EMU", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Emulation Interrupt" },
	{ int_define_name: "INT_NMI", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Non-Maskable Interrupt" },
	{ int_define_name: "INT_ILLEGAL", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Illegal Operation Trap" },
	{ int_define_name: "INT_USER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 1" },
	{ int_define_name: "INT_USER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 2" },
	{ int_define_name: "INT_USER3", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 3" },
	{ int_define_name: "INT_USER4", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 4" },
	{ int_define_name: "INT_USER5", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 5" },
	{ int_define_name: "INT_USER6", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 6" },
	{ int_define_name: "INT_USER7", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 7" },
	{ int_define_name: "INT_USER8", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 8" },
	{ int_define_name: "INT_USER9", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 9" },
	{ int_define_name: "INT_USER10", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 10" },
	{ int_define_name: "INT_USER11", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 11" },
	{ int_define_name: "INT_USER12", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 12" },
	{ int_define_name: "INT_ADCA1", int_group_channel_number: "1.1", int_group_number: "1", int_channel_number: "1", int_description: "ADCA Interrupt 1" },
	{ int_define_name: "INT_XINT1", int_group_channel_number: "1.3", int_group_number: "1", int_channel_number: "3", int_description: "XINT1 Interrupt" },
	{ int_define_name: "INT_XINT2", int_group_channel_number: "1.4", int_group_number: "1", int_channel_number: "4", int_description: "XINT2 Interrupt" },
	{ int_define_name: "INT_SYS_ERR", int_group_channel_number: "2.1", int_group_number: "2", int_channel_number: "1", int_description: "SYS_ERR Interrupt" },
	{ int_define_name: "INT_TIMER0", int_group_channel_number: "2.2", int_group_number: "2", int_channel_number: "2", int_description: "Timer 0 Interrupt" },
	{ int_define_name: "INT_WAKE", int_group_channel_number: "2.3", int_group_number: "2", int_channel_number: "3", int_description: "Standby and Halt Wakeup Interrupt" },
	{ int_define_name: "INT_MCPWM1", int_group_channel_number: "2.4", int_group_number: "2", int_channel_number: "4", int_description: "MCPWM1 Interrupt" },
	{ int_define_name: "INT_MCPWM3", int_group_channel_number: "3.2", int_group_number: "3", int_channel_number: "2", int_description: "MCPWM3 Interrupt" },
	{ int_define_name: "INT_ECAP1", int_group_channel_number: "4.3", int_group_number: "4", int_channel_number: "3", int_description: "eCAP1 Interrupt" },
	{ int_define_name: "INT_EQEP1", int_group_channel_number: "5.1", int_group_number: "5", int_channel_number: "1", int_description: "eQEP1 Interrupt" },
	{ int_define_name: "INT_SPIA_RX", int_group_channel_number: "5.2", int_group_number: "5", int_channel_number: "2", int_description: "SPIA Receive Interrupt" },
	{ int_define_name: "INT_SPIA_TX", int_group_channel_number: "5.3", int_group_number: "5", int_channel_number: "3", int_description: "SPIA Transmit Interrupt" },
	{ int_define_name: "INT_DCC0", int_group_channel_number: "6.2", int_group_number: "6", int_channel_number: "2", int_description: "DCC0 Interrupt" },
	{ int_define_name: "INT_DMA_CH1", int_group_channel_number: "6.3", int_group_number: "6", int_channel_number: "3", int_description: "DMA Channel 1 Interrupt" },
	{ int_define_name: "INT_DMA_CH2", int_group_channel_number: "6.4", int_group_number: "6", int_channel_number: "4", int_description: "DMA Channel 2 Interrupt" },
	{ int_define_name: "INT_I2CA", int_group_channel_number: "7.2", int_group_number: "7", int_channel_number: "2", int_description: "I2CA Interrupt 1" },
	{ int_define_name: "INT_I2CA_FIFO", int_group_channel_number: "7.3", int_group_number: "7", int_channel_number: "3", int_description: "I2CA Interrupt 2" },
	{ int_define_name: "INT_SCIA_RX", int_group_channel_number: "7.4", int_group_number: "7", int_channel_number: "4", int_description: "SCIA Receive Interrupt" },
	{ int_define_name: "INT_SCIA_TX", int_group_channel_number: "8.1", int_group_number: "8", int_channel_number: "1", int_description: "SCIA Transmit Interrupt" },
	{ int_define_name: "INT_SCIB_RX", int_group_channel_number: "8.2", int_group_number: "8", int_channel_number: "2", int_description: "SCIB Receive Interrupt" },
	{ int_define_name: "INT_SCIB_TX", int_group_channel_number: "8.3", int_group_number: "8", int_channel_number: "3", int_description: "SCIB Transmit Interrupt" },
	{ int_define_name: "INT_UARTA", int_group_channel_number: "9.2", int_group_number: "9", int_channel_number: "2", int_description: "UARTA Interrupt" },
	{ int_define_name: "INT_ADCA_EVT", int_group_channel_number: "9.3", int_group_number: "9", int_channel_number: "3", int_description: "ADCA Event Interrupt" },
	{ int_define_name: "INT_ADCA2", int_group_channel_number: "9.4", int_group_number: "9", int_channel_number: "4", int_description: "ADCA Interrupt 2" },
	{ int_define_name: "INT_XINT3", int_group_channel_number: "10.3", int_group_number: "10", int_channel_number: "3", int_description: "XINT3 Interrupt" },
	{ int_define_name: "INT_XINT4", int_group_channel_number: "10.4", int_group_number: "10", int_channel_number: "4", int_description: "XINT4 Interrupt" },
	{ int_define_name: "INT_XINT5", int_group_channel_number: "11.1", int_group_number: "11", int_channel_number: "1", int_description: "XINT5 Interrupt" },
	{ int_define_name: "INT_FLSS", int_group_channel_number: "11.2", int_group_number: "11", int_channel_number: "2", int_description: "Interrupt from flash sub-system" },
	{ int_define_name: "INT_FREERTOS", int_group_channel_number: "11.3", int_group_number: "11", int_channel_number: "3", int_description: "FreeRTOS SW interrupt" },
];
module.exports = {
	interrupts: interrupts,
}
