let Sysctl_PLLConfig = [
	{ name: "SYSCTL_PLL_ENABLE", displayName: "PLL ENABLE" },
	{ name: "SYSCTL_PLL_DISABLE", displayName: "PLL DISABLE" },
	{ name: "SYSCTL_PLL_BYPASS", displayName: "PLL BYPASS" },
]
let Sysctl_PLLPDiv = [
	{ name: "SYSCTL_PDIV_1", displayName: "PDIV 1" },
	{ name: "SYSCTL_PDIV_2", displayName: "PDIV 2" },
	{ name: "SYSCTL_PDIV_4", displayName: "PDIV 4" },
	{ name: "SYSCTL_PDIV_8", displayName: "PDIV 8" },
]
let Sysctl_PLLMult = [
	{ name: "SYSCTL_PLLMULT_2", displayName: "PLLMULT 2" },
	{ name: "SYSCTL_PLLMULT_3", displayName: "PLLMULT 3" },
	{ name: "SYSCTL_PLLMULT_4", displayName: "PLLMULT 4" },
	{ name: "SYSCTL_PLLMULT_5", displayName: "PLLMULT 5" },
	{ name: "SYSCTL_PLLMULT_6", displayName: "PLLMULT 6" },
	{ name: "SYSCTL_PLLMULT_7", displayName: "PLLMULT 7" },
	{ name: "SYSCTL_PLLMULT_8", displayName: "PLLMULT 8" },
	{ name: "SYSCTL_PLLMULT_9", displayName: "PLLMULT 9" },
	{ name: "SYSCTL_PLLMULT_10", displayName: "PLLMULT 10" },
	{ name: "SYSCTL_PLLMULT_11", displayName: "PLLMULT 11" },
	{ name: "SYSCTL_PLLMULT_12", displayName: "PLLMULT 12" },
	{ name: "SYSCTL_PLLMULT_13", displayName: "PLLMULT 13" },
	{ name: "SYSCTL_PLLMULT_14", displayName: "PLLMULT 14" },
	{ name: "SYSCTL_PLLMULT_15", displayName: "PLLMULT 15" },
	{ name: "SYSCTL_PLLMULT_16", displayName: "PLLMULT 16" },
	{ name: "SYSCTL_PLLMULT_17", displayName: "PLLMULT 17" },
	{ name: "SYSCTL_PLLMULT_18", displayName: "PLLMULT 18" },
	{ name: "SYSCTL_PLLMULT_19", displayName: "PLLMULT 19" },
	{ name: "SYSCTL_PLLMULT_20", displayName: "PLLMULT 20" },
	{ name: "SYSCTL_PLLMULT_21", displayName: "PLLMULT 21" },
	{ name: "SYSCTL_PLLMULT_22", displayName: "PLLMULT 22" },
	{ name: "SYSCTL_PLLMULT_23", displayName: "PLLMULT 23" },
	{ name: "SYSCTL_PLLMULT_24", displayName: "PLLMULT 24" },
	{ name: "SYSCTL_PLLMULT_25", displayName: "PLLMULT 25" },
	{ name: "SYSCTL_PLLMULT_26", displayName: "PLLMULT 26" },
	{ name: "SYSCTL_PLLMULT_27", displayName: "PLLMULT 27" },
	{ name: "SYSCTL_PLLMULT_28", displayName: "PLLMULT 28" },
	{ name: "SYSCTL_PLLMULT_29", displayName: "PLLMULT 29" },
	{ name: "SYSCTL_PLLMULT_30", displayName: "PLLMULT 30" },
	{ name: "SYSCTL_PLLMULT_31", displayName: "PLLMULT 31" },
	{ name: "SYSCTL_PLLMULT_32", displayName: "PLLMULT 32" },
	{ name: "SYSCTL_PLLMULT_33", displayName: "PLLMULT 33" },
	{ name: "SYSCTL_PLLMULT_34", displayName: "PLLMULT 34" },
	{ name: "SYSCTL_PLLMULT_35", displayName: "PLLMULT 35" },
	{ name: "SYSCTL_PLLMULT_36", displayName: "PLLMULT 36" },
	{ name: "SYSCTL_PLLMULT_37", displayName: "PLLMULT 37" },
	{ name: "SYSCTL_PLLMULT_38", displayName: "PLLMULT 38" },
	{ name: "SYSCTL_PLLMULT_39", displayName: "PLLMULT 39" },
	{ name: "SYSCTL_PLLMULT_40", displayName: "PLLMULT 40" },
	{ name: "SYSCTL_PLLMULT_41", displayName: "PLLMULT 41" },
	{ name: "SYSCTL_PLLMULT_42", displayName: "PLLMULT 42" },
	{ name: "SYSCTL_PLLMULT_43", displayName: "PLLMULT 43" },
	{ name: "SYSCTL_PLLMULT_44", displayName: "PLLMULT 44" },
	{ name: "SYSCTL_PLLMULT_45", displayName: "PLLMULT 45" },
	{ name: "SYSCTL_PLLMULT_46", displayName: "PLLMULT 46" },
	{ name: "SYSCTL_PLLMULT_47", displayName: "PLLMULT 47" },
	{ name: "SYSCTL_PLLMULT_48", displayName: "PLLMULT 48" },
	{ name: "SYSCTL_PLLMULT_49", displayName: "PLLMULT 49" },
	{ name: "SYSCTL_PLLMULT_50", displayName: "PLLMULT 50" },
	{ name: "SYSCTL_PLLMULT_51", displayName: "PLLMULT 51" },
	{ name: "SYSCTL_PLLMULT_52", displayName: "PLLMULT 52" },
	{ name: "SYSCTL_PLLMULT_53", displayName: "PLLMULT 53" },
	{ name: "SYSCTL_PLLMULT_54", displayName: "PLLMULT 54" },
	{ name: "SYSCTL_PLLMULT_55", displayName: "PLLMULT 55" },
	{ name: "SYSCTL_PLLMULT_56", displayName: "PLLMULT 56" },
	{ name: "SYSCTL_PLLMULT_57", displayName: "PLLMULT 57" },
	{ name: "SYSCTL_PLLMULT_58", displayName: "PLLMULT 58" },
	{ name: "SYSCTL_PLLMULT_59", displayName: "PLLMULT 59" },
	{ name: "SYSCTL_PLLMULT_60", displayName: "PLLMULT 60" },
	{ name: "SYSCTL_PLLMULT_61", displayName: "PLLMULT 61" },
	{ name: "SYSCTL_PLLMULT_62", displayName: "PLLMULT 62" },
	{ name: "SYSCTL_PLLMULT_63", displayName: "PLLMULT 63" },
	{ name: "SYSCTL_PLLMULT_64", displayName: "PLLMULT 64" },
	{ name: "SYSCTL_PLLMULT_65", displayName: "PLLMULT 65" },
	{ name: "SYSCTL_PLLMULT_66", displayName: "PLLMULT 66" },
	{ name: "SYSCTL_PLLMULT_67", displayName: "PLLMULT 67" },
	{ name: "SYSCTL_PLLMULT_68", displayName: "PLLMULT 68" },
	{ name: "SYSCTL_PLLMULT_69", displayName: "PLLMULT 69" },
	{ name: "SYSCTL_PLLMULT_70", displayName: "PLLMULT 70" },
	{ name: "SYSCTL_PLLMULT_71", displayName: "PLLMULT 71" },
	{ name: "SYSCTL_PLLMULT_72", displayName: "PLLMULT 72" },
	{ name: "SYSCTL_PLLMULT_73", displayName: "PLLMULT 73" },
	{ name: "SYSCTL_PLLMULT_74", displayName: "PLLMULT 74" },
	{ name: "SYSCTL_PLLMULT_75", displayName: "PLLMULT 75" },
	{ name: "SYSCTL_PLLMULT_76", displayName: "PLLMULT 76" },
	{ name: "SYSCTL_PLLMULT_77", displayName: "PLLMULT 77" },
	{ name: "SYSCTL_PLLMULT_78", displayName: "PLLMULT 78" },
	{ name: "SYSCTL_PLLMULT_79", displayName: "PLLMULT 79" },
	{ name: "SYSCTL_PLLMULT_80", displayName: "PLLMULT 80" },
	{ name: "SYSCTL_PLLMULT_81", displayName: "PLLMULT 81" },
	{ name: "SYSCTL_PLLMULT_82", displayName: "PLLMULT 82" },
	{ name: "SYSCTL_PLLMULT_83", displayName: "PLLMULT 83" },
	{ name: "SYSCTL_PLLMULT_84", displayName: "PLLMULT 84" },
	{ name: "SYSCTL_PLLMULT_85", displayName: "PLLMULT 85" },
	{ name: "SYSCTL_PLLMULT_86", displayName: "PLLMULT 86" },
	{ name: "SYSCTL_PLLMULT_87", displayName: "PLLMULT 87" },
	{ name: "SYSCTL_PLLMULT_88", displayName: "PLLMULT 88" },
	{ name: "SYSCTL_PLLMULT_89", displayName: "PLLMULT 89" },
	{ name: "SYSCTL_PLLMULT_90", displayName: "PLLMULT 90" },
	{ name: "SYSCTL_PLLMULT_91", displayName: "PLLMULT 91" },
	{ name: "SYSCTL_PLLMULT_92", displayName: "PLLMULT 92" },
	{ name: "SYSCTL_PLLMULT_93", displayName: "PLLMULT 93" },
	{ name: "SYSCTL_PLLMULT_94", displayName: "PLLMULT 94" },
	{ name: "SYSCTL_PLLMULT_95", displayName: "PLLMULT 95" },
	{ name: "SYSCTL_PLLMULT_96", displayName: "PLLMULT 96" },
	{ name: "SYSCTL_PLLMULT_97", displayName: "PLLMULT 97" },
	{ name: "SYSCTL_PLLMULT_98", displayName: "PLLMULT 98" },
	{ name: "SYSCTL_PLLMULT_99", displayName: "PLLMULT 99" },
	{ name: "SYSCTL_PLLMULT_100", displayName: "PLLMULT 100" },
	{ name: "SYSCTL_PLLMULT_101", displayName: "PLLMULT 101" },
	{ name: "SYSCTL_PLLMULT_102", displayName: "PLLMULT 102" },
	{ name: "SYSCTL_PLLMULT_103", displayName: "PLLMULT 103" },
	{ name: "SYSCTL_PLLMULT_104", displayName: "PLLMULT 104" },
	{ name: "SYSCTL_PLLMULT_105", displayName: "PLLMULT 105" },
	{ name: "SYSCTL_PLLMULT_106", displayName: "PLLMULT 106" },
	{ name: "SYSCTL_PLLMULT_107", displayName: "PLLMULT 107" },
	{ name: "SYSCTL_PLLMULT_108", displayName: "PLLMULT 108" },
	{ name: "SYSCTL_PLLMULT_109", displayName: "PLLMULT 109" },
	{ name: "SYSCTL_PLLMULT_110", displayName: "PLLMULT 110" },
	{ name: "SYSCTL_PLLMULT_111", displayName: "PLLMULT 111" },
	{ name: "SYSCTL_PLLMULT_112", displayName: "PLLMULT 112" },
	{ name: "SYSCTL_PLLMULT_113", displayName: "PLLMULT 113" },
	{ name: "SYSCTL_PLLMULT_114", displayName: "PLLMULT 114" },
	{ name: "SYSCTL_PLLMULT_115", displayName: "PLLMULT 115" },
	{ name: "SYSCTL_PLLMULT_116", displayName: "PLLMULT 116" },
	{ name: "SYSCTL_PLLMULT_117", displayName: "PLLMULT 117" },
	{ name: "SYSCTL_PLLMULT_118", displayName: "PLLMULT 118" },
	{ name: "SYSCTL_PLLMULT_119", displayName: "PLLMULT 119" },
	{ name: "SYSCTL_PLLMULT_120", displayName: "PLLMULT 120" },
	{ name: "SYSCTL_PLLMULT_121", displayName: "PLLMULT 121" },
	{ name: "SYSCTL_PLLMULT_122", displayName: "PLLMULT 122" },
	{ name: "SYSCTL_PLLMULT_123", displayName: "PLLMULT 123" },
	{ name: "SYSCTL_PLLMULT_124", displayName: "PLLMULT 124" },
	{ name: "SYSCTL_PLLMULT_125", displayName: "PLLMULT 125" },
	{ name: "SYSCTL_PLLMULT_126", displayName: "PLLMULT 126" },
	{ name: "SYSCTL_PLLMULT_127", displayName: "PLLMULT 127" },
	{ name: "SYSCTL_PLLMULT_128", displayName: "PLLMULT 128" },
]
let Sysctl_PLLRDivClk0 = [
	{ name: "SYSCTL_RDIVCLK0_2", displayName: "RDIVCLK0 2" },
	{ name: "SYSCTL_RDIVCLK0_4", displayName: "RDIVCLK0 4" },
	{ name: "SYSCTL_RDIVCLK0_6", displayName: "RDIVCLK0 6" },
	{ name: "SYSCTL_RDIVCLK0_8", displayName: "RDIVCLK0 8" },
	{ name: "SYSCTL_RDIVCLK0_10", displayName: "RDIVCLK0 10" },
	{ name: "SYSCTL_RDIVCLK0_12", displayName: "RDIVCLK0 12" },
	{ name: "SYSCTL_RDIVCLK0_14", displayName: "RDIVCLK0 14" },
	{ name: "SYSCTL_RDIVCLK0_16", displayName: "RDIVCLK0 16" },
	{ name: "SYSCTL_RDIVCLK0_18", displayName: "RDIVCLK0 18" },
	{ name: "SYSCTL_RDIVCLK0_20", displayName: "RDIVCLK0 20" },
	{ name: "SYSCTL_RDIVCLK0_22", displayName: "RDIVCLK0 22" },
	{ name: "SYSCTL_RDIVCLK0_24", displayName: "RDIVCLK0 24" },
	{ name: "SYSCTL_RDIVCLK0_26", displayName: "RDIVCLK0 26" },
	{ name: "SYSCTL_RDIVCLK0_28", displayName: "RDIVCLK0 28" },
	{ name: "SYSCTL_RDIVCLK0_30", displayName: "RDIVCLK0 30" },
	{ name: "SYSCTL_RDIVCLK0_32", displayName: "RDIVCLK0 32" },
]
let Sysctl_PLLSysDiv = [
	{ name: "SYSCTL_SYSDIV_1", displayName: "SYSDIV 1" },
	{ name: "SYSCTL_SYSDIV_2", displayName: "SYSDIV 2" },
	{ name: "SYSCTL_SYSDIV_3", displayName: "SYSDIV 3" },
	{ name: "SYSCTL_SYSDIV_4", displayName: "SYSDIV 4" },
	{ name: "SYSCTL_SYSDIV_5", displayName: "SYSDIV 5" },
	{ name: "SYSCTL_SYSDIV_6", displayName: "SYSDIV 6" },
	{ name: "SYSCTL_SYSDIV_7", displayName: "SYSDIV 7" },
	{ name: "SYSCTL_SYSDIV_8", displayName: "SYSDIV 8" },
	{ name: "SYSCTL_SYSDIV_9", displayName: "SYSDIV 9" },
	{ name: "SYSCTL_SYSDIV_10", displayName: "SYSDIV 10" },
	{ name: "SYSCTL_SYSDIV_11", displayName: "SYSDIV 11" },
	{ name: "SYSCTL_SYSDIV_12", displayName: "SYSDIV 12" },
	{ name: "SYSCTL_SYSDIV_13", displayName: "SYSDIV 13" },
	{ name: "SYSCTL_SYSDIV_14", displayName: "SYSDIV 14" },
	{ name: "SYSCTL_SYSDIV_15", displayName: "SYSDIV 15" },
	{ name: "SYSCTL_SYSDIV_16", displayName: "SYSDIV 16" },
	{ name: "SYSCTL_SYSDIV_17", displayName: "SYSDIV 17" },
	{ name: "SYSCTL_SYSDIV_18", displayName: "SYSDIV 18" },
	{ name: "SYSCTL_SYSDIV_19", displayName: "SYSDIV 19" },
	{ name: "SYSCTL_SYSDIV_20", displayName: "SYSDIV 20" },
	{ name: "SYSCTL_SYSDIV_21", displayName: "SYSDIV 21" },
	{ name: "SYSCTL_SYSDIV_22", displayName: "SYSDIV 22" },
	{ name: "SYSCTL_SYSDIV_23", displayName: "SYSDIV 23" },
	{ name: "SYSCTL_SYSDIV_24", displayName: "SYSDIV 24" },
	{ name: "SYSCTL_SYSDIV_25", displayName: "SYSDIV 25" },
	{ name: "SYSCTL_SYSDIV_26", displayName: "SYSDIV 26" },
	{ name: "SYSCTL_SYSDIV_27", displayName: "SYSDIV 27" },
	{ name: "SYSCTL_SYSDIV_28", displayName: "SYSDIV 28" },
	{ name: "SYSCTL_SYSDIV_29", displayName: "SYSDIV 29" },
	{ name: "SYSCTL_SYSDIV_30", displayName: "SYSDIV 30" },
	{ name: "SYSCTL_SYSDIV_31", displayName: "SYSDIV 31" },
	{ name: "SYSCTL_SYSDIV_32", displayName: "SYSDIV 32" },
	{ name: "SYSCTL_SYSDIV_33", displayName: "SYSDIV 33" },
	{ name: "SYSCTL_SYSDIV_34", displayName: "SYSDIV 34" },
	{ name: "SYSCTL_SYSDIV_35", displayName: "SYSDIV 35" },
	{ name: "SYSCTL_SYSDIV_36", displayName: "SYSDIV 36" },
	{ name: "SYSCTL_SYSDIV_37", displayName: "SYSDIV 37" },
	{ name: "SYSCTL_SYSDIV_38", displayName: "SYSDIV 38" },
	{ name: "SYSCTL_SYSDIV_39", displayName: "SYSDIV 39" },
	{ name: "SYSCTL_SYSDIV_40", displayName: "SYSDIV 40" },
	{ name: "SYSCTL_SYSDIV_41", displayName: "SYSDIV 41" },
	{ name: "SYSCTL_SYSDIV_42", displayName: "SYSDIV 42" },
	{ name: "SYSCTL_SYSDIV_43", displayName: "SYSDIV 43" },
	{ name: "SYSCTL_SYSDIV_44", displayName: "SYSDIV 44" },
	{ name: "SYSCTL_SYSDIV_45", displayName: "SYSDIV 45" },
	{ name: "SYSCTL_SYSDIV_46", displayName: "SYSDIV 46" },
	{ name: "SYSCTL_SYSDIV_47", displayName: "SYSDIV 47" },
	{ name: "SYSCTL_SYSDIV_48", displayName: "SYSDIV 48" },
	{ name: "SYSCTL_SYSDIV_49", displayName: "SYSDIV 49" },
	{ name: "SYSCTL_SYSDIV_50", displayName: "SYSDIV 50" },
	{ name: "SYSCTL_SYSDIV_51", displayName: "SYSDIV 51" },
	{ name: "SYSCTL_SYSDIV_52", displayName: "SYSDIV 52" },
	{ name: "SYSCTL_SYSDIV_53", displayName: "SYSDIV 53" },
	{ name: "SYSCTL_SYSDIV_54", displayName: "SYSDIV 54" },
	{ name: "SYSCTL_SYSDIV_55", displayName: "SYSDIV 55" },
	{ name: "SYSCTL_SYSDIV_56", displayName: "SYSDIV 56" },
	{ name: "SYSCTL_SYSDIV_57", displayName: "SYSDIV 57" },
	{ name: "SYSCTL_SYSDIV_58", displayName: "SYSDIV 58" },
	{ name: "SYSCTL_SYSDIV_59", displayName: "SYSDIV 59" },
	{ name: "SYSCTL_SYSDIV_60", displayName: "SYSDIV 60" },
	{ name: "SYSCTL_SYSDIV_61", displayName: "SYSDIV 61" },
	{ name: "SYSCTL_SYSDIV_62", displayName: "SYSDIV 62" },
	{ name: "SYSCTL_SYSDIV_63", displayName: "SYSDIV 63" },
	{ name: "SYSCTL_SYSDIV_64", displayName: "SYSDIV 64" },
]
let SysCtl_PeripheralPCLOCKCR = [
	{ name: "SYSCTL_PERIPH_CLK_TBCLKSYNC", displayName: "TBCLKSYNC clock" },
]
let SysCtl_PeripheralSOFTPRES = [
	{ name: "SYSCTL_PERIPH_RES_MCPWM1", displayName: "Reset MCPWM1 clock" },
	{ name: "SYSCTL_PERIPH_RES_MCPWM3", displayName: "Reset MCPWM3 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP1", displayName: "Reset ECAP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP1", displayName: "Reset EQEP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCA", displayName: "Reset ADC_A clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS1", displayName: "Reset CMPSS1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS2", displayName: "Reset CMPSS2 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS3", displayName: "Reset CMPSS3 clock" },
	{ name: "SYSCTL_PERIPH_RES_PGA1", displayName: "Reset PGA1 clock" },
	{ name: "SYSCTL_PERIPH_RES_I2CA", displayName: "Reset I2C_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SCIA", displayName: "Reset SCI_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SCIB", displayName: "Reset SCI_B clock" },
	{ name: "SYSCTL_PERIPH_RES_UARTA", displayName: "Reset UART_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIA", displayName: "Reset SPI_A clock" },
]
let SysCtl_WDPredivider = [
	{ name: "SYSCTL_WD_PREDIV_2", displayName: "PREDIVCLK = WROSCDIV8 / 2" },
	{ name: "SYSCTL_WD_PREDIV_4", displayName: "PREDIVCLK = WROSCDIV8 / 4" },
	{ name: "SYSCTL_WD_PREDIV_8", displayName: "PREDIVCLK = WROSCDIV8 / 8" },
	{ name: "SYSCTL_WD_PREDIV_16", displayName: "PREDIVCLK = WROSCDIV8 / 16" },
	{ name: "SYSCTL_WD_PREDIV_32", displayName: "PREDIVCLK = WROSCDIV8 / 32" },
	{ name: "SYSCTL_WD_PREDIV_64", displayName: "PREDIVCLK = WROSCDIV8 / 64" },
	{ name: "SYSCTL_WD_PREDIV_128", displayName: "PREDIVCLK = WROSCDIV8 / 128" },
	{ name: "SYSCTL_WD_PREDIV_256", displayName: "PREDIVCLK = WROSCDIV8 / 256" },
	{ name: "SYSCTL_WD_PREDIV_512", displayName: "PREDIVCLK = WROSCDIV8 / 512" },
	{ name: "SYSCTL_WD_PREDIV_1024", displayName: "PREDIVCLK = WROSCDIV8 / 1024" },
	{ name: "SYSCTL_WD_PREDIV_2048", displayName: "PREDIVCLK = WROSCDIV8 / 2048" },
	{ name: "SYSCTL_WD_PREDIV_4096", displayName: "PREDIVCLK = WROSCDIV8 / 4096" },
]
let SysCtl_WDPrescaler = [
	{ name: "SYSCTL_WD_PRESCALE_1", displayName: "WDCLK = PREDIVCLK / 1" },
	{ name: "SYSCTL_WD_PRESCALE_2", displayName: "WDCLK = PREDIVCLK / 2" },
	{ name: "SYSCTL_WD_PRESCALE_4", displayName: "WDCLK = PREDIVCLK / 4" },
	{ name: "SYSCTL_WD_PRESCALE_8", displayName: "WDCLK = PREDIVCLK / 8" },
	{ name: "SYSCTL_WD_PRESCALE_16", displayName: "WDCLK = PREDIVCLK / 16" },
	{ name: "SYSCTL_WD_PRESCALE_32", displayName: "WDCLK = PREDIVCLK / 32" },
	{ name: "SYSCTL_WD_PRESCALE_64", displayName: "WDCLK = PREDIVCLK / 64" },
]
let SysCtl_WDMode = [
	{ name: "SYSCTL_WD_MODE_RESET", displayName: "Watchdog can generate a reset signal" },
	{ name: "SYSCTL_WD_MODE_INTERRUPT", displayName: "Watchdog can generate an interrupt signal; reset signal is disabled" },
]
let SysCtl_LSPCLKPrescaler = [
	{ name: "SYSCTL_LSPCLK_PRESCALE_1", displayName: "LSPCLK = SYSCLK / 1" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_2", displayName: "LSPCLK = SYSCLK / 2" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_4", displayName: "LSPCLK = SYSCLK / 4 (default)" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_6", displayName: "LSPCLK = SYSCLK / 6" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_8", displayName: "LSPCLK = SYSCLK / 8" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_10", displayName: "LSPCLK = SYSCLK / 10" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_12", displayName: "LSPCLK = SYSCLK / 12" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_14", displayName: "LSPCLK = SYSCLK / 14" },
]
let SysCtl_ClockOut = [
	{ name: "SYSCTL_CLOCKOUT_PLLSYS", displayName: "PLL System Clock post SYSCLKDIV" },
	{ name: "SYSCTL_CLOCKOUT_PLLCLK", displayName: "PLL Clock after Bypass Mux" },
	{ name: "SYSCTL_CLOCKOUT_SYSCLK", displayName: "CPU System Clock" },
	{ name: "SYSCTL_CLOCKOUT_WROSC", displayName: "Wide-range Oscillator" },
	{ name: "SYSCTL_CLOCKOUT_SYSOSC", displayName: "System Oscillator" },
	{ name: "SYSCTL_CLOCKOUT_WROSCDIV8", displayName: "Wide-range Oscillator BY 8" },
	{ name: "SYSCTL_CLOCKOUT_SYSOSCDIV4", displayName: "System Oscillator BY 4" },
	{ name: "SYSCTL_CLOCKOUT_XTALOSC", displayName: "External Oscillator" },
	{ name: "SYSCTL_CLOCKOUT_PLLRAW", displayName: "PLL System Clock pre SYSCLKDIV" },
]
let SysCtl_ExternalOscMode = [
	{ name: "SYSCTL_XTALMODE_CRYSTAL", displayName: "XTAL Oscillator Crystal Mode" },
	{ name: "SYSCTL_XTALMODE_SINGLE", displayName: "XTAL Oscillator Single-Ended Mode" },
]
let SysCtl_SyncOutputSource = [
	{ name: "SYSCTL_SYNC_OUT_SRC_MCPWM1SYNCOUT", displayName: "MCPWM1SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_MCPWM3SYNCOUT", displayName: "MCPWM3SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP1SYNCOUT", displayName: "ECAP1SYNCOUT --> EXTSYNCOUT" },
]
let SysCtl_DeviceParametric = [
	{ name: "SYSCTL_DEVICE_QUAL", displayName: "Device Qualification Status" },
	{ name: "SYSCTL_DEVICE_FLASH", displayName: "Device Flash size (KB)" },
	{ name: "SYSCTL_DEVICE_FAMILY", displayName: "Device Family" },
	{ name: "SYSCTL_DEVICE_PARTNO", displayName: "Device Part Number" },
	{ name: "SYSCTL_DEVICE_CLASSID", displayName: "Device Class ID" },
]
let SysCtl_SelType = [
	{ name: "SYSCTL_ECAPTYPE", displayName: "Configure ECAP Type : - Type 0 : No EALLOW protection for ECAP registers - Type 1 : ECAP registers are EALLOW protected" },
]
let SysCtl_XClkDivider = [
	{ name: "SYSCTL_XCLKOUT_DIV_1", displayName: "XCLKOUT =  XCLKOUT / 1" },
	{ name: "SYSCTL_XCLKOUT_DIV_2", displayName: "XCLKOUT =  XCLKOUT / 2" },
	{ name: "SYSCTL_XCLKOUT_DIV_4", displayName: "XCLKOUT =  XCLKOUT / 4" },
	{ name: "SYSCTL_XCLKOUT_DIV_8", displayName: "XCLKOUT =  XCLKOUT / 8" },
]
let SysCtl_Cputimer2ClkDivider = [
	{ name: "SYSCTL_TMR2CLKPRESCALE_1", displayName: "Cputimer2 clock =  Cputimer2 clock / 1" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_2", displayName: "Cputimer2 clock =  Cputimer2 clock / 2" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_4", displayName: "Cputimer2 clock =  Cputimer2 clock / 4" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_8", displayName: "Cputimer2 clock =  Cputimer2 clock / 8" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_16", displayName: "Cputimer2 clock =  Cputimer2 clock / 16" },
]
let SysCtl_Cputimer2ClkSource = [
	{ name: "SYSCTL_TMR2CLKSRCSEL_SYSCLK", displayName: "System Clock" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_WROSCDIV8", displayName: "Wide-range Oscillator" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_SYSOSCDIV4", displayName: "System Oscillator" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_XTAL", displayName: "Crystal oscillator" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_AUXPLLCLK", displayName: "Aux PLL CLock" },
]
let SysCtl_ClkRegSel = [
	{ name: "SYSCTL_CLK_REG_SEL_ALL", displayName: "ALL lock" },
]
let SysCtl_CpuRegSel = [
	{ name: "SYSCTL_CPU_REG_SEL_ALL", displayName: "ALL lock" },
	{ name: "SYSCTL_CPU_REG_SEL_BROMPATCH", displayName: "BROMPATCH lock" },
]
let SysCtl_UserRegister = [
	{ name: "SYSCTL_USER_REG1_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_USER_REG2_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_USER_REG1_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_USER_REG2_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_USER_REG1_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG2_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG3_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG4_PORESETN", displayName: "User register reset by PORESETn" },
]
let SysCtl_CMPSSLPMSel = [
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_1H", displayName: "CMPSSLPMSEL CMPSS 1H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_1L", displayName: "CMPSSLPMSEL CMPSS 1L" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_2H", displayName: "CMPSSLPMSEL CMPSS 2H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_2L", displayName: "CMPSSLPMSEL CMPSS 2L" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_3H", displayName: "CMPSSLPMSEL CMPSS 3H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_3L", displayName: "CMPSSLPMSEL CMPSS 3L" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_4H", displayName: "CMPSSLPMSEL CMPSS 4H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_4L", displayName: "CMPSSLPMSEL CMPSS 4L" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_5H", displayName: "CMPSSLPMSEL CMPSS 5H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_5L", displayName: "CMPSSLPMSEL CMPSS 5L" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_6H", displayName: "CMPSSLPMSEL CMPSS 6H" },
	{ name: "SYSCTL_CMPSSLPMSEL_CMPSS_6L", displayName: "CMPSSLPMSEL CMPSS 6L" },
]
let SYSCTL_NMI = [
	{ name: "SYSCTL_NMI_NMIINT", displayName: "NMI Interrupt Flag" },
	{ name: "SYSCTL_NMI_CLOCKFAIL", displayName: "Clock Fail Interrupt Flag" },
	{ name: "SYSCTL_NMI_UNCERR", displayName: "Flash/RAM/ROM Uncorrectable Error NMI Flag" },
	{ name: "SYSCTL_NMI_SWERR", displayName: "SW Error Force NMI Flag" },
]
let SYSCTL_STATUS_SYS_ERR = [
	{ name: "SYSCTL_STATUS_GINT", displayName: "Global Interrupt flag" },
	{ name: "SYSCTL_STATUS_CORRECTABLE_ERR", displayName: "RAM/Flash correctable error flag" },
	{ name: "SYSCTL_STATUS_FPU_UFLOW", displayName: "FPU_UFLOW Interrupt flag." },
	{ name: "SYSCTL_STATUS_FPU_OFLOW", displayName: "FPU_OFLOW Interrupt flag." },
]
let SYSCTL_CAUSE = [
	{ name: "SYSCTL_CAUSE_POR", displayName: "Power-on reset" },
	{ name: "SYSCTL_CAUSE_XRS", displayName: "External reset pin" },
	{ name: "SYSCTL_CAUSE_WDRS", displayName: "Watchdog reset" },
	{ name: "SYSCTL_CAUSE_NMIWDRS", displayName: "NMI watchdog reset" },
	{ name: "SYSCTL_CAUSE_SCCRESET", displayName: "SCCRESETn by DCSM" },
	{ name: "SYSCTL_CAUSE_SIMRESET_CPU1RSN", displayName: "SIMRESET_CPU1RSn" },
	{ name: "SYSCTL_CAUSE_SIMRESET_XRSN", displayName: "SIMRESET_XRSn" },
]
let SYSCTL_ADCSOC_SRC = [
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCA", displayName: "PWM1 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCA", displayName: "PWM3 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCB", displayName: "PWM1 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCB", displayName: "PWM3 SOCB for ADCSOCBO" },
]
module.exports = {
	Sysctl_PLLConfig: Sysctl_PLLConfig,
	Sysctl_PLLPDiv: Sysctl_PLLPDiv,
	Sysctl_PLLMult: Sysctl_PLLMult,
	Sysctl_PLLRDivClk0: Sysctl_PLLRDivClk0,
	Sysctl_PLLSysDiv: Sysctl_PLLSysDiv,
	SysCtl_PeripheralPCLOCKCR: SysCtl_PeripheralPCLOCKCR,
	SysCtl_PeripheralSOFTPRES: SysCtl_PeripheralSOFTPRES,
	SysCtl_WDPredivider: SysCtl_WDPredivider,
	SysCtl_WDPrescaler: SysCtl_WDPrescaler,
	SysCtl_WDMode: SysCtl_WDMode,
	SysCtl_LSPCLKPrescaler: SysCtl_LSPCLKPrescaler,
	SysCtl_ClockOut: SysCtl_ClockOut,
	SysCtl_ExternalOscMode: SysCtl_ExternalOscMode,
	SysCtl_SyncOutputSource: SysCtl_SyncOutputSource,
	SysCtl_DeviceParametric: SysCtl_DeviceParametric,
	SysCtl_SelType: SysCtl_SelType,
	SysCtl_XClkDivider: SysCtl_XClkDivider,
	SysCtl_Cputimer2ClkDivider: SysCtl_Cputimer2ClkDivider,
	SysCtl_Cputimer2ClkSource: SysCtl_Cputimer2ClkSource,
	SysCtl_ClkRegSel: SysCtl_ClkRegSel,
	SysCtl_CpuRegSel: SysCtl_CpuRegSel,
	SysCtl_UserRegister: SysCtl_UserRegister,
	SysCtl_CMPSSLPMSel: SysCtl_CMPSSLPMSel,
	SYSCTL_NMI: SYSCTL_NMI,
	SYSCTL_STATUS_SYS_ERR: SYSCTL_STATUS_SYS_ERR,
	SYSCTL_CAUSE: SYSCTL_CAUSE,
	SYSCTL_ADCSOC_SRC: SYSCTL_ADCSOC_SRC,
}
