let DMA_Trigger = [
	{ name: "DMA_TRIGGER_SOFTWARE", displayName: "TRIGGER SOFTWARE" },
	{ name: "DMA_TRIGGER_ADCA1", displayName: "TRIGGER ADCA1" },
	{ name: "DMA_TRIGGER_ADCA2", displayName: "TRIGGER ADCA2" },
	{ name: "DMA_TRIGGER_ADCA3", displayName: "TRIGGER ADCA3" },
	{ name: "DMA_TRIGGER_ADCA4", displayName: "TRIGGER ADCA4" },
	{ name: "DMA_TRIGGER_ADCAEVT", displayName: "TRIGGER ADCAEVT" },
	{ name: "DMA_TRIGGER_ADCB1", displayName: "TRIGGER ADCB1" },
	{ name: "DMA_TRIGGER_ADCB2", displayName: "TRIGGER ADCB2" },
	{ name: "DMA_TRIGGER_ADCB3", displayName: "TRIGGER ADCB3" },
	{ name: "DMA_TRIGGER_ADCB4", displayName: "TRIGGER ADCB4" },
	{ name: "DMA_TRIGGER_ADCBEVT", displayName: "TRIGGER ADCBEVT" },
	{ name: "DMA_TRIGGER_ADCC1", displayName: "TRIGGER ADCC1" },
	{ name: "DMA_TRIGGER_ADCC2", displayName: "TRIGGER ADCC2" },
	{ name: "DMA_TRIGGER_ADCC3", displayName: "TRIGGER ADCC3" },
	{ name: "DMA_TRIGGER_ADCC4", displayName: "TRIGGER ADCC4" },
	{ name: "DMA_TRIGGER_ADCCEVT", displayName: "TRIGGER ADCCEVT" },
	{ name: "DMA_TRIGGER_ADCD1", displayName: "TRIGGER ADCD1" },
	{ name: "DMA_TRIGGER_ADCD2", displayName: "TRIGGER ADCD2" },
	{ name: "DMA_TRIGGER_ADCD3", displayName: "TRIGGER ADCD3" },
	{ name: "DMA_TRIGGER_ADCD4", displayName: "TRIGGER ADCD4" },
	{ name: "DMA_TRIGGER_ADCDEVT", displayName: "TRIGGER ADCDEVT" },
	{ name: "DMA_TRIGGER_CLA1", displayName: "TRIGGER CLA1" },
	{ name: "DMA_TRIGGER_CLA2", displayName: "TRIGGER CLA2" },
	{ name: "DMA_TRIGGER_CLA3", displayName: "TRIGGER CLA3" },
	{ name: "DMA_TRIGGER_CLA4", displayName: "TRIGGER CLA4" },
	{ name: "DMA_TRIGGER_CLA5", displayName: "TRIGGER CLA5" },
	{ name: "DMA_TRIGGER_CLA6", displayName: "TRIGGER CLA6" },
	{ name: "DMA_TRIGGER_CLA7", displayName: "TRIGGER CLA7" },
	{ name: "DMA_TRIGGER_CLA8", displayName: "TRIGGER CLA8" },
	{ name: "DMA_TRIGGER_XINT1", displayName: "TRIGGER XINT1" },
	{ name: "DMA_TRIGGER_XINT2", displayName: "TRIGGER XINT2" },
	{ name: "DMA_TRIGGER_XINT3", displayName: "TRIGGER XINT3" },
	{ name: "DMA_TRIGGER_XINT4", displayName: "TRIGGER XINT4" },
	{ name: "DMA_TRIGGER_XINT5", displayName: "TRIGGER XINT5" },
	{ name: "DMA_TRIGGER_EPWM1SOCA", displayName: "TRIGGER EPWM1SOCA" },
	{ name: "DMA_TRIGGER_EPWM1SOCB", displayName: "TRIGGER EPWM1SOCB" },
	{ name: "DMA_TRIGGER_EPWM2SOCA", displayName: "TRIGGER EPWM2SOCA" },
	{ name: "DMA_TRIGGER_EPWM2SOCB", displayName: "TRIGGER EPWM2SOCB" },
	{ name: "DMA_TRIGGER_EPWM3SOCA", displayName: "TRIGGER EPWM3SOCA" },
	{ name: "DMA_TRIGGER_EPWM3SOCB", displayName: "TRIGGER EPWM3SOCB" },
	{ name: "DMA_TRIGGER_EPWM4SOCA", displayName: "TRIGGER EPWM4SOCA" },
	{ name: "DMA_TRIGGER_EPWM4SOCB", displayName: "TRIGGER EPWM4SOCB" },
	{ name: "DMA_TRIGGER_EPWM5SOCA", displayName: "TRIGGER EPWM5SOCA" },
	{ name: "DMA_TRIGGER_EPWM5SOCB", displayName: "TRIGGER EPWM5SOCB" },
	{ name: "DMA_TRIGGER_EPWM6SOCA", displayName: "TRIGGER EPWM6SOCA" },
	{ name: "DMA_TRIGGER_EPWM6SOCB", displayName: "TRIGGER EPWM6SOCB" },
	{ name: "DMA_TRIGGER_EPWM7SOCA", displayName: "TRIGGER EPWM7SOCA" },
	{ name: "DMA_TRIGGER_EPWM7SOCB", displayName: "TRIGGER EPWM7SOCB" },
	{ name: "DMA_TRIGGER_EPWM8SOCA", displayName: "TRIGGER EPWM8SOCA" },
	{ name: "DMA_TRIGGER_EPWM8SOCB", displayName: "TRIGGER EPWM8SOCB" },
	{ name: "DMA_TRIGGER_EPWM9SOCA", displayName: "TRIGGER EPWM9SOCA" },
	{ name: "DMA_TRIGGER_EPWM9SOCB", displayName: "TRIGGER EPWM9SOCB" },
	{ name: "DMA_TRIGGER_EPWM10SOCA", displayName: "TRIGGER EPWM10SOCA" },
	{ name: "DMA_TRIGGER_EPWM10SOCB", displayName: "TRIGGER EPWM10SOCB" },
	{ name: "DMA_TRIGGER_EPWM11SOCA", displayName: "TRIGGER EPWM11SOCA" },
	{ name: "DMA_TRIGGER_EPWM11SOCB", displayName: "TRIGGER EPWM11SOCB" },
	{ name: "DMA_TRIGGER_EPWM12SOCA", displayName: "TRIGGER EPWM12SOCA" },
	{ name: "DMA_TRIGGER_EPWM12SOCB", displayName: "TRIGGER EPWM12SOCB" },
	{ name: "DMA_TRIGGER_TINT0", displayName: "TRIGGER TINT0" },
	{ name: "DMA_TRIGGER_TINT1", displayName: "TRIGGER TINT1" },
	{ name: "DMA_TRIGGER_TINT2", displayName: "TRIGGER TINT2" },
	{ name: "DMA_TRIGGER_ECAP1", displayName: "TRIGGER ECAP1" },
	{ name: "DMA_TRIGGER_ECAP2", displayName: "TRIGGER ECAP2" },
	{ name: "DMA_TRIGGER_LINATX", displayName: "TRIGGER LINATX" },
	{ name: "DMA_TRIGGER_LINARX", displayName: "TRIGGER LINARX" },
	{ name: "DMA_TRIGGER_SPIATX", displayName: "TRIGGER SPIATX" },
	{ name: "DMA_TRIGGER_SPIARX", displayName: "TRIGGER SPIARX" },
	{ name: "DMA_TRIGGER_SPIBTX", displayName: "TRIGGER SPIBTX" },
	{ name: "DMA_TRIGGER_SPIBRX", displayName: "TRIGGER SPIBRX" },
	{ name: "DMA_TRIGGER_FSITXA", displayName: "TRIGGER FSITXA" },
	{ name: "DMA_TRIGGER_FSIA_DATA_TAG_MATCH", displayName: "TRIGGER FSIA DATA TAG MATCH" },
	{ name: "DMA_TRIGGER_FSIRXA", displayName: "TRIGGER FSIRXA" },
	{ name: "DMA_TRIGGER_FSIA_PING_TAG_MATCH", displayName: "TRIGGER FSIA PING TAG MATCH" },
	{ name: "DMA_TRIGGER_CLB1INT", displayName: "TRIGGER CLB1INT" },
	{ name: "DMA_TRIGGER_CLB2INT", displayName: "TRIGGER CLB2INT" },
	{ name: "DMA_TRIGGER_USBA_RX1", displayName: "TRIGGER USBA RX1" },
	{ name: "DMA_TRIGGER_USBA_TX1", displayName: "TRIGGER USBA TX1" },
	{ name: "DMA_TRIGGER_USBA_RX2", displayName: "TRIGGER USBA RX2" },
	{ name: "DMA_TRIGGER_USBA_TX2", displayName: "TRIGGER USBA TX2" },
	{ name: "DMA_TRIGGER_USBA_RX3", displayName: "TRIGGER USBA RX3" },
	{ name: "DMA_TRIGGER_USBA_TX3", displayName: "TRIGGER USBA TX3" },
	{ name: "DMA_TRIGGER_ADCE1", displayName: "TRIGGER ADCE1" },
	{ name: "DMA_TRIGGER_ADCE2", displayName: "TRIGGER ADCE2" },
	{ name: "DMA_TRIGGER_ADCE3", displayName: "TRIGGER ADCE3" },
	{ name: "DMA_TRIGGER_ADCE4", displayName: "TRIGGER ADCE4" },
	{ name: "DMA_TRIGGER_ADCEEVT", displayName: "TRIGGER ADCEEVT" },
	{ name: "DMA_TRIGGER_AESA_CONTEXTIN", displayName: "TRIGGER AESA CONTEXTIN" },
	{ name: "DMA_TRIGGER_AESA_DATAIN", displayName: "TRIGGER AESA DATAIN" },
	{ name: "DMA_TRIGGER_AESA_CONTEXTOUT", displayName: "TRIGGER AESA CONTEXTOUT" },
	{ name: "DMA_TRIGGER_AESA_DATAOUT", displayName: "TRIGGER AESA DATAOUT" },
	{ name: "DMA_TRIGGER_EPG1", displayName: "TRIGGER EPG1" },
]
let DMA_InterruptMode = [
	{ name: "DMA_INT_AT_BEGINNING", displayName: "DMA interrupt is generated at the beginning of a transfer" },
	{ name: "DMA_INT_AT_END", displayName: "DMA interrupt is generated at the end of a transfer" },
]
let DMA_EmulationMode = [
	{ name: "DMA_EMULATION_STOP", displayName: "Transmission stops after current read-write access is completed" },
	{ name: "DMA_EMULATION_FREE_RUN", displayName: "Continue DMA operation regardless of emulation suspend" },
]
let DMA_CFG = [
	{ name: "DMA_CFG_ONESHOT_DISABLE", displayName: "Only one burst transfer performed per trigger." },
	{ name: "DMA_CFG_ONESHOT_ENABLE", displayName: "Burst transfers occur without additional event triggers after the first." },
	{ name: "DMA_CFG_CONTINUOUS_DISABLE", displayName: "DMA channel will be disabled at the end of a transfer." },
	{ name: "DMA_CFG_CONTINUOUS_ENABLE", displayName: "DMA reinitializes when the transfer count is zero and waits for a trigger." },
	{ name: "DMA_CFG_SIZE_16BIT", displayName: "DMA transfers 16 bits at a time." },
	{ name: "DMA_CFG_SIZE_32BIT", displayName: "DMA transfers 32 bits at a time." },
]
module.exports = {
	DMA_Trigger: DMA_Trigger,
	DMA_InterruptMode: DMA_InterruptMode,
	DMA_EmulationMode: DMA_EmulationMode,
	DMA_CFG: DMA_CFG,
}
