let SysCtl_PeripheralPCLOCKCR = [
	{ name: "SYSCTL_PERIPH_CLK_CLA1", displayName: "CLA1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_DMA", displayName: "DMA clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER0", displayName: "CPUTIMER0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER1", displayName: "CPUTIMER1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_TIMER2", displayName: "CPUTIMER2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CPUBGCRC", displayName: "CPUBGCRC clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLA1BGCRC", displayName: "CLA1BGCRC clock" },
	{ name: "SYSCTL_PERIPH_CLK_TBCLKSYNC", displayName: "TBCLKSYNC clock" },
	{ name: "SYSCTL_PERIPH_CLK_GTBCLKSYNC", displayName: "GTBCLKSYNC clock" },
	{ name: "SYSCTL_PERIPH_CLK_ERAD", displayName: "ERAD clock" },
	{ name: "SYSCTL_PERIPH_CLK_EMIF1", displayName: "EMIF1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM1", displayName: "EPWM1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM2", displayName: "EPWM2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM3", displayName: "EPWM3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM4", displayName: "EPWM4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM5", displayName: "EPWM5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM6", displayName: "EPWM6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM7", displayName: "EPWM7 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM8", displayName: "EPWM8 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM9", displayName: "EPWM9 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM10", displayName: "EPWM10 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM11", displayName: "EPWM11 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM12", displayName: "EPWM12 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM13", displayName: "EPWM13 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM14", displayName: "EPWM14 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM15", displayName: "EPWM15 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM16", displayName: "EPWM16 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM17", displayName: "EPWM17 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPWM18", displayName: "EPWM18 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP1", displayName: "ECAP1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP2", displayName: "ECAP2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP3", displayName: "ECAP3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP4", displayName: "ECAP4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP5", displayName: "ECAP5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP6", displayName: "ECAP6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAP7", displayName: "ECAP7 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP1", displayName: "EQEP1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP2", displayName: "EQEP2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP3", displayName: "EQEP3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP4", displayName: "EQEP4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP5", displayName: "EQEP5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_EQEP6", displayName: "EQEP6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SD1", displayName: "SD1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SD2", displayName: "SD2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SD3", displayName: "SD3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SD4", displayName: "SD4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_SCIA", displayName: "SCI_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_SCIB", displayName: "SCI_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_UARTA", displayName: "UART_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_UARTB", displayName: "UART_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPIA", displayName: "SPI_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPIB", displayName: "SPI_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPIC", displayName: "SPI_C clock" },
	{ name: "SYSCTL_PERIPH_CLK_SPID", displayName: "SPI_D clock" },
	{ name: "SYSCTL_PERIPH_CLK_I2CA", displayName: "I2C_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_I2CB", displayName: "I2C_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_PMBUSA", displayName: "PMBUS_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_CANA", displayName: "CAN_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_MCANA", displayName: "MCAN_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_MCANB", displayName: "MCAN_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_USBA", displayName: "USB_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCA", displayName: "ADC_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCB", displayName: "ADC_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCC", displayName: "ADC_C clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS1", displayName: "CMPSS1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS2", displayName: "CMPSS2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS3", displayName: "CMPSS3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS4", displayName: "CMPSS4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS5", displayName: "CMPSS5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS6", displayName: "CMPSS6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS7", displayName: "CMPSS7 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS8", displayName: "CMPSS8 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS9", displayName: "CMPSS9 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS10", displayName: "CMPSS10 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CMPSS11", displayName: "CMPSS11 clock" },
	{ name: "SYSCTL_PERIPH_CLK_DACA", displayName: "DAC_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_DACC", displayName: "DAC_C clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB1", displayName: "CLB1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB2", displayName: "CLB2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB3", displayName: "CLB3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB4", displayName: "CLB4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB5", displayName: "CLB5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_CLB6", displayName: "CLB6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSITXA", displayName: "FSITX_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSITXB", displayName: "FSITX_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSIRXA", displayName: "FSIRX_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSIRXB", displayName: "FSIRX_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSIRXC", displayName: "FSIRX_C clock" },
	{ name: "SYSCTL_PERIPH_CLK_FSIRXD", displayName: "FSIRX_D clock" },
	{ name: "SYSCTL_PERIPH_CLK_LINA", displayName: "LIN_A clock" },
	{ name: "SYSCTL_PERIPH_CLK_LINB", displayName: "LIN_B clock" },
	{ name: "SYSCTL_PERIPH_CLK_DCC0", displayName: "DCC0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_DCC1", displayName: "DCC1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_DCC2", displayName: "DCC2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ECAT", displayName: "ETHERCAT clock" },
	{ name: "SYSCTL_PERIPH_CLK_HRCAL0", displayName: "HRCAL0 clock" },
	{ name: "SYSCTL_PERIPH_CLK_HRCAL1", displayName: "HRCAL1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_HRCAL2", displayName: "HRCAL2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_AESA", displayName: "AESA clock" },
	{ name: "SYSCTL_PERIPH_CLK_EPG1", displayName: "EPG1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER1", displayName: "ADCCHECKER1 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER2", displayName: "ADCCHECKER2 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER3", displayName: "ADCCHECKER3 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER4", displayName: "ADCCHECKER4 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER5", displayName: "ADCCHECKER5 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER6", displayName: "ADCCHECKER6 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER7", displayName: "ADCCHECKER7 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCCHECKER8", displayName: "ADCCHECKER8 clock" },
	{ name: "SYSCTL_PERIPH_CLK_ADCSEAGGRCPU1", displayName: "ADCSEAGGRCPU1 clock" },
]
let SysCtl_PeripheralSOFTPRES = [
	{ name: "SYSCTL_PERIPH_RES_CPU1CLA1", displayName: "Reset CPU1_CLA1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU1CPUBGCRC", displayName: "Reset CPU1_CPUBGCRC clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU1CLA1BGCRC", displayName: "Reset CPU1_CLA1BGCRC clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU2CPUBGCRC", displayName: "Reset CPU2_CPUBGCRC clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU1ERAD", displayName: "Reset CPU1_ERAD clock" },
	{ name: "SYSCTL_PERIPH_RES_CPU2ERAD", displayName: "Reset CPU2_ERAD clock" },
	{ name: "SYSCTL_PERIPH_RES_EMIF1", displayName: "Reset EMIF1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM1", displayName: "Reset EPWM1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM2", displayName: "Reset EPWM2 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM3", displayName: "Reset EPWM3 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM4", displayName: "Reset EPWM4 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM5", displayName: "Reset EPWM5 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM6", displayName: "Reset EPWM6 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM7", displayName: "Reset EPWM7 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM8", displayName: "Reset EPWM8 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM9", displayName: "Reset EPWM9 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM10", displayName: "Reset EPWM10 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM11", displayName: "Reset EPWM11 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM12", displayName: "Reset EPWM12 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM13", displayName: "Reset EPWM13 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM14", displayName: "Reset EPWM14 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM15", displayName: "Reset EPWM15 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM16", displayName: "Reset EPWM16 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM17", displayName: "Reset EPWM17 clock" },
	{ name: "SYSCTL_PERIPH_RES_EPWM18", displayName: "Reset EPWM18 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP1", displayName: "Reset ECAP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP2", displayName: "Reset ECAP2 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP3", displayName: "Reset ECAP3 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP4", displayName: "Reset ECAP4 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP5", displayName: "Reset ECAP5 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP6", displayName: "Reset ECAP6 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAP7", displayName: "Reset ECAP7 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP1", displayName: "Reset EQEP1 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP2", displayName: "Reset EQEP2 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP3", displayName: "Reset EQEP3 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP4", displayName: "Reset EQEP4 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP5", displayName: "Reset EQEP5 clock" },
	{ name: "SYSCTL_PERIPH_RES_EQEP6", displayName: "Reset EQEP6 clock" },
	{ name: "SYSCTL_PERIPH_RES_SD1", displayName: "Reset SD1 clock" },
	{ name: "SYSCTL_PERIPH_RES_SD2", displayName: "Reset SD2 clock" },
	{ name: "SYSCTL_PERIPH_RES_SD3", displayName: "Reset SD3 clock" },
	{ name: "SYSCTL_PERIPH_RES_SD4", displayName: "Reset SD4 clock" },
	{ name: "SYSCTL_PERIPH_RES_SCIA", displayName: "Reset SCI_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SCIB", displayName: "Reset SCI_B clock" },
	{ name: "SYSCTL_PERIPH_RES_UARTA", displayName: "Reset UART_A clock" },
	{ name: "SYSCTL_PERIPH_RES_UARTB", displayName: "Reset UART_B clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIA", displayName: "Reset SPI_A clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIB", displayName: "Reset SPI_B clock" },
	{ name: "SYSCTL_PERIPH_RES_SPIC", displayName: "Reset SPI_C clock" },
	{ name: "SYSCTL_PERIPH_RES_SPID", displayName: "Reset SPI_D clock" },
	{ name: "SYSCTL_PERIPH_RES_I2CA", displayName: "Reset I2C_A clock" },
	{ name: "SYSCTL_PERIPH_RES_I2CB", displayName: "Reset I2C_B clock" },
	{ name: "SYSCTL_PERIPH_RES_PMBUSA", displayName: "Reset PMBUS_A clock" },
	{ name: "SYSCTL_PERIPH_RES_CANA", displayName: "Reset CAN_A clock" },
	{ name: "SYSCTL_PERIPH_RES_MCANA", displayName: "Reset MCAN_A clock" },
	{ name: "SYSCTL_PERIPH_RES_MCANB", displayName: "Reset MCAN_B clock" },
	{ name: "SYSCTL_PERIPH_RES_USBA", displayName: "Reset USB_A clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCA", displayName: "Reset ADC_A clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCB", displayName: "Reset ADC_B clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCC", displayName: "Reset ADC_C clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS1", displayName: "Reset CMPSS1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS2", displayName: "Reset CMPSS2 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS3", displayName: "Reset CMPSS3 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS4", displayName: "Reset CMPSS4 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS5", displayName: "Reset CMPSS5 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS6", displayName: "Reset CMPSS6 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS7", displayName: "Reset CMPSS7 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS8", displayName: "Reset CMPSS8 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS9", displayName: "Reset CMPSS9 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS10", displayName: "Reset CMPSS10 clock" },
	{ name: "SYSCTL_PERIPH_RES_CMPSS11", displayName: "Reset CMPSS11 clock" },
	{ name: "SYSCTL_PERIPH_RES_DACA", displayName: "Reset DAC_A clock" },
	{ name: "SYSCTL_PERIPH_RES_DACC", displayName: "Reset DAC_C clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB1", displayName: "Reset CLB1 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB2", displayName: "Reset CLB2 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB3", displayName: "Reset CLB3 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB4", displayName: "Reset CLB4 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB5", displayName: "Reset CLB5 clock" },
	{ name: "SYSCTL_PERIPH_RES_CLB6", displayName: "Reset CLB6 clock" },
	{ name: "SYSCTL_PERIPH_RES_FSITXA", displayName: "Reset FSITX_A clock" },
	{ name: "SYSCTL_PERIPH_RES_FSITXB", displayName: "Reset FSITX_B clock" },
	{ name: "SYSCTL_PERIPH_RES_FSIRXA", displayName: "Reset FSIRX_A clock" },
	{ name: "SYSCTL_PERIPH_RES_FSIRXB", displayName: "Reset FSIRX_B clock" },
	{ name: "SYSCTL_PERIPH_RES_FSIRXC", displayName: "Reset FSIRX_C clock" },
	{ name: "SYSCTL_PERIPH_RES_FSIRXD", displayName: "Reset FSIRX_D clock" },
	{ name: "SYSCTL_PERIPH_RES_LINA", displayName: "Reset LIN_A clock" },
	{ name: "SYSCTL_PERIPH_RES_LINB", displayName: "Reset LIN_B clock" },
	{ name: "SYSCTL_PERIPH_RES_DCC0", displayName: "Reset DCC0 clock" },
	{ name: "SYSCTL_PERIPH_RES_DCC1", displayName: "Reset DCC1 clock" },
	{ name: "SYSCTL_PERIPH_RES_DCC2", displayName: "Reset DCC2 clock" },
	{ name: "SYSCTL_PERIPH_RES_ECAT", displayName: "Reset ETHERCAT clock" },
	{ name: "SYSCTL_PERIPH_RES_AESA", displayName: "Reset AESA clock" },
	{ name: "SYSCTL_PERIPH_RES_EPG1", displayName: "Reset EPG1 clock" },
	{ name: "SYSCTL_PERIPH_RES_FLASHA", displayName: "Reset FLASHA clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER1", displayName: "Reset ADCCHECKER1 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER2", displayName: "Reset ADCCHECKER2 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER3", displayName: "Reset ADCCHECKER3 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER4", displayName: "Reset ADCCHECKER4 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER5", displayName: "Reset ADCCHECKER5 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER6", displayName: "Reset ADCCHECKER6 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER7", displayName: "Reset ADCCHECKER7 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCCHECKER8", displayName: "Reset ADCCHECKER8 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCSEAGGRCPU1", displayName: "Reset ADCSEAGGRCPU1 clock" },
	{ name: "SYSCTL_PERIPH_RES_ADCSEAGGRCPU2", displayName: "Reset ADCSEAGGRCPU2 clock" },
]
let SysCtl_CPUSelPeripheral = [
	{ name: "SYSCTL_CPUSEL0_EPWM", displayName: "Configure CPU Select for EPWM" },
	{ name: "SYSCTL_CPUSEL1_ECAP", displayName: "Configure CPU Select for ECAP" },
	{ name: "SYSCTL_CPUSEL2_EQEP", displayName: "Configure CPU Select for EQEP" },
	{ name: "SYSCTL_CPUSEL4_SD", displayName: "Configure CPU Select for SD" },
	{ name: "SYSCTL_CPUSEL5_SCI", displayName: "Configure CPU Select for SCI" },
	{ name: "SYSCTL_CPUSEL6_SPI", displayName: "Configure CPU Select for SPI" },
	{ name: "SYSCTL_CPUSEL7_I2C", displayName: "Configure CPU Select for I2C" },
	{ name: "SYSCTL_CPUSEL8_CAN", displayName: "Configure CPU Select for CAN" },
	{ name: "SYSCTL_CPUSEL11_ADC", displayName: "Configure CPU Select for ADC" },
	{ name: "SYSCTL_CPUSEL12_CMPSS", displayName: "Configure CPU Select for CMPSS" },
	{ name: "SYSCTL_CPUSEL13_DCC", displayName: "Configure CPU Select for DCC" },
	{ name: "SYSCTL_CPUSEL14_DAC", displayName: "Configure CPU Select for DAC" },
	{ name: "SYSCTL_CPUSEL15_CLB", displayName: "Configure CPU Select for CLB" },
	{ name: "SYSCTL_CPUSEL16_FSI", displayName: "Configure CPU Select for FSI" },
	{ name: "SYSCTL_CPUSEL17_LIN", displayName: "Configure CPU Select for LIN" },
	{ name: "SYSCTL_CPUSEL23_ECAT", displayName: "Configure CPU Select for ETHERCAT" },
	{ name: "SYSCTL_CPUSEL25_HRCAL", displayName: "Configure CPU Select for HRCAL" },
	{ name: "SYSCTL_CPUSEL26_AES", displayName: "Configure CPU Select for AES" },
	{ name: "SYSCTL_CPUSEL27_EPG", displayName: "Configure CPU Select for EPG" },
]
let SysCtl_CPUSelPeriphInstance = [
	{ name: "SYSCTL_CPUSEL_EPWM1", displayName: "CPUSEL EPWM1" },
	{ name: "SYSCTL_CPUSEL_EPWM2", displayName: "CPUSEL EPWM2" },
	{ name: "SYSCTL_CPUSEL_EPWM3", displayName: "CPUSEL EPWM3" },
	{ name: "SYSCTL_CPUSEL_EPWM4", displayName: "CPUSEL EPWM4" },
	{ name: "SYSCTL_CPUSEL_EPWM5", displayName: "CPUSEL EPWM5" },
	{ name: "SYSCTL_CPUSEL_EPWM6", displayName: "CPUSEL EPWM6" },
	{ name: "SYSCTL_CPUSEL_EPWM7", displayName: "CPUSEL EPWM7" },
	{ name: "SYSCTL_CPUSEL_EPWM8", displayName: "CPUSEL EPWM8" },
	{ name: "SYSCTL_CPUSEL_EPWM9", displayName: "CPUSEL EPWM9" },
	{ name: "SYSCTL_CPUSEL_EPWM10", displayName: "CPUSEL EPWM10" },
	{ name: "SYSCTL_CPUSEL_EPWM11", displayName: "CPUSEL EPWM11" },
	{ name: "SYSCTL_CPUSEL_EPWM12", displayName: "CPUSEL EPWM12" },
	{ name: "SYSCTL_CPUSEL_EPWM13", displayName: "CPUSEL EPWM13" },
	{ name: "SYSCTL_CPUSEL_EPWM14", displayName: "CPUSEL EPWM14" },
	{ name: "SYSCTL_CPUSEL_EPWM15", displayName: "CPUSEL EPWM15" },
	{ name: "SYSCTL_CPUSEL_EPWM16", displayName: "CPUSEL EPWM16" },
	{ name: "SYSCTL_CPUSEL_EPWM17", displayName: "CPUSEL EPWM17" },
	{ name: "SYSCTL_CPUSEL_EPWM18", displayName: "CPUSEL EPWM18" },
	{ name: "SYSCTL_CPUSEL_ECAP1", displayName: "CPUSEL ECAP1" },
	{ name: "SYSCTL_CPUSEL_ECAP2", displayName: "CPUSEL ECAP2" },
	{ name: "SYSCTL_CPUSEL_ECAP3", displayName: "CPUSEL ECAP3" },
	{ name: "SYSCTL_CPUSEL_ECAP4", displayName: "CPUSEL ECAP4" },
	{ name: "SYSCTL_CPUSEL_ECAP5", displayName: "CPUSEL ECAP5" },
	{ name: "SYSCTL_CPUSEL_ECAP6", displayName: "CPUSEL ECAP6" },
	{ name: "SYSCTL_CPUSEL_ECAP7", displayName: "CPUSEL ECAP7" },
	{ name: "SYSCTL_CPUSEL_EQEP1", displayName: "CPUSEL EQEP1" },
	{ name: "SYSCTL_CPUSEL_EQEP2", displayName: "CPUSEL EQEP2" },
	{ name: "SYSCTL_CPUSEL_EQEP3", displayName: "CPUSEL EQEP3" },
	{ name: "SYSCTL_CPUSEL_EQEP4", displayName: "CPUSEL EQEP4" },
	{ name: "SYSCTL_CPUSEL_EQEP5", displayName: "CPUSEL EQEP5" },
	{ name: "SYSCTL_CPUSEL_EQEP6", displayName: "CPUSEL EQEP6" },
	{ name: "SYSCTL_CPUSEL_HRCAP6", displayName: "CPUSEL HRCAP6" },
	{ name: "SYSCTL_CPUSEL_HRCAP7", displayName: "CPUSEL HRCAP7" },
	{ name: "SYSCTL_CPUSEL_SD1", displayName: "CPUSEL SD1" },
	{ name: "SYSCTL_CPUSEL_SD2", displayName: "CPUSEL SD2" },
	{ name: "SYSCTL_CPUSEL_SD3", displayName: "CPUSEL SD3" },
	{ name: "SYSCTL_CPUSEL_SD4", displayName: "CPUSEL SD4" },
	{ name: "SYSCTL_CPUSEL_SCIA", displayName: "CPUSEL SCIA" },
	{ name: "SYSCTL_CPUSEL_SCIB", displayName: "CPUSEL SCIB" },
	{ name: "SYSCTL_CPUSEL_UARTA", displayName: "CPUSEL UARTA" },
	{ name: "SYSCTL_CPUSEL_UARTB", displayName: "CPUSEL UARTB" },
	{ name: "SYSCTL_CPUSEL_SPIA", displayName: "CPUSEL SPIA" },
	{ name: "SYSCTL_CPUSEL_SPIB", displayName: "CPUSEL SPIB" },
	{ name: "SYSCTL_CPUSEL_SPIC", displayName: "CPUSEL SPIC" },
	{ name: "SYSCTL_CPUSEL_SPID", displayName: "CPUSEL SPID" },
	{ name: "SYSCTL_CPUSEL_I2CA", displayName: "CPUSEL I2CA" },
	{ name: "SYSCTL_CPUSEL_I2CB", displayName: "CPUSEL I2CB" },
	{ name: "SYSCTL_CPUSEL_PMBUSA", displayName: "CPUSEL PMBUSA" },
	{ name: "SYSCTL_CPUSEL_CANA", displayName: "CPUSEL CANA" },
	{ name: "SYSCTL_CPUSEL_MCANA", displayName: "CPUSEL MCANA" },
	{ name: "SYSCTL_CPUSEL_MCANB", displayName: "CPUSEL MCANB" },
	{ name: "SYSCTL_CPUSEL_USBA", displayName: "CPUSEL USBA" },
	{ name: "SYSCTL_CPUSEL_ADCA", displayName: "CPUSEL ADCA" },
	{ name: "SYSCTL_CPUSEL_ADCB", displayName: "CPUSEL ADCB" },
	{ name: "SYSCTL_CPUSEL_ADCC", displayName: "CPUSEL ADCC" },
	{ name: "SYSCTL_CPUSEL_CMPSS1", displayName: "CPUSEL CMPSS1" },
	{ name: "SYSCTL_CPUSEL_CMPSS2", displayName: "CPUSEL CMPSS2" },
	{ name: "SYSCTL_CPUSEL_CMPSS3", displayName: "CPUSEL CMPSS3" },
	{ name: "SYSCTL_CPUSEL_CMPSS4", displayName: "CPUSEL CMPSS4" },
	{ name: "SYSCTL_CPUSEL_CMPSS5", displayName: "CPUSEL CMPSS5" },
	{ name: "SYSCTL_CPUSEL_CMPSS6", displayName: "CPUSEL CMPSS6" },
	{ name: "SYSCTL_CPUSEL_CMPSS7", displayName: "CPUSEL CMPSS7" },
	{ name: "SYSCTL_CPUSEL_CMPSS8", displayName: "CPUSEL CMPSS8" },
	{ name: "SYSCTL_CPUSEL_CMPSS9", displayName: "CPUSEL CMPSS9" },
	{ name: "SYSCTL_CPUSEL_CMPSS10", displayName: "CPUSEL CMPSS10" },
	{ name: "SYSCTL_CPUSEL_CMPSS11", displayName: "CPUSEL CMPSS11" },
	{ name: "SYSCTL_CPUSEL_DCC0", displayName: "CPUSEL DCC0" },
	{ name: "SYSCTL_CPUSEL_DCC1", displayName: "CPUSEL DCC1" },
	{ name: "SYSCTL_CPUSEL_DCC2", displayName: "CPUSEL DCC2" },
	{ name: "SYSCTL_CPUSEL_DACA", displayName: "CPUSEL DACA" },
	{ name: "SYSCTL_CPUSEL_DACC", displayName: "CPUSEL DACC" },
	{ name: "SYSCTL_CPUSEL_CLB1", displayName: "CPUSEL CLB1" },
	{ name: "SYSCTL_CPUSEL_CLB2", displayName: "CPUSEL CLB2" },
	{ name: "SYSCTL_CPUSEL_CLB3", displayName: "CPUSEL CLB3" },
	{ name: "SYSCTL_CPUSEL_CLB4", displayName: "CPUSEL CLB4" },
	{ name: "SYSCTL_CPUSEL_CLB5", displayName: "CPUSEL CLB5" },
	{ name: "SYSCTL_CPUSEL_CLB6", displayName: "CPUSEL CLB6" },
	{ name: "SYSCTL_CPUSEL_FSITXA", displayName: "CPUSEL FSITXA" },
	{ name: "SYSCTL_CPUSEL_FSITXB", displayName: "CPUSEL FSITXB" },
	{ name: "SYSCTL_CPUSEL_FSIRXA", displayName: "CPUSEL FSIRXA" },
	{ name: "SYSCTL_CPUSEL_FSIRXB", displayName: "CPUSEL FSIRXB" },
	{ name: "SYSCTL_CPUSEL_FSIRXC", displayName: "CPUSEL FSIRXC" },
	{ name: "SYSCTL_CPUSEL_FSIRXD", displayName: "CPUSEL FSIRXD" },
	{ name: "SYSCTL_CPUSEL_LINA", displayName: "CPUSEL LINA" },
	{ name: "SYSCTL_CPUSEL_LINB", displayName: "CPUSEL LINB" },
	{ name: "SYSCTL_CPUSEL_ECAT", displayName: "CPUSEL ECAT" },
	{ name: "SYSCTL_CPUSEL_HRCAL0", displayName: "CPUSEL HRCAL0" },
	{ name: "SYSCTL_CPUSEL_HRCAL1", displayName: "CPUSEL HRCAL1" },
	{ name: "SYSCTL_CPUSEL_HRCAL2", displayName: "CPUSEL HRCAL2" },
	{ name: "SYSCTL_CPUSEL_AESA", displayName: "CPUSEL AESA" },
	{ name: "SYSCTL_CPUSEL_EPG1", displayName: "CPUSEL EPG1" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER1", displayName: "CPUSEL ADCCHECKER1" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER2", displayName: "CPUSEL ADCCHECKER2" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER3", displayName: "CPUSEL ADCCHECKER3" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER4", displayName: "CPUSEL ADCCHECKER4" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER5", displayName: "CPUSEL ADCCHECKER5" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER6", displayName: "CPUSEL ADCCHECKER6" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER7", displayName: "CPUSEL ADCCHECKER7" },
	{ name: "SYSCTL_CPUSEL_ADCCHECKER8", displayName: "CPUSEL ADCCHECKER8" },
]
let SysCtl_CPUSel = [
	{ name: "SYSCTL_CPUSEL_CPU1", displayName: "Connect the peripheral (indicated by SysCtl_CPUSelPeripheral) to CPU1" },
	{ name: "SYSCTL_CPUSEL_CPU2", displayName: "Connect the peripheral (indicated by SysCtl_CPUSelPeripheral) to CPU2" },
]
let SysCtl_FlashBank = [
	{ name: "SYSCTL_FLASH_BANK0", displayName: "FLASH BANK0" },
	{ name: "SYSCTL_FLASH_BANK1", displayName: "FLASH BANK1" },
	{ name: "SYSCTL_FLASH_BANK2", displayName: "FLASH BANK2" },
	{ name: "SYSCTL_FLASH_BANK3", displayName: "FLASH BANK3" },
	{ name: "SYSCTL_FLASH_BANK4", displayName: "FLASH BANK4" },
]
let SysCtl_SharedDxRAM = [
	{ name: "SYSCTL_D2RAM", displayName: "D2RAM" },
	{ name: "SYSCTL_D3RAM", displayName: "D3RAM" },
	{ name: "SYSCTL_D4RAM", displayName: "D4RAM" },
	{ name: "SYSCTL_D5RAM", displayName: "D5RAM" },
]
let SysCtl_WDPredivider = [
	{ name: "SYSCTL_WD_PREDIV_2", displayName: "PREDIVCLK = INTOSC1 / 2" },
	{ name: "SYSCTL_WD_PREDIV_4", displayName: "PREDIVCLK = INTOSC1 / 4" },
	{ name: "SYSCTL_WD_PREDIV_8", displayName: "PREDIVCLK = INTOSC1 / 8" },
	{ name: "SYSCTL_WD_PREDIV_16", displayName: "PREDIVCLK = INTOSC1 / 16" },
	{ name: "SYSCTL_WD_PREDIV_32", displayName: "PREDIVCLK = INTOSC1 / 32" },
	{ name: "SYSCTL_WD_PREDIV_64", displayName: "PREDIVCLK = INTOSC1 / 64" },
	{ name: "SYSCTL_WD_PREDIV_128", displayName: "PREDIVCLK = INTOSC1 / 128" },
	{ name: "SYSCTL_WD_PREDIV_256", displayName: "PREDIVCLK = INTOSC1 / 256" },
	{ name: "SYSCTL_WD_PREDIV_512", displayName: "PREDIVCLK = INTOSC1 / 512" },
	{ name: "SYSCTL_WD_PREDIV_1024", displayName: "PREDIVCLK = INTOSC1 / 1024" },
	{ name: "SYSCTL_WD_PREDIV_2048", displayName: "PREDIVCLK = INTOSC1 / 2048" },
	{ name: "SYSCTL_WD_PREDIV_4096", displayName: "PREDIVCLK = INTOSC1 / 4096" },
]
let SysCtl_WDPrescaler = [
	{ name: "SYSCTL_WD_PRESCALE_1", displayName: "WDCLK = PREDIVCLK / 1" },
	{ name: "SYSCTL_WD_PRESCALE_2", displayName: "WDCLK = PREDIVCLK / 2" },
	{ name: "SYSCTL_WD_PRESCALE_4", displayName: "WDCLK = PREDIVCLK / 4" },
	{ name: "SYSCTL_WD_PRESCALE_8", displayName: "WDCLK = PREDIVCLK / 8" },
	{ name: "SYSCTL_WD_PRESCALE_16", displayName: "WDCLK = PREDIVCLK / 16" },
	{ name: "SYSCTL_WD_PRESCALE_32", displayName: "WDCLK = PREDIVCLK / 32" },
	{ name: "SYSCTL_WD_PRESCALE_64", displayName: "WDCLK = PREDIVCLK / 64" },
]
let SysCtl_WDMode = [
	{ name: "SYSCTL_WD_MODE_RESET", displayName: "Watchdog can generate a reset signal" },
	{ name: "SYSCTL_WD_MODE_INTERRUPT", displayName: "Watchdog can generate an interrupt signal; reset signal is disabled" },
]
let SysCtl_LSPCLKPrescaler = [
	{ name: "SYSCTL_LSPCLK_PRESCALE_1", displayName: "LSPCLK = SYSCLK / 1" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_2", displayName: "LSPCLK = SYSCLK / 2" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_4", displayName: "LSPCLK = SYSCLK / 4 (default)" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_6", displayName: "LSPCLK = SYSCLK / 6" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_8", displayName: "LSPCLK = SYSCLK / 8" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_10", displayName: "LSPCLK = SYSCLK / 10" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_12", displayName: "LSPCLK = SYSCLK / 12" },
	{ name: "SYSCTL_LSPCLK_PRESCALE_14", displayName: "LSPCLK = SYSCLK / 14" },
]
let SysCtl_EPWMCLKDivider = [
	{ name: "SYSCTL_EPWMCLK_DIV_1", displayName: "EPWMCLK = PLLSYSCLK / 1" },
	{ name: "SYSCTL_EPWMCLK_DIV_2", displayName: "EPWMCLK = PLLSYSCLK / 2" },
]
let SysCtl_EMIF1CLKDivider = [
	{ name: "SYSCTL_EMIF1CLK_DIV_1", displayName: "EMIF1CLK = PLLSYSCLK / 1" },
	{ name: "SYSCTL_EMIF1CLK_DIV_2", displayName: "EMIF1CLK = PLLSYSCLK / 2" },
]
let SysCtl_AccessPeripheral = [
	{ name: "SYSCTL_ACCESS_ADCA", displayName: "ADCA access" },
	{ name: "SYSCTL_ACCESS_ADCB", displayName: "ADCB access" },
	{ name: "SYSCTL_ACCESS_ADCC", displayName: "ADCC access" },
	{ name: "SYSCTL_ACCESS_CMPSS1", displayName: "CMPSS1 access" },
	{ name: "SYSCTL_ACCESS_CMPSS2", displayName: "CMPSS2 access" },
	{ name: "SYSCTL_ACCESS_CMPSS3", displayName: "CMPSS3 access" },
	{ name: "SYSCTL_ACCESS_CMPSS4", displayName: "CMPSS4 access" },
	{ name: "SYSCTL_ACCESS_CMPSS5", displayName: "CMPSS5 access" },
	{ name: "SYSCTL_ACCESS_CMPSS6", displayName: "CMPSS6 access" },
	{ name: "SYSCTL_ACCESS_CMPSS7", displayName: "CMPSS7 access" },
	{ name: "SYSCTL_ACCESS_CMPSS8", displayName: "CMPSS8 access" },
	{ name: "SYSCTL_ACCESS_CMPSS9", displayName: "CMPSS9 access" },
	{ name: "SYSCTL_ACCESS_CMPSS10", displayName: "CMPSS10 access" },
	{ name: "SYSCTL_ACCESS_CMPSS11", displayName: "CMPSS11 access" },
	{ name: "SYSCTL_ACCESS_DACA", displayName: "DACA access" },
	{ name: "SYSCTL_ACCESS_DACC", displayName: "DACC access" },
	{ name: "SYSCTL_ACCESS_EPWM1", displayName: "EPWM1 access" },
	{ name: "SYSCTL_ACCESS_EPWM2", displayName: "EPWM2 access" },
	{ name: "SYSCTL_ACCESS_EPWM3", displayName: "EPWM3 access" },
	{ name: "SYSCTL_ACCESS_EPWM4", displayName: "EPWM4 access" },
	{ name: "SYSCTL_ACCESS_EPWM5", displayName: "EPWM5 access" },
	{ name: "SYSCTL_ACCESS_EPWM6", displayName: "EPWM6 access" },
	{ name: "SYSCTL_ACCESS_EPWM7", displayName: "EPWM7 access" },
	{ name: "SYSCTL_ACCESS_EPWM8", displayName: "EPWM8 access" },
	{ name: "SYSCTL_ACCESS_EPWM9", displayName: "EPWM9 access" },
	{ name: "SYSCTL_ACCESS_EPWM10", displayName: "EPWM10 access" },
	{ name: "SYSCTL_ACCESS_EPWM11", displayName: "EPWM11 access" },
	{ name: "SYSCTL_ACCESS_EPWM12", displayName: "EPWM12 access" },
	{ name: "SYSCTL_ACCESS_EPWM13", displayName: "EPWM13 access" },
	{ name: "SYSCTL_ACCESS_EPWM14", displayName: "EPWM14 access" },
	{ name: "SYSCTL_ACCESS_EPWM15", displayName: "EPWM15 access" },
	{ name: "SYSCTL_ACCESS_EPWM16", displayName: "EPWM16 access" },
	{ name: "SYSCTL_ACCESS_EPWM17", displayName: "EPWM17 access" },
	{ name: "SYSCTL_ACCESS_EPWM18", displayName: "EPWM18 access" },
	{ name: "SYSCTL_ACCESS_EQEP1", displayName: "EQEP1 access" },
	{ name: "SYSCTL_ACCESS_EQEP2", displayName: "EQEP2 access" },
	{ name: "SYSCTL_ACCESS_EQEP3", displayName: "EQEP3 access" },
	{ name: "SYSCTL_ACCESS_EQEP4", displayName: "EQEP4 access" },
	{ name: "SYSCTL_ACCESS_EQEP5", displayName: "EQEP5 access" },
	{ name: "SYSCTL_ACCESS_EQEP6", displayName: "EQEP6 access" },
	{ name: "SYSCTL_ACCESS_ECAP1", displayName: "ECAP1 access" },
	{ name: "SYSCTL_ACCESS_ECAP2", displayName: "ECAP2 access" },
	{ name: "SYSCTL_ACCESS_ECAP3", displayName: "ECAP3 access" },
	{ name: "SYSCTL_ACCESS_ECAP4", displayName: "ECAP4 access" },
	{ name: "SYSCTL_ACCESS_ECAP5", displayName: "ECAP5 access" },
	{ name: "SYSCTL_ACCESS_ECAP6", displayName: "ECAP6 access" },
	{ name: "SYSCTL_ACCESS_ECAP7", displayName: "ECAP7 access" },
	{ name: "SYSCTL_ACCESS_SDFM1", displayName: "SDFM1 access" },
	{ name: "SYSCTL_ACCESS_SDFM2", displayName: "SDFM2 access" },
	{ name: "SYSCTL_ACCESS_SDFM3", displayName: "SDFM3 access" },
	{ name: "SYSCTL_ACCESS_SDFM4", displayName: "SDFM4 access" },
	{ name: "SYSCTL_ACCESS_CLB1", displayName: "CLB1 access" },
	{ name: "SYSCTL_ACCESS_CLB2", displayName: "CLB2 access" },
	{ name: "SYSCTL_ACCESS_CLB3", displayName: "CLB3 access" },
	{ name: "SYSCTL_ACCESS_CLB4", displayName: "CLB4 access" },
	{ name: "SYSCTL_ACCESS_CLB5", displayName: "CLB5 access" },
	{ name: "SYSCTL_ACCESS_CLB6", displayName: "CLB6 access" },
	{ name: "SYSCTL_ACCESS_SCIA", displayName: "SCIA access" },
	{ name: "SYSCTL_ACCESS_SCIB", displayName: "SCIB access" },
	{ name: "SYSCTL_ACCESS_SPIA", displayName: "SPIA access" },
	{ name: "SYSCTL_ACCESS_SPIB", displayName: "SPIB access" },
	{ name: "SYSCTL_ACCESS_SPIC", displayName: "SPIC access" },
	{ name: "SYSCTL_ACCESS_SPID", displayName: "SPID access" },
	{ name: "SYSCTL_ACCESS_I2CA", displayName: "I2CA access" },
	{ name: "SYSCTL_ACCESS_I2CB", displayName: "I2CB access" },
	{ name: "SYSCTL_ACCESS_PMBUSA", displayName: "PMBUS_A access" },
	{ name: "SYSCTL_ACCESS_LINA", displayName: "LIN_A access" },
	{ name: "SYSCTL_ACCESS_LINB", displayName: "LIN_B access" },
	{ name: "SYSCTL_ACCESS_CANA", displayName: "DCANA access" },
	{ name: "SYSCTL_ACCESS_MCANA", displayName: "MCANA access" },
	{ name: "SYSCTL_ACCESS_MCANB", displayName: "MCANB access" },
	{ name: "SYSCTL_ACCESS_FSIATX", displayName: "FSIATX access" },
	{ name: "SYSCTL_ACCESS_FSIARX", displayName: "FSIARX access" },
	{ name: "SYSCTL_ACCESS_FSIBTX", displayName: "FSIBTX access" },
	{ name: "SYSCTL_ACCESS_FSIBRX", displayName: "FSIBRX access" },
	{ name: "SYSCTL_ACCESS_FSICRX", displayName: "FSICRX access" },
	{ name: "SYSCTL_ACCESS_FSIDRX", displayName: "FSIDRX access" },
	{ name: "SYSCTL_ACCESS_USBA", displayName: "USBA access" },
	{ name: "SYSCTL_ACCESS_HRPWM0", displayName: "HRPWM0 access" },
	{ name: "SYSCTL_ACCESS_HRPWM1", displayName: "HRPWM1 access" },
	{ name: "SYSCTL_ACCESS_HRPWM2", displayName: "HRPWM2 access" },
	{ name: "SYSCTL_ACCESS_ECAT", displayName: "ETHERCAT access" },
	{ name: "SYSCTL_ACCESS_AESA", displayName: "AESA access" },
	{ name: "SYSCTL_ACCESS_UARTA", displayName: "UARTA access" },
	{ name: "SYSCTL_ACCESS_UARTB", displayName: "UARTB access" },
]
let SysCtl_AccessController = [
	{ name: "SYSCTL_ACCESS_CPUX", displayName: "CPU access to the peripheral" },
	{ name: "SYSCTL_ACCESS_CLA1", displayName: "CLA1 access to the peripheral" },
	{ name: "SYSCTL_ACCESS_DMA1", displayName: "DMA access to the peripheral" },
]
let SysCtl_AccessPermission = [
	{ name: "SYSCTL_ACCESS_FULL", displayName: "Full Access for both read and write." },
	{ name: "SYSCTL_ACCESS_PROTECTED", displayName: "Protected RD access such that FIFOs. Clear on read, registers are not changed and no write access." },
	{ name: "SYSCTL_ACCESS_NONE", displayName: "No read or write access." },
]
let SysCtl_ClockOut = [
	{ name: "SYSCTL_CLOCKOUT_PLLSYS", displayName: "PLL System Clock post SYSCLKDIV" },
	{ name: "SYSCTL_CLOCKOUT_PLLRAW", displayName: "PLL Raw Clock" },
	{ name: "SYSCTL_CLOCKOUT_SYSCLK", displayName: "CPU System Clock" },
	{ name: "SYSCTL_CLOCKOUT_SYSCLK2", displayName: "CPU 2 System Clock" },
	{ name: "SYSCTL_CLOCKOUT_AUXPLLCLK", displayName: "Aux PLL Clock" },
	{ name: "SYSCTL_CLOCKOUT_INTOSC1", displayName: "Internal Oscillator 1" },
	{ name: "SYSCTL_CLOCKOUT_INTOSC2", displayName: "Internal Oscillator 2" },
	{ name: "SYSCTL_CLOCKOUT_XTALOSC", displayName: "External Oscillator" },
]
let SysCtl_ExternalOscMode = [
	{ name: "SYSCTL_XTALMODE_CRYSTAL", displayName: "XTAL Oscillator Crystal Mode" },
	{ name: "SYSCTL_XTALMODE_SINGLE", displayName: "XTAL Oscillator Single-Ended Mode" },
]
let SysCtl_SyncOutputSource = [
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM1SYNCOUT", displayName: "EPWM1SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM2SYNCOUT", displayName: "EPWM2SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM3SYNCOUT", displayName: "EPWM3SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM4SYNCOUT", displayName: "EPWM4SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM5SYNCOUT", displayName: "EPWM5SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM6SYNCOUT", displayName: "EPWM6SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM7SYNCOUT", displayName: "EPWM7SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM8SYNCOUT", displayName: "EPWM8SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM9SYNCOUT", displayName: "EPWM9SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM10SYNCOUT", displayName: "EPWM10SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM11SYNCOUT", displayName: "EPWM11SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM12SYNCOUT", displayName: "EPWM12SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM13SYNCOUT", displayName: "EPWM13SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM14SYNCOUT", displayName: "EPWM14SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM15SYNCOUT", displayName: "EPWM15SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM16SYNCOUT", displayName: "EPWM16SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM17SYNCOUT", displayName: "EPWM15SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_EPWM18SYNCOUT", displayName: "EPWM16SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP1SYNCOUT", displayName: "ECAP1SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP2SYNCOUT", displayName: "ECAP2SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP3SYNCOUT", displayName: "ECAP3SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP4SYNCOUT", displayName: "ECAP4SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP5SYNCOUT", displayName: "ECAP5SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP6SYNCOUT", displayName: "ECAP6SYNCOUT --> EXTSYNCOUT" },
	{ name: "SYSCTL_SYNC_OUT_SRC_ECAP7SYNCOUT", displayName: "ECAP7SYNCOUT --> EXTSYNCOUT" },
]
let SysCtl_DeviceParametric = [
	{ name: "SYSCTL_DEVICE_QUAL", displayName: "Device Qualification Status" },
	{ name: "SYSCTL_DEVICE_PINCOUNT", displayName: "Device Pin Count" },
	{ name: "SYSCTL_DEVICE_FLASH", displayName: "Device Flash size (KB)" },
	{ name: "SYSCTL_DEVICE_FAMILY", displayName: "Device Family" },
	{ name: "SYSCTL_DEVICE_PARTNO", displayName: "Device Part Number" },
	{ name: "SYSCTL_DEVICE_CLASSID", displayName: "Device Class ID" },
]
let SysCtl_DeviceConf = [
	{ name: "SYSCTL_DC_PERCNF_PARTID", displayName: "Allows/Blocks write to Device config registers" },
	{ name: "SYSCTL_BANKSEL", displayName: "Allows/Blocks write to BANKSEL registers" },
]
let SysCtl_CoreReset = [
	{ name: "SYSCTL_CORE_DEACTIVE", displayName: "Core reset is deactivated" },
	{ name: "SYSCTL_CORE_ACTIVE", displayName: "Core is held in reset" },
]
let SysCtl_SelType = [
	{ name: "SYSCTL_USBTYPE", displayName: "Configure USB Type : - Type 0 : Disable Global interrupt feature - TYpe 1 : Enable Global interrupt feature" },
	{ name: "SYSCTL_ECAPTYPE", displayName: "Configure ECAP Type : - Type 0 : No EALLOW protection for ECAP registers - Type 1 : ECAP registers are EALLOW protected" },
	{ name: "SYSCTL_SDFMTYPE", displayName: "Configure SDFM Type : - Type 0 : Data Ready conditions combined with the fault conditions on the interrupt line. Data ready interrupts from individual filters are not generated. - Type 1 : Data Ready conditions do not generate the SDFMINT. Each filter generates a separate data ready interrupts." },
	{ name: "SYSCTL_MEMMAPTYPE", displayName: "Configure MEMMAP Type : - Type 0 : Disables re-mapping SDRAM in lower 64kb of address space - Type 1 : Enables re-mapping SDRAM in lower 64kb of address space." },
]
let SysCtl_XClkDivider = [
	{ name: "SYSCTL_XCLKOUT_DIV_1", displayName: "XCLKOUT =  XCLKOUT / 1" },
	{ name: "SYSCTL_XCLKOUT_DIV_2", displayName: "XCLKOUT =  XCLKOUT / 2" },
	{ name: "SYSCTL_XCLKOUT_DIV_4", displayName: "XCLKOUT =  XCLKOUT / 4" },
	{ name: "SYSCTL_XCLKOUT_DIV_8", displayName: "XCLKOUT =  XCLKOUT / 8" },
]
let SysCtl_ECatClkDivider = [
	{ name: "SYSCTL_ECATCLKOUT_DIV_1", displayName: "ECat clock =  ECat clock / 1" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_2", displayName: "ECat clock =  ECat clock / 2" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_3", displayName: "ECat clock =  ECat clock / 3" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_4", displayName: "ECat clock =  ECat clock / 4" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_5", displayName: "ECat clock =  ECat clock / 5" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_6", displayName: "ECat clock =  ECat clock / 6" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_7", displayName: "ECat clock =  ECat clock / 7" },
	{ name: "SYSCTL_ECATCLKOUT_DIV_8", displayName: "ECat clock =  ECat clock / 8" },
]
let SysCtl_PLLClockSource = [
	{ name: "SYSCTL_SOURCE_AUXPLL", displayName: "Auxillary PLL" },
	{ name: "SYSCTL_SOURCE_SYSPLL", displayName: "System PLL" },
]
let SysCtl_MCANClkDivider = [
	{ name: "SYSCTL_MCANCLK_DIV_1", displayName: "MCAN clock =  MCAN clock / 1" },
	{ name: "SYSCTL_MCANCLK_DIV_2", displayName: "MCAN clock =  MCAN clock / 2" },
	{ name: "SYSCTL_MCANCLK_DIV_3", displayName: "MCAN clock =  MCAN clock / 3" },
	{ name: "SYSCTL_MCANCLK_DIV_4", displayName: "MCAN clock =  MCAN clock / 4" },
	{ name: "SYSCTL_MCANCLK_DIV_5", displayName: "MCAN clock =  MCAN clock / 5" },
	{ name: "SYSCTL_MCANCLK_DIV_6", displayName: "MCAN clock =  MCAN clock / 6" },
	{ name: "SYSCTL_MCANCLK_DIV_7", displayName: "MCAN clock =  MCAN clock / 7" },
	{ name: "SYSCTL_MCANCLK_DIV_8", displayName: "MCAN clock =  MCAN clock / 8" },
	{ name: "SYSCTL_MCANCLK_DIV_9", displayName: "MCAN clock =  MCAN clock / 9" },
	{ name: "SYSCTL_MCANCLK_DIV_10", displayName: "MCAN clock =  MCAN clock / 10" },
	{ name: "SYSCTL_MCANCLK_DIV_11", displayName: "MCAN clock =  MCAN clock / 11" },
	{ name: "SYSCTL_MCANCLK_DIV_12", displayName: "MCAN clock =  MCAN clock / 12" },
	{ name: "SYSCTL_MCANCLK_DIV_13", displayName: "MCAN clock =  MCAN clock / 13" },
	{ name: "SYSCTL_MCANCLK_DIV_14", displayName: "MCAN clock =  MCAN clock / 14" },
	{ name: "SYSCTL_MCANCLK_DIV_15", displayName: "MCAN clock =  MCAN clock / 15" },
	{ name: "SYSCTL_MCANCLK_DIV_16", displayName: "MCAN clock =  MCAN clock / 16" },
	{ name: "SYSCTL_MCANCLK_DIV_17", displayName: "MCAN clock =  MCAN clock / 17" },
	{ name: "SYSCTL_MCANCLK_DIV_18", displayName: "MCAN clock =  MCAN clock / 18" },
	{ name: "SYSCTL_MCANCLK_DIV_19", displayName: "MCAN clock =  MCAN clock / 19" },
	{ name: "SYSCTL_MCANCLK_DIV_20", displayName: "MCAN clock =  MCAN clock / 20" },
]
let SysCtl_MCANInstance = [
	{ name: "SYSCTL_MCANA", displayName: "MCANA" },
	{ name: "SYSCTL_MCANB", displayName: "MCANB" },
]
let SysCtl_AuxPLLClkDivider = [
	{ name: "SYSCTL_AUXPLLCLK_DIV_1", displayName: "AUXPLL clock =  AUXPLL clock / 1" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_2", displayName: "AUXPLL clock =  AUXPLL clock / 2" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_4", displayName: "AUXPLL clock =  AUXPLL clock / 4" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_8", displayName: "AUXPLL clock =  AUXPLL clock / 8" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_3", displayName: "AUXPLL clock =  AUXPLL clock / 3" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_5", displayName: "AUXPLL clock =  AUXPLL clock / 5" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_6", displayName: "AUXPLL clock =  AUXPLL clock / 6" },
	{ name: "SYSCTL_AUXPLLCLK_DIV_7", displayName: "AUXPLL clock =  AUXPLL clock / 7" },
]
let SysCtl_Cputimer2ClkDivider = [
	{ name: "SYSCTL_TMR2CLKPRESCALE_1", displayName: "Cputimer2 clock =  Cputimer2 clock / 1" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_2", displayName: "Cputimer2 clock =  Cputimer2 clock / 2" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_4", displayName: "Cputimer2 clock =  Cputimer2 clock / 4" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_8", displayName: "Cputimer2 clock =  Cputimer2 clock / 8" },
	{ name: "SYSCTL_TMR2CLKPRESCALE_16", displayName: "Cputimer2 clock =  Cputimer2 clock / 16" },
]
let SysCtl_Cputimer2ClkSource = [
	{ name: "SYSCTL_TMR2CLKSRCSEL_SYSCLK", displayName: "System Clock" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_INTOSC1", displayName: "Internal Oscillator 1" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_INTOSC2", displayName: "Internal Oscillator 2" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_XTAL", displayName: "Crystal oscillator" },
	{ name: "SYSCTL_TMR2CLKSRCSEL_AUXPLLCLK", displayName: "Aux PLL CLock" },
]
let SysCtl_ClkRegSel = [
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL1", displayName: "CLKSRCCTL1 lock" },
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL2", displayName: "CLKSRCCTL2 lock" },
	{ name: "SYSCTL_REG_SEL_CLKSRCCTL3", displayName: "CLKSRCCTL3 lock" },
	{ name: "SYSCTL_REG_SEL_SYSPLLCTL1", displayName: "SYSPLLCTL1 lock" },
	{ name: "SYSCTL_REG_SEL_SYSPLLMULT", displayName: "SYSPLLMULT lock" },
	{ name: "SYSCTL_REG_SEL_AUXPLLCTL1", displayName: "AUXPLLCTL1 lock" },
	{ name: "SYSCTL_REG_SEL_AUXPLLMULT", displayName: "AUXPLLMULT lock" },
	{ name: "SYSCTL_REG_SEL_SYSCLKDIVSEL", displayName: "SYSCLKDIVSEL lock" },
	{ name: "SYSCTL_REG_SEL_AUXCLKDIVSEL", displayName: "AUXCLKDIVSEL lock" },
	{ name: "SYSCTL_REG_SEL_PERCLKDIVSEL", displayName: "PERCLKDIVSEL lock" },
	{ name: "SYSCTL_REG_SEL_CLBCLKCTL", displayName: "CLBCLKCTL lock" },
	{ name: "SYSCTL_REG_SEL_LOSPCP", displayName: "LOSPCP lock" },
	{ name: "SYSCTL_REG_SEL_XTALCR", displayName: "XTALCR lock" },
	{ name: "SYSCTL_REG_SEL_EXTRFLTDET", displayName: "EXTRFLTDET lock" },
	{ name: "SYSCTL_REG_SEL_ETHERCATCLKCTL", displayName: "ETHERCATCLKCTL lock" },
]
let SysCtl_CpuRegSel = [
	{ name: "SYSCTL_REG_SEL_PIEVERRADDR", displayName: "PIEVERRADDR lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR0", displayName: "PCLKCR0 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR1", displayName: "PCLKCR1 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR2", displayName: "PCLKCR2 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR3", displayName: "PCLKCR3 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR4", displayName: "PCLKCR4 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR6", displayName: "PCLKCR6 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR7", displayName: "PCLKCR7 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR8", displayName: "PCLKCR8 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR9", displayName: "PCLKCR9 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR10", displayName: "PCLKCR10 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR11", displayName: "PCLKCR11 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR13", displayName: "PCLKCR13 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR14", displayName: "PCLKCR14 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR16", displayName: "PCLKCR16 lock" },
	{ name: "SYSCTL_REG_SEL_LPMCR", displayName: "LPMCR lock" },
	{ name: "SYSCTL_REG_SEL_GPIOLPMSEL0", displayName: "GPIOLPMSEL0 lock" },
	{ name: "SYSCTL_REG_SEL_GPIOLPMSEL1", displayName: "GPIOLPMSEL1 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR17", displayName: "PCLKCR17 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR18", displayName: "PCLKCR18 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR19", displayName: "PCLKCR19 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR21", displayName: "PCLKCR21 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR22", displayName: "PCLKCR22 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR23", displayName: "PCLKCR23 lock" },
	{ name: "SYSCTL_REG_SEL_ETHERCATCTL", displayName: "ETHERCATCTL lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR25", displayName: "PCLKCR25 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR26", displayName: "PCLKCR26 lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR27", displayName: "PCLKCR27 lock" },
	{ name: "SYSCTL_REG_SEL_LSEN", displayName: "LSEN lock" },
	{ name: "SYSCTL_REG_SEL_CMPSSLPMSEL", displayName: "CMPSSLPMSEL lock" },
	{ name: "SYSCTL_REG_SEL_PCLKCR28", displayName: "PCLKCR28 lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG1_SYSRSN", displayName: "USER_REG1_SYSRSN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG2_SYSRSN", displayName: "USER_REG2_SYSRSN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG1_XRSN", displayName: "USER_REG1_XRSN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG2_XRSN", displayName: "USER_REG2_XRSN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG1_PORESETN", displayName: "USER_REG1_PORESETN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG2_PORESETN", displayName: "USER_REG2_PORESETN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG3_PORESETN", displayName: "USER_REG3_PORESETN lock" },
	{ name: "SYSCTL_REG_SEL_USER_REG4_PORESETN", displayName: "USER_REG4_PORESETN lock" },
]
let SysCtl_CLBClkDivider = [
	{ name: "SYSCTL_CLBCLKOUT_DIV_1", displayName: "CLB clock =  CLB clock / 1" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_2", displayName: "CLB clock =  CLB clock / 2" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_3", displayName: "CLB clock =  CLB clock / 3" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_4", displayName: "CLB clock =  CLB clock / 4" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_5", displayName: "CLB clock =  CLB clock / 5" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_6", displayName: "CLB clock =  CLB clock / 6" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_7", displayName: "CLB clock =  CLB clock / 7" },
	{ name: "SYSCTL_CLBCLKOUT_DIV_8", displayName: "CLB clock =  CLB clock / 8" },
]
let SysCtl_CLBTClkDivider = [
	{ name: "SYSCTL_CLBTCLKOUT_DIV_1", displayName: "CLBTCLKOUT =  CLB clock / 1" },
	{ name: "SYSCTL_CLBTCLKOUT_DIV_2", displayName: "CLBTCLKOUT =  CLB clock / 2" },
]
let SysCtl_CLBInst = [
	{ name: "SYSCTL_CLB1", displayName: "CLB 1 instance" },
	{ name: "SYSCTL_CLB2", displayName: "CLB 2 instance" },
	{ name: "SYSCTL_CLB3", displayName: "CLB 3 instance" },
	{ name: "SYSCTL_CLB4", displayName: "CLB 4 instance" },
	{ name: "SYSCTL_CLB5", displayName: "CLB 5 instance" },
	{ name: "SYSCTL_CLB6", displayName: "CLB 6 instance" },
]
let SysCtl_CLBClkm = [
	{ name: "SYSCTL_CLBCLK_SYNC", displayName: "CLB is synchronous to SYSCLK" },
	{ name: "SYSCTL_CLBCLK_ASYNC", displayName: "CLB runs of asynchronous clock" },
]
let SysCtl_UserRegister = [
	{ name: "SYSCTL_USER_REG1_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_USER_REG2_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_USER_REG1_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_USER_REG2_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_USER_REG1_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG2_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG3_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_USER_REG4_PORESETN", displayName: "User register reset by PORESETn" },
]
let SysCtl_LFUUserRegister = [
	{ name: "SYSCTL_LFU_USER_REG1_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_LFU_USER_REG2_SYSRSN", displayName: "User register reset by SYSRSn" },
	{ name: "SYSCTL_LFU_USER_REG1_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_LFU_USER_REG2_XRSN", displayName: "User register reset by XRSn" },
	{ name: "SYSCTL_LFU_USER_REG1_PORESETN", displayName: "User register reset by PORESETn" },
	{ name: "SYSCTL_LFU_USER_REG2_PORESETN", displayName: "User register reset by PORESETn" },
]
let SysCtl_DevicePartNumber = [
	{ name: "SYSCTL_EMULATE_F28P650DK9", displayName: "EMULATE F28P650DK9" },
	{ name: "SYSCTL_EMULATE_F28P650DK7", displayName: "EMULATE F28P650DK7" },
	{ name: "SYSCTL_EMULATE_F28P650DK8", displayName: "EMULATE F28P650DK8" },
	{ name: "SYSCTL_EMULATE_F28P650SK7", displayName: "EMULATE F28P650SK7" },
	{ name: "SYSCTL_EMULATE_F28P659DK8", displayName: "EMULATE F28P659DK8" },
	{ name: "SYSCTL_EMULATE_F28P650DK6", displayName: "EMULATE F28P650DK6" },
	{ name: "SYSCTL_EMULATE_F28P650SK6", displayName: "EMULATE F28P650SK6" },
	{ name: "SYSCTL_EMULATE_F28P659DH8", displayName: "EMULATE F28P659DH8" },
	{ name: "SYSCTL_EMULATE_F28P659SH6", displayName: "EMULATE F28P659SH6" },
	{ name: "SYSCTL_EMULATE_F28P650DH6", displayName: "EMULATE F28P650DH6" },
	{ name: "SYSCTL_EMULATE_F28P650SH6", displayName: "EMULATE F28P650SH6" },
]
let SYSCTL_AUXPLL = [
	{ name: "SYSCTL_AUXPLL_DIV_1", displayName: "Auxiliary PLL divide by 1" },
	{ name: "SYSCTL_AUXPLL_DIV_2", displayName: "Auxiliary PLL divide by 2" },
	{ name: "SYSCTL_AUXPLL_DIV_4", displayName: "Auxiliary PLL divide by 4" },
	{ name: "SYSCTL_AUXPLL_DIV_8", displayName: "Auxiliary PLL divide by 8" },
	{ name: "SYSCTL_AUXPLL_DIV_3", displayName: "Auxiliary PLL divide by 3" },
	{ name: "SYSCTL_AUXPLL_DIV_5", displayName: "Auxiliary PLL divide by 5" },
	{ name: "SYSCTL_AUXPLL_DIV_6", displayName: "Auxiliary PLL divide by 6" },
	{ name: "SYSCTL_AUXPLL_DIV_7", displayName: "Auxiliary PLL divide by 7" },
	{ name: "SYSCTL_AUXPLL_REFDIV(x)", displayName: "Macro to format Clock divider value. x is a number from 1 to 32." },
	{ name: "SYSCTL_AUXPLL_ODIV(x)", displayName: "Macro to format Clock divider value. x is a number from 1 to 32." },
	{ name: "SYSCTL_AUXPLL_IMULT(x)", displayName: "Macro to format integer multiplier value. x is a number from 1 to 127." },
	{ name: "SYSCTL_AUXPLL_FMULT_NONE", displayName: "No fractional multiplier" },
	{ name: "SYSCTL_AUXPLL_FMULT_0", displayName: "No fractional multiplier" },
	{ name: "SYSCTL_AUXPLL_FMULT_1_4", displayName: "Fractional multiplier - 0.25" },
	{ name: "SYSCTL_AUXPLL_FMULT_1_2", displayName: "Fractional multiplier - 0.50" },
	{ name: "SYSCTL_AUXPLL_FMULT_3_4", displayName: "Fractional multiplier - 0.75" },
	{ name: "SYSCTL_AUXPLL_OSCSRC_OSC2", displayName: "Internal oscillator INTOSC2 as auxiliary clock input" },
	{ name: "SYSCTL_AUXPLL_OSCSRC_XTAL", displayName: "External oscillator (XTAL) as auxiliary clock input" },
	{ name: "SYSCTL_AUXPLL_OSCSRC_AUXCLKIN", displayName: "AUXCLKIN (from GPIO) as auxiliary clock input" },
	{ name: "SYSCTL_AUXPLL_OSCSRC_XTAL_SE", displayName: "External oscillator (XTAL) in single-ended mode" },
	{ name: "SYSCTL_AUXPLL_ENABLE", displayName: "Enable AUXPLL" },
	{ name: "SYSCTL_AUXPLL_DISABLE", displayName: "Disable AUXPLL" },
	{ name: "SYSCTL_AUXPLL_BYPASS", displayName: "Bypass AUXPLL" },
]
let SYSCTL_NMI = [
	{ name: "SYSCTL_NMI_NMIINT", displayName: "NMI Interrupt Flag" },
	{ name: "SYSCTL_NMI_CLOCKFAIL", displayName: "Clock Fail Interrupt Flag" },
	{ name: "SYSCTL_NMI_UNCERR", displayName: "Flash/RAM/ROM Uncorrectable Error NMI Flag" },
	{ name: "SYSCTL_NMI_REGPARITYERR", displayName: "Register parity error" },
	{ name: "SYSCTL_NMI_CPU1HWBISTERR", displayName: "HW BIST Error NMI Flag" },
	{ name: "SYSCTL_NMI_PIEVECTERR", displayName: "PIE Vector Fetch Error Flag" },
	{ name: "SYSCTL_NMI_SYSDBGNMI", displayName: "System Debug Module NMI Flag" },
	{ name: "SYSCTL_NMI_RLNMI", displayName: "Reconfigurable Logic NMI Flag" },
	{ name: "SYSCTL_NMI_CPU2WDRSN", displayName: "CPU2 WDRSn Reset Indication Flag" },
	{ name: "SYSCTL_NMI_CPU2NMIWDRSN", displayName: "CPU2 NMIWDRSn Reset Indication Flag" },
	{ name: "SYSCTL_NMI_LSCMPERR", displayName: "Lockstep Compare Error" },
	{ name: "SYSCTL_NMI_ECATNMIN", displayName: "EtherCAT NMI Flag" },
	{ name: "SYSCTL_NMI_CRC_FAIL", displayName: "BGCRC calculation failed." },
	{ name: "SYSCTL_NMI_SWERR", displayName: "SW Error Force NMI Flag" },
]
let SYSCTL_STATUS_SYS_ERR = [
	{ name: "SYSCTL_STATUS_GINT", displayName: "Global Interrupt flag" },
	{ name: "SYSCTL_STATUS_EMIF_ERR", displayName: "EMIF error event flag" },
	{ name: "SYSCTL_STATUS_CORRECTABLE_ERR", displayName: "RAM/Flash correctable error flag" },
	{ name: "SYSCTL_STATUS_RAM_ACC_VIOL", displayName: "A RAM access vioation flag." },
	{ name: "SYSCTL_STATUS_SYS_PLL_SLIP", displayName: "System PLL Slip event flag." },
	{ name: "SYSCTL_STATUS_AUX_PLL_SLIP", displayName: "Auxillary PLL Slip event flag." },
	{ name: "SYSCTL_STATUS_DCC0", displayName: "DCC0 Interrupt flag." },
	{ name: "SYSCTL_STATUS_DCC1", displayName: "DCC1 Interrupt flag." },
	{ name: "SYSCTL_STATUS_DCC2", displayName: "DCC2 Interrupt flag." },
	{ name: "SYSCTL_STATUS_AES_BUS_ERROR", displayName: "AES_BUS_ERROR Interrupt flag." },
	{ name: "SYSCTL_STATUS_EPG1_INT", displayName: "EPG1_INT Interrupt flag." },
]
let SYSCTL_CAUSE = [
	{ name: "SYSCTL_CAUSE_POR", displayName: "Power-on reset" },
	{ name: "SYSCTL_CAUSE_XRS", displayName: "External reset pin" },
	{ name: "SYSCTL_CAUSE_WDRS", displayName: "Watchdog reset" },
	{ name: "SYSCTL_CAUSE_NMIWDRS", displayName: "NMI watchdog reset" },
	{ name: "SYSCTL_CAUSE_SCCRESET", displayName: "SCCRESETn by DCSM" },
	{ name: "SYSCTL_CAUSE_HWBISTN", displayName: "HWBISTn Reset" },
	{ name: "SYSCTL_CAUSE_ECAT_RESET_OUT", displayName: "ECAT_RESET_OUT Reset" },
	{ name: "SYSCTL_CAUSE_SIMRESET_CPU1RSN", displayName: "SIMRESET_CPU1RSn" },
	{ name: "SYSCTL_CAUSE_SIMRESET_XRSN", displayName: "SIMRESET_XRSn" },
]
let SYSCTL_ADCSOC_SRC = [
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCA", displayName: "ePWM1 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM2SOCA", displayName: "ePWM2 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCA", displayName: "ePWM3 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM4SOCA", displayName: "ePWM4 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM5SOCA", displayName: "ePWM5 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM6SOCA", displayName: "ePWM6 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM7SOCA", displayName: "ePWM7 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM8SOCA", displayName: "ePWM8 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM9SOCA", displayName: "ePWM9 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM10SOCA", displayName: "ePWM10 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM11SOCA", displayName: "ePWM11 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM12SOCA", displayName: "ePWM12 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM13SOCA", displayName: "ePWM13 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM14SOCA", displayName: "ePWM14 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM15SOCA", displayName: "ePWM15 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM16SOCA", displayName: "ePWM16 SOCA for ADCSOCAO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM1SOCB", displayName: "ePWM1 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM2SOCB", displayName: "ePWM2 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM3SOCB", displayName: "ePWM3 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM4SOCB", displayName: "ePWM4 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM5SOCB", displayName: "ePWM5 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM6SOCB", displayName: "ePWM6 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM7SOCB", displayName: "ePWM7 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM8SOCB", displayName: "ePWM8 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM9SOCB", displayName: "ePWM9 SOCB for ADCSOCBO" },
	{ name: "SYSCTL_ADCSOC_SRC_PWM13SOCB", displayName: "ePWM13 SOCB for ADCSOCBO" },
]
module.exports = {
	SysCtl_PeripheralPCLOCKCR: SysCtl_PeripheralPCLOCKCR,
	SysCtl_PeripheralSOFTPRES: SysCtl_PeripheralSOFTPRES,
	SysCtl_CPUSelPeripheral: SysCtl_CPUSelPeripheral,
	SysCtl_CPUSelPeriphInstance: SysCtl_CPUSelPeriphInstance,
	SysCtl_CPUSel: SysCtl_CPUSel,
	SysCtl_FlashBank: SysCtl_FlashBank,
	SysCtl_SharedDxRAM: SysCtl_SharedDxRAM,
	SysCtl_WDPredivider: SysCtl_WDPredivider,
	SysCtl_WDPrescaler: SysCtl_WDPrescaler,
	SysCtl_WDMode: SysCtl_WDMode,
	SysCtl_LSPCLKPrescaler: SysCtl_LSPCLKPrescaler,
	SysCtl_EPWMCLKDivider: SysCtl_EPWMCLKDivider,
	SysCtl_EMIF1CLKDivider: SysCtl_EMIF1CLKDivider,
	SysCtl_AccessPeripheral: SysCtl_AccessPeripheral,
	SysCtl_AccessController: SysCtl_AccessController,
	SysCtl_AccessPermission: SysCtl_AccessPermission,
	SysCtl_ClockOut: SysCtl_ClockOut,
	SysCtl_ExternalOscMode: SysCtl_ExternalOscMode,
	SysCtl_SyncOutputSource: SysCtl_SyncOutputSource,
	SysCtl_DeviceParametric: SysCtl_DeviceParametric,
	SysCtl_DeviceConf: SysCtl_DeviceConf,
	SysCtl_CoreReset: SysCtl_CoreReset,
	SysCtl_SelType: SysCtl_SelType,
	SysCtl_XClkDivider: SysCtl_XClkDivider,
	SysCtl_ECatClkDivider: SysCtl_ECatClkDivider,
	SysCtl_PLLClockSource: SysCtl_PLLClockSource,
	SysCtl_MCANClkDivider: SysCtl_MCANClkDivider,
	SysCtl_MCANInstance: SysCtl_MCANInstance,
	SysCtl_AuxPLLClkDivider: SysCtl_AuxPLLClkDivider,
	SysCtl_Cputimer2ClkDivider: SysCtl_Cputimer2ClkDivider,
	SysCtl_Cputimer2ClkSource: SysCtl_Cputimer2ClkSource,
	SysCtl_ClkRegSel: SysCtl_ClkRegSel,
	SysCtl_CpuRegSel: SysCtl_CpuRegSel,
	SysCtl_CLBClkDivider: SysCtl_CLBClkDivider,
	SysCtl_CLBTClkDivider: SysCtl_CLBTClkDivider,
	SysCtl_CLBInst: SysCtl_CLBInst,
	SysCtl_CLBClkm: SysCtl_CLBClkm,
	SysCtl_UserRegister: SysCtl_UserRegister,
	SysCtl_LFUUserRegister: SysCtl_LFUUserRegister,
	SysCtl_DevicePartNumber: SysCtl_DevicePartNumber,
	SYSCTL_AUXPLL: SYSCTL_AUXPLL,
	SYSCTL_NMI: SYSCTL_NMI,
	SYSCTL_STATUS_SYS_ERR: SYSCTL_STATUS_SYS_ERR,
	SYSCTL_CAUSE: SYSCTL_CAUSE,
	SYSCTL_ADCSOC_SRC: SYSCTL_ADCSOC_SRC,
}
