let XBAR_MUXES = [
	{ name: "XBAR_MUX00", displayName:"MUX 00" },
	{ name: "XBAR_MUX01", displayName:"MUX 01" },
	{ name: "XBAR_MUX02", displayName:"MUX 02" },
	{ name: "XBAR_MUX03", displayName:"MUX 03" },
	{ name: "XBAR_MUX04", displayName:"MUX 04" },
	{ name: "XBAR_MUX05", displayName:"MUX 05" },
	{ name: "XBAR_MUX06", displayName:"MUX 06" },
	{ name: "XBAR_MUX07", displayName:"MUX 07" },
	{ name: "XBAR_MUX08", displayName:"MUX 08" },
	{ name: "XBAR_MUX09", displayName:"MUX 09" },
	{ name: "XBAR_MUX10", displayName:"MUX 10" },
	{ name: "XBAR_MUX11", displayName:"MUX 11" },
	{ name: "XBAR_MUX12", displayName:"MUX 12" },
	{ name: "XBAR_MUX13", displayName:"MUX 13" },
	{ name: "XBAR_MUX14", displayName:"MUX 14" },
	{ name: "XBAR_MUX15", displayName:"MUX 15" },
	{ name: "XBAR_MUX16", displayName:"MUX 16" },
	{ name: "XBAR_MUX17", displayName:"MUX 17" },
	{ name: "XBAR_MUX18", displayName:"MUX 18" },
	{ name: "XBAR_MUX19", displayName:"MUX 19" },
	{ name: "XBAR_MUX20", displayName:"MUX 20" },
	{ name: "XBAR_MUX21", displayName:"MUX 21" },
	{ name: "XBAR_MUX22", displayName:"MUX 22" },
	{ name: "XBAR_MUX23", displayName:"MUX 23" },
	{ name: "XBAR_MUX24", displayName:"MUX 24" },
	{ name: "XBAR_MUX25", displayName:"MUX 25" },
	{ name: "XBAR_MUX26", displayName:"MUX 26" },
	{ name: "XBAR_MUX27", displayName:"MUX 27" },
	{ name: "XBAR_MUX28", displayName:"MUX 28" },
	{ name: "XBAR_MUX29", displayName:"MUX 29" },
	{ name: "XBAR_MUX30", displayName:"MUX 30" },
	{ name: "XBAR_MUX31", displayName:"MUX 31" },
]
let XBAR_OutputNum = [
	{ name: "XBAR_OUTPUT1", displayName: "OUTPUT1 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT2", displayName: "OUTPUT2 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT3", displayName: "OUTPUT3 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT4", displayName: "OUTPUT4 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT5", displayName: "OUTPUT5 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT6", displayName: "OUTPUT6 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT7", displayName: "OUTPUT7 of the Output X-BAR" },
	{ name: "XBAR_OUTPUT8", displayName: "OUTPUT8 of the Output X-BAR" },
]
let XBAR_TripNum = [
	{ name: "XBAR_TRIP4", displayName: "TRIP4 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP5", displayName: "TRIP5 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP7", displayName: "TRIP7 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP8", displayName: "TRIP8 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP9", displayName: "TRIP9 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP10", displayName: "TRIP10 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP11", displayName: "TRIP11 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP12", displayName: "TRIP12 of the ePWM X-BAR" },
]
let XBAR_AuxSigNum = [
	{ name: "XBAR_AUXSIG0", displayName: "AUXSIG0" },
	{ name: "XBAR_AUXSIG1", displayName: "AUXSIG1" },
	{ name: "XBAR_AUXSIG2", displayName: "AUXSIG2" },
	{ name: "XBAR_AUXSIG3", displayName: "AUXSIG3" },
	{ name: "XBAR_AUXSIG4", displayName: "AUXSIG4" },
	{ name: "XBAR_AUXSIG5", displayName: "AUXSIG5" },
	{ name: "XBAR_AUXSIG6", displayName: "AUXSIG6" },
	{ name: "XBAR_AUXSIG7", displayName: "AUXSIG7" },
]
let XBAR_InputNum = [
	{ name: "XBAR_INPUT1", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, EPWM TRIP[TZ1, TRIP1], ERAD" },
	{ name: "XBAR_INPUT2", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, CMPSS[CMPSS2/4. EXT_FILTIN_L]" },
	{ name: "XBAR_INPUT3", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, DCCx[CLK1]" },
	{ name: "XBAR_INPUT4", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, DCCx[CLK1]" },
	{ name: "XBAR_INPUT5", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, CPU XINT[XINT4], EPG[EPGAIN1]" },
	{ name: "XBAR_INPUT6", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, CPU XINT[XINT5], EPG[EPGAIN2]" },
	{ name: "XBAR_INPUT7", displayName: "ECAP, ERAD, DCCx[CLK1], EPG[EPGAIN3]" },
	{ name: "XBAR_INPUT8", displayName: "ECAP, ERAD, DCCx[CLK0], EPG[EPGAIN4]" },
	{ name: "XBAR_INPUT9", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, EPWM TRIP[TZ2, TRIP2], ERAD" },
	{ name: "XBAR_INPUT10", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, EPWM TRIP[TZ3, TRIP3], ERAD" },
	{ name: "XBAR_INPUT11", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, ERAD, CPU XINT[XINT1]" },
	{ name: "XBAR_INPUT12", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, ERAD, CPU XINT[XINT2], ADC SOC[ADCEXTSOC], EPWM / ECAP SYNC[EXTSYNCIN1]" },
	{ name: "XBAR_INPUT13", displayName: "ECAP, X-BARs, CLB XBAR, OUTPUT XBAR, EPWM TRIP[TRIP6], ERAD, CPU XINT[XINT3], EPWM / ECAP SYNC[EXTSYNCIN2]" },
	{ name: "XBAR_INPUT14", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, CMPSS[CMPSS1/3. EXT_FILTIN_H]" },
	{ name: "XBAR_INPUT15", displayName: "ECAP, X-BARs, CLB XBAR, ERAD, CMPSS[CMPSS1/3. EXT_FILTIN_L]" },
	{ name: "XBAR_INPUT16", displayName: "ECAP, X-BARs, CLB XBAR, ERAD CMPSS[CMPSS2/4. EXT_FILTIN_H]" },
]
let XBAR_OutputMuxConfig = [
	{ name: "XBAR_OUT_MUX00_CMPSS1_CTRIPOUTH", displayName: "CMPSS1 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX00_CMPSS1_CTRIPOUTH_OR_L", displayName: "CMPSS1 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_OUT_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_OUT_MUX01_CMPSS1_CTRIPOUTL", displayName: "CMPSS1 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX01_INPUTXBAR1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_OUT_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_OUT_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_OUT_MUX02_CMPSS2_CTRIPOUTH", displayName: "CMPSS2 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX02_CMPSS2_CTRIPOUTH_OR_L", displayName: "CMPSS2 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_OUT_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_OUT_MUX03_CMPSS2_CTRIPOUTL", displayName: "CMPSS2 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX03_INPUTXBAR2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_OUT_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_OUT_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_OUT_MUX04_CMPSS3_CTRIPOUTH", displayName: "CMPSS3 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX04_CMPSS3_CTRIPOUTH_OR_L", displayName: "CMPSS3 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_OUT_MUX05_CMPSS3_CTRIPOUTL", displayName: "CMPSS3 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX05_INPUTXBAR3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_OUT_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_OUT_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_OUT_MUX06_CMPSS4_CTRIPOUTH", displayName: "CMPSS4 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX06_CMPSS4_CTRIPOUTH_OR_L", displayName: "CMPSS4 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_OUT_MUX07_CMPSS4_CTRIPOUTL", displayName: "CMPSS4 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX07_INPUTXBAR4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_OUT_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_OUT_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_OUT_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_OUT_MUX09_INPUTXBAR5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_OUT_MUX09_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_OUT_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_OUT_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_OUT_MUX11_INPUTXBAR6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_OUT_MUX11_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_OUT_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_OUT_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_OUT_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_OUT_MUX13_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_OUT_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_OUT_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_OUT_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_OUT_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_OUT_MUX15_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_OUT_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_OUT_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_OUT_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX16_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_OUT_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_OUT_MUX17_CLAHALT", displayName: "CLAHALT" },
	{ name: "XBAR_OUT_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_OUT_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX18_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_OUT_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_OUT_MUX19_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_OUT_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_OUT_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX20_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_OUT_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_OUT_MUX21_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX21_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_OUT_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_OUT_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX22_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_OUT_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_OUT_MUX23_ADCA_EXTMUXSEL0", displayName: "ADCA EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX23_ADCC_EXTMUXSEL0", displayName: "ADCC EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX23_ADCE_EXTMUXSEL0", displayName: "ADCE EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_OUT_MUX24_ADCA_EXTMUXSEL1", displayName: "ADCA EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX24_ADCC_EXTMUXSEL1", displayName: "ADCC EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX24_ADCE_EXTMUXSEL1", displayName: "ADCE EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_OUT_MUX25_ADCA_EXTMUXSEL2", displayName: "ADCA EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX25_ADCC_EXTMUXSEL2", displayName: "ADCC EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX25_ADCE_EXTMUXSEL2", displayName: "ADCE EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_OUT_MUX26_ADCA_EXTMUXSEL3", displayName: "ADCA EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX26_ADCC_EXTMUXSEL3", displayName: "ADCC EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX26_ADCE_EXTMUXSEL3", displayName: "ADCE EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_OUT_MUX27_ADCB_EXTMUXSEL0", displayName: "ADCB EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX27_ADCD_EXTMUXSEL0", displayName: "ADCD EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX27_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_OUT_MUX28_ADCB_EXTMUXSEL1", displayName: "ADCB EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX28_ADCD_EXTMUXSEL1", displayName: "ADCD EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_OUT_MUX29_ADCB_EXTMUXSEL2", displayName: "ADCB EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX29_ADCD_EXTMUXSEL2", displayName: "ADCD EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_OUT_MUX30_ADCB_EXTMUXSEL3", displayName: "ADCB EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX30_ADCD_EXTMUXSEL3", displayName: "ADCD EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX30_EPG1_OUT0", displayName: "EPG1OUT0" },
	{ name: "XBAR_OUT_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_OUT_MUX31_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_OUT_MUX31_EPG1_OUT1", displayName: "EPG1 OUT1" },
	{ name: "XBAR_OUT_MUX00_CLB1_OUT0", displayName: "CLB1 OUT0" },
	{ name: "XBAR_OUT_MUX00_XTRIP_OUT1", displayName: "OUTPUTXBAR1" },
	{ name: "XBAR_OUT_MUX01_CLB1_OUT1", displayName: "CLB1 OUT1" },
	{ name: "XBAR_OUT_MUX01_XTRIP_OUT2", displayName: "OUTPUTXBAR2" },
	{ name: "XBAR_OUT_MUX02_CLB1_OUT2", displayName: "CLB1 OUT2" },
	{ name: "XBAR_OUT_MUX03_CLB1_OUT3", displayName: "CLB1 OUT3" },
	{ name: "XBAR_OUT_MUX04_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_OUT_MUX05_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_OUT_MUX06_CLB1_OUT6", displayName: "CLB1 OUT6" },
	{ name: "XBAR_OUT_MUX07_CLB1_OUT7", displayName: "CLB1 OUT7" },
	{ name: "XBAR_OUT_MUX08_CLB2_OUT0", displayName: "CLB2 OUT0" },
	{ name: "XBAR_OUT_MUX08_XTRIP_OUT3", displayName: "OUTPUTXBAR3" },
	{ name: "XBAR_OUT_MUX09_CLB2_OUT1", displayName: "CLB2 OUT1" },
	{ name: "XBAR_OUT_MUX09_XTRIP_OUT4", displayName: "OUTPUTXBAR4" },
	{ name: "XBAR_OUT_MUX10_CLB2_OUT2", displayName: "CLB2 OUT2" },
	{ name: "XBAR_OUT_MUX11_CLB2_OUT3", displayName: "CLB2 OUT3" },
	{ name: "XBAR_OUT_MUX12_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_OUT_MUX13_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_OUT_MUX14_CLB2_OUT6", displayName: "CLB2 OUT6" },
	{ name: "XBAR_OUT_MUX15_CLB2_OUT7", displayName: "CLB2 OUT7" },
	{ name: "XBAR_OUT_MUX16_CLB3_OUT0", displayName: "CLB3_OUT0" },
	{ name: "XBAR_OUT_MUX16_XTRIP_OUT5", displayName: "OUTPUTXBAR5" },
	{ name: "XBAR_OUT_MUX17_CLB3_OUT1", displayName: "CLB3_OUT1" },
	{ name: "XBAR_OUT_MUX17_XTRIP_OUT6", displayName: "OUTPUTXBAR6" },
	{ name: "XBAR_OUT_MUX18_CLB3_OUT2", displayName: "CLB3_OUT2" },
	{ name: "XBAR_OUT_MUX19_CLB3_OUT3", displayName: "CLB3_OUT3" },
	{ name: "XBAR_OUT_MUX20_CLB3_OUT4", displayName: "CLB3_OUT4" },
	{ name: "XBAR_OUT_MUX21_CLB3_OUT5", displayName: "CLB3_OUT5" },
	{ name: "XBAR_OUT_MUX22_CLB3_OUT6", displayName: "CLB3_OUT6" },
	{ name: "XBAR_OUT_MUX23_CLB3_OUT7", displayName: "CLB3_OUT7" },
	{ name: "XBAR_OUT_MUX24_CLB4_OUT0", displayName: "CLB4_OUT0" },
	{ name: "XBAR_OUT_MUX24_XTRIP_OUT7", displayName: "OUTPUTXBAR7" },
	{ name: "XBAR_OUT_MUX25_CLB4_OUT1", displayName: "CLB4_OUT1" },
	{ name: "XBAR_OUT_MUX25_XTRIP_OUT8", displayName: "OUTPUTXBAR8" },
	{ name: "XBAR_OUT_MUX26_CLB4_OUT2", displayName: "CLB4_OUT2" },
	{ name: "XBAR_OUT_MUX27_CLB4_OUT3", displayName: "CLB4_OUT3" },
	{ name: "XBAR_OUT_MUX28_CLB4_OUT4", displayName: "CLB4_OUT4" },
	{ name: "XBAR_OUT_MUX29_CLB4_OUT5", displayName: "CLB4_OUT5" },
	{ name: "XBAR_OUT_MUX30_CLB4_OUT6", displayName: "CLB4_OUT6" },
	{ name: "XBAR_OUT_MUX30_EPG1_OUT2", displayName: "EPG1 OUT2" },
	{ name: "XBAR_OUT_MUX31_CLB4_OUT7", displayName: "CLB4_OUT7" },
	{ name: "XBAR_OUT_MUX31_EPG1_OUT3", displayName: "EPG1 OUT3" },
]
let XBAR_EPWMMuxConfig = [
	{ name: "XBAR_EPWM_MUX00_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_EPWM_MUX00_CMPSS1_CTRIPH_OR_L", displayName: "CMPSS1 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_EPWM_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_EPWM_MUX01_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_EPWM_MUX01_INPUTXBAR1_INPUT1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_EPWM_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_EPWM_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_EPWM_MUX02_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_EPWM_MUX02_CMPSS2_CTRIPH_OR_L", displayName: "CMPSS2 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_EPWM_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_EPWM_MUX03_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_EPWM_MUX03_INPUTXBAR1_INPUT2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_EPWM_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_EPWM_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_EPWM_MUX04_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_EPWM_MUX04_CMPSS3_CTRIPH_OR_L", displayName: "CMPSS3 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_EPWM_MUX05_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_EPWM_MUX05_INPUTXBAR1_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_EPWM_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_EPWM_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_EPWM_MUX06_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_EPWM_MUX06_CMPSS4_CTRIPH_OR_L", displayName: "CMPSS4 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_EPWM_MUX07_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_EPWM_MUX07_INPUTXBAR1_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_EPWM_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_EPWM_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_EPWM_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_EPWM_MUX09_INPUTXBAR1_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_EPWM_MUX09_CLB3_OUT4", displayName: "CLB3_OUT4" },
	{ name: "XBAR_EPWM_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_EPWM_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_EPWM_MUX11_INPUTXBAR1_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_EPWM_MUX11_CLB3_OUT5", displayName: "CLB3_OUT5" },
	{ name: "XBAR_EPWM_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_EPWM_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_EPWM_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_EPWM_MUX13_CLB4_OUT4", displayName: "CLB4_OUT4" },
	{ name: "XBAR_EPWM_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_EPWM_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_EPWM_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_EPWM_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_EPWM_MUX15_CLB4_OUT5", displayName: "CLB4_OUT5" },
	{ name: "XBAR_EPWM_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_EPWM_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_EPWM_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX16_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_EPWM_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_EPWM_MUX17_INPUTXBAR1_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_EPWM_MUX17_CLBINPUTXBAR7", displayName: "CLBINPUTXBAR7" },
	{ name: "XBAR_EPWM_MUX17_CLAHALT", displayName: "CLAHALT" },
	{ name: "XBAR_EPWM_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_EPWM_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX18_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_EPWM_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_EPWM_MUX19_INPUTXBAR1_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_EPWM_MUX19_CLBINPUTXBAR8", displayName: "CLBINPUTXBAR8" },
	{ name: "XBAR_EPWM_MUX19_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_EPWM_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_EPWM_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX20_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_EPWM_MUX20_FSIA_RX_TRIG1", displayName: "FSIA RX TRIG1" },
	{ name: "XBAR_EPWM_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_EPWM_MUX21_INPUTXBAR1_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_EPWM_MUX21_CLBINPUTXBAR9", displayName: "CLBINPUTXBAR9" },
	{ name: "XBAR_EPWM_MUX22_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_EPWM_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_EPWM_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_EPWM_MUX23_INPUTXBAR1_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_EPWM_MUX23_CLBINPUTXBAR10", displayName: "CLBINPUTXBAR10" },
	{ name: "XBAR_EPWM_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_EPWM_MUX24_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_EPWM_MUX25_INPUTXBAR1_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_EPWM_MUX25_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_EPWM_MUX25_CLBINPUTXBAR11", displayName: "CLBINPUTXBAR11" },
	{ name: "XBAR_EPWM_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_EPWM_MUX26_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_EPWM_MUX27_INPUTXBAR1_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_EPWM_MUX27_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_EPWM_MUX27_CLBINPUTXBAR12", displayName: "CLBINPUTXBAR12" },
	{ name: "XBAR_EPWM_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_EPWM_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_EPWM_MUX29_INPUTXBAR1_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_EPWM_MUX29_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_EPWM_MUX29_CLBINPUTXBAR13", displayName: "CLBINPUTXBAR13" },
	{ name: "XBAR_EPWM_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_EPWM_MUX30_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_EPWM_MUX31_INPUTXBAR1_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_EPWM_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_EPWM_MUX31_CLBINPUTXBAR14", displayName: "CLBINPUTXBAR14" },
]
let XBAR_CLBMuxConfig = [
	{ name: "XBAR_CLB_MUX00_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_CLB_MUX00_CMPSS1_CTRIPH_OR_L", displayName: "CMPSS1 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_CLB_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_CLB_MUX01_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_CLB_MUX01_INPUTXBAR1_INPUT1", displayName: "INPUTXBAR1 INPUT1" },
	{ name: "XBAR_CLB_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_CLB_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_CLB_MUX02_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_CLB_MUX02_CMPSS2_CTRIPH_OR_L", displayName: "CMPSS2 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_CLB_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_CLB_MUX03_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_CLB_MUX03_INPUTXBAR1_INPUT2", displayName: "INPUTXBAR1 INPUT2" },
	{ name: "XBAR_CLB_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_CLB_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_CLB_MUX04_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_CLB_MUX04_CMPSS3_CTRIPH_OR_L", displayName: "CMPSS3 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_CLB_MUX04_SD1FLT1_COMPZ", displayName: "SD1FLT1_COMPZ" },
	{ name: "XBAR_CLB_MUX05_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_CLB_MUX05_INPUTXBAR1_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_CLB_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_CLB_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_CLB_MUX06_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_CLB_MUX06_CMPSS4_CTRIPH_OR_L", displayName: "CMPSS4 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_CLB_MUX06_SD2FLT1_COMPZ", displayName: "SD2FLT1_COMPZ" },
	{ name: "XBAR_CLB_MUX07_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_CLB_MUX07_INPUTXBAR1_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_CLB_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_CLB_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_CLB_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_CLB_MUX08_SD2FLT2_COMPZ", displayName: "SD2FLT2_COMPZ" },
	{ name: "XBAR_CLB_MUX09_INPUTXBAR1_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_CLB_MUX09_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_CLB_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_CLB_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_CLB_MUX10_SD2FLT3_COMPZ", displayName: "SD2FLT3_COMPZ" },
	{ name: "XBAR_CLB_MUX11_INPUTXBAR1_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_CLB_MUX11_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_CLB_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_CLB_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_CLB_MUX12_SD2FLT4_COMPZ", displayName: "SD2FLT4_COMPZ" },
	{ name: "XBAR_CLB_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_CLB_MUX13_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_CLB_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_CLB_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_CLB_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_CLB_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_CLB_MUX15_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_CLB_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_CLB_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_CLB_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX16_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_CLB_MUX16_FSIA_RX_TRIG3", displayName: "FSIA RX TRIG3" },
	{ name: "XBAR_CLB_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_CLB_MUX17_INPUTXBAR1_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_CLB_MUX17_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_CLB_MUX17_CLAHALT", displayName: "CLAHALT" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPZ", displayName: "SD1FLT2_COMPZ" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_DRINT", displayName: "SD1FLT2_DRINT" },
	{ name: "XBAR_CLB_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_CLB_MUX19_INPUTXBAR1_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_CLB_MUX19_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_CLB_MUX19_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPZ", displayName: "SD1FLT3_COMPZ" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_DRINT", displayName: "SD1FLT3_DRINT" },
	{ name: "XBAR_CLB_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_CLB_MUX21_INPUTXBAR1_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_CLB_MUX21_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_CLB_MUX21_SD1FLT1_DRINT", displayName: "SD1FLT1_DRINT" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPZ", displayName: "SD1FLT4_COMPZ" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_DRINT", displayName: "SD1FLT4_DRINT" },
	{ name: "XBAR_CLB_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_CLB_MUX23_INPUTXBAR1_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_CLB_MUX23_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_CLB_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_CLB_MUX24_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX24_CPU1_ERADEVT8", displayName: "CPU1 ERADEVT8" },
	{ name: "XBAR_CLB_MUX24_SD2FLT1_DRINT", displayName: "SD2FLT1_DRINT" },
	{ name: "XBAR_CLB_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_CLB_MUX25_INPUTXBAR1_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_CLB_MUX25_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_CLB_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_CLB_MUX26_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX26_CPU1_ERADEVT9", displayName: "CPU1 ERADEVT9" },
	{ name: "XBAR_CLB_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_CLB_MUX27_INPUTXBAR1_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_CLB_MUX27_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_CLB_MUX27_SD2FLT2_DRINT", displayName: "SD2FLT2_DRINT" },
	{ name: "XBAR_CLB_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_CLB_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX28_CPU1_ERADEVT10", displayName: "CPU1 ERADEVT10" },
	{ name: "XBAR_CLB_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_CLB_MUX29_INPUTXBAR1_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_CLB_MUX29_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_CLB_MUX29_SD2FLT3_DRINT", displayName: "SD2FLT3_DRINT" },
	{ name: "XBAR_CLB_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_CLB_MUX30_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX30_CPU1_ERADEVT11", displayName: "CPU1 ERADEVT11" },
	{ name: "XBAR_CLB_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_CLB_MUX31_INPUTXBAR1_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_CLB_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_CLB_MUX31_SD2FLT4_DRINT", displayName: "SD2FLT4_DRINT" },
]
let XBAR_InputFlag = [
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPL", displayName: "INPUT FLG CMPSS1 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPH", displayName: "INPUT FLG CMPSS1 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPL", displayName: "INPUT FLG CMPSS2 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPH", displayName: "INPUT FLG CMPSS2 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPL", displayName: "INPUT FLG CMPSS3 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPH", displayName: "INPUT FLG CMPSS3 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPL", displayName: "INPUT FLG CMPSS4 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPH", displayName: "INPUT FLG CMPSS4 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPOUTL", displayName: "INPUT FLG CMPSS1 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPOUTH", displayName: "INPUT FLG CMPSS1 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPOUTL", displayName: "INPUT FLG CMPSS2 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPOUTH", displayName: "INPUT FLG CMPSS2 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPOUTL", displayName: "INPUT FLG CMPSS3 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPOUTH", displayName: "INPUT FLG CMPSS3 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPOUTL", displayName: "INPUT FLG CMPSS4 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPOUTH", displayName: "INPUT FLG CMPSS4 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_INPUT1", displayName: "INPUT FLG INPUT1" },
	{ name: "XBAR_INPUT_FLG_INPUT2", displayName: "INPUT FLG INPUT2" },
	{ name: "XBAR_INPUT_FLG_INPUT3", displayName: "INPUT FLG INPUT3" },
	{ name: "XBAR_INPUT_FLG_INPUT4", displayName: "INPUT FLG INPUT4" },
	{ name: "XBAR_INPUT_FLG_INPUT5", displayName: "INPUT FLG INPUT5" },
	{ name: "XBAR_INPUT_FLG_INPUT6", displayName: "INPUT FLG INPUT6" },
	{ name: "XBAR_INPUT_FLG_ADCSOCA", displayName: "INPUT FLG ADCSOCA" },
	{ name: "XBAR_INPUT_FLG_ADCSOCB", displayName: "INPUT FLG ADCSOCB" },
	{ name: "XBAR_INPUT_FLG_INPUT7", displayName: "INPUT FLG INPUT7" },
	{ name: "XBAR_INPUT_FLG_INPUT8", displayName: "INPUT FLG INPUT8" },
	{ name: "XBAR_INPUT_FLG_INPUT9", displayName: "INPUT FLG INPUT9" },
	{ name: "XBAR_INPUT_FLG_INPUT10", displayName: "INPUT FLG INPUT10" },
	{ name: "XBAR_INPUT_FLG_INPUT11", displayName: "INPUT FLG INPUT11" },
	{ name: "XBAR_INPUT_FLG_INPUT12", displayName: "INPUT FLG INPUT12" },
	{ name: "XBAR_INPUT_FLG_INPUT13", displayName: "INPUT FLG INPUT13" },
	{ name: "XBAR_INPUT_FLG_INPUT14", displayName: "INPUT FLG INPUT14" },
	{ name: "XBAR_INPUT_FLG_ECAP1_OUT", displayName: "INPUT FLG ECAP1 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP2_OUT", displayName: "INPUT FLG ECAP2 OUT" },
	{ name: "XBAR_INPUT_FLG_EXTSYNCOUT", displayName: "INPUT FLG EXTSYNCOUT" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT1", displayName: "INPUT FLG ADCAEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT2", displayName: "INPUT FLG ADCAEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT3", displayName: "INPUT FLG ADCAEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT4", displayName: "INPUT FLG ADCAEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT1", displayName: "INPUT FLG ADCBEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT2", displayName: "INPUT FLG ADCBEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT3", displayName: "INPUT FLG ADCBEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT4", displayName: "INPUT FLG ADCBEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT1", displayName: "INPUT FLG ADCCEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT2", displayName: "INPUT FLG ADCCEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT3", displayName: "INPUT FLG ADCCEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT4", displayName: "INPUT FLG ADCCEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT1", displayName: "INPUT FLG ADCDEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT2", displayName: "INPUT FLG ADCDEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT3", displayName: "INPUT FLG ADCDEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT4", displayName: "INPUT FLG ADCDEVT4" },
	{ name: "XBAR_INPUT_FLG_SD1FLT1_COMPL", displayName: "INPUT FLG SD1FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT1_COMPH", displayName: "INPUT FLG SD1FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT2_COMPL", displayName: "INPUT FLG SD1FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT2_COMPH", displayName: "INPUT FLG SD1FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT3_COMPL", displayName: "INPUT FLG SD1FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT3_COMPH", displayName: "INPUT FLG SD1FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT4_COMPL", displayName: "INPUT FLG SD1FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT4_COMPH", displayName: "INPUT FLG SD1FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT1", displayName: "INPUT FLG ADCEEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT2", displayName: "INPUT FLG ADCEEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT3", displayName: "INPUT FLG ADCEEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT4", displayName: "INPUT FLG ADCEEVT4" },
	{ name: "XBAR_INPUT_FLG_SD2FLT1_COMPL", displayName: "INPUT FLG SD2FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT1_COMPH", displayName: "INPUT FLG SD2FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT2_COMPL", displayName: "INPUT FLG SD2FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT2_COMPH", displayName: "INPUT FLG SD2FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT3_COMPL", displayName: "INPUT FLG SD2FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT3_COMPH", displayName: "INPUT FLG SD2FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT4_COMPL", displayName: "INPUT FLG SD2FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT4_COMPH", displayName: "INPUT FLG SD2FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT0", displayName: "INPUT FLG MCANA FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT1", displayName: "INPUT FLG MCANA FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT2", displayName: "INPUT FLG MCANA FEVT2" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT4", displayName: "INPUT FLG CLB1 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT5", displayName: "INPUT FLG CLB1 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT4", displayName: "INPUT FLG CLB2 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT5", displayName: "INPUT FLG CLB2 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT4", displayName: "INPUT FLG CLB3 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT5", displayName: "INPUT FLG CLB3 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT4", displayName: "INPUT FLG CLB4 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT5", displayName: "INPUT FLG CLB4 OUT5" },
	{ name: "XBAR_INPUT_FLG_ERRORSTS_ERROR", displayName: "INPUT FLG ERRORSTS ERROR" },
	{ name: "XBAR_INPUT_FLG_CLAHALT", displayName: "INPUT FLG CLAHALT" },
]

// MUX Specific Configs
let XBAR_OutputMuxConfig_MUX00 = [
	{ name: "XBAR_OUT_MUX00_CMPSS1_CTRIPOUTH", displayName: "CMPSS1 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX00_CMPSS1_CTRIPOUTH_OR_L", displayName: "CMPSS1 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_OUT_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_OUT_MUX00_CLB1_OUT0", displayName: "CLB1 OUT0" },
	{ name: "XBAR_OUT_MUX00_XTRIP_OUT1", displayName: "OUTPUTXBAR1" },
]
let XBAR_OutputMuxConfig_MUX01 = [
	{ name: "XBAR_OUT_MUX01_CMPSS1_CTRIPOUTL", displayName: "CMPSS1 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX01_INPUTXBAR1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_OUT_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_OUT_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_OUT_MUX01_CLB1_OUT1", displayName: "CLB1 OUT1" },
	{ name: "XBAR_OUT_MUX01_XTRIP_OUT2", displayName: "OUTPUTXBAR2" },
]
let XBAR_OutputMuxConfig_MUX02 = [
	{ name: "XBAR_OUT_MUX02_CMPSS2_CTRIPOUTH", displayName: "CMPSS2 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX02_CMPSS2_CTRIPOUTH_OR_L", displayName: "CMPSS2 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_OUT_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_OUT_MUX02_CLB1_OUT2", displayName: "CLB1 OUT2" },
]
let XBAR_OutputMuxConfig_MUX03 = [
	{ name: "XBAR_OUT_MUX03_CMPSS2_CTRIPOUTL", displayName: "CMPSS2 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX03_INPUTXBAR2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_OUT_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_OUT_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_OUT_MUX03_CLB1_OUT3", displayName: "CLB1 OUT3" },
]
let XBAR_OutputMuxConfig_MUX04 = [
	{ name: "XBAR_OUT_MUX04_CMPSS3_CTRIPOUTH", displayName: "CMPSS3 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX04_CMPSS3_CTRIPOUTH_OR_L", displayName: "CMPSS3 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_OUT_MUX04_CLB1_OUT4", displayName: "CLB1 OUT4" },
]
let XBAR_OutputMuxConfig_MUX05 = [
	{ name: "XBAR_OUT_MUX05_CMPSS3_CTRIPOUTL", displayName: "CMPSS3 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX05_INPUTXBAR3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_OUT_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_OUT_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_OUT_MUX05_CLB1_OUT5", displayName: "CLB1 OUT5" },
]
let XBAR_OutputMuxConfig_MUX06 = [
	{ name: "XBAR_OUT_MUX06_CMPSS4_CTRIPOUTH", displayName: "CMPSS4 CTRIPOUTH" },
	{ name: "XBAR_OUT_MUX06_CMPSS4_CTRIPOUTH_OR_L", displayName: "CMPSS4 CTRIPOUTH OR CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_OUT_MUX06_CLB1_OUT6", displayName: "CLB1 OUT6" },
]
let XBAR_OutputMuxConfig_MUX07 = [
	{ name: "XBAR_OUT_MUX07_CMPSS4_CTRIPOUTL", displayName: "CMPSS4 CTRIPOUTL" },
	{ name: "XBAR_OUT_MUX07_INPUTXBAR4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_OUT_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_OUT_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_OUT_MUX07_CLB1_OUT7", displayName: "CLB1 OUT7" },
]
let XBAR_OutputMuxConfig_MUX08 = [
	{ name: "XBAR_OUT_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_OUT_MUX08_CLB2_OUT0", displayName: "CLB2 OUT0" },
	{ name: "XBAR_OUT_MUX08_XTRIP_OUT3", displayName: "OUTPUTXBAR3" },
]
let XBAR_OutputMuxConfig_MUX09 = [
	{ name: "XBAR_OUT_MUX09_INPUTXBAR5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_OUT_MUX09_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_OUT_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_OUT_MUX09_CLB2_OUT1", displayName: "CLB2 OUT1" },
	{ name: "XBAR_OUT_MUX09_XTRIP_OUT4", displayName: "OUTPUTXBAR4" },
]
let XBAR_OutputMuxConfig_MUX10 = [
	{ name: "XBAR_OUT_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_OUT_MUX10_CLB2_OUT2", displayName: "CLB2 OUT2" },
]
let XBAR_OutputMuxConfig_MUX11 = [
	{ name: "XBAR_OUT_MUX11_INPUTXBAR6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_OUT_MUX11_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_OUT_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_OUT_MUX11_CLB2_OUT3", displayName: "CLB2 OUT3" },
]
let XBAR_OutputMuxConfig_MUX12 = [
	{ name: "XBAR_OUT_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_OUT_MUX12_CLB2_OUT4", displayName: "CLB2 OUT4" },
]
let XBAR_OutputMuxConfig_MUX13 = [
	{ name: "XBAR_OUT_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_OUT_MUX13_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_OUT_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_OUT_MUX13_CLB2_OUT5", displayName: "CLB2 OUT5" },
]
let XBAR_OutputMuxConfig_MUX14 = [
	{ name: "XBAR_OUT_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_OUT_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_OUT_MUX14_CLB2_OUT6", displayName: "CLB2 OUT6" },
]
let XBAR_OutputMuxConfig_MUX15 = [
	{ name: "XBAR_OUT_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_OUT_MUX15_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_OUT_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_OUT_MUX15_CLB2_OUT7", displayName: "CLB2 OUT7" },
]
let XBAR_OutputMuxConfig_MUX16 = [
	{ name: "XBAR_OUT_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_OUT_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX16_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_OUT_MUX16_CLB3_OUT0", displayName: "CLB3_OUT0" },
	{ name: "XBAR_OUT_MUX16_XTRIP_OUT5", displayName: "OUTPUTXBAR5" },
]
let XBAR_OutputMuxConfig_MUX17 = [
	{ name: "XBAR_OUT_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_OUT_MUX17_CLAHALT", displayName: "CLAHALT" },
	{ name: "XBAR_OUT_MUX17_CLB3_OUT1", displayName: "CLB3_OUT1" },
	{ name: "XBAR_OUT_MUX17_XTRIP_OUT6", displayName: "OUTPUTXBAR6" },
]
let XBAR_OutputMuxConfig_MUX18 = [
	{ name: "XBAR_OUT_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_OUT_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX18_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_OUT_MUX18_CLB3_OUT2", displayName: "CLB3_OUT2" },
]
let XBAR_OutputMuxConfig_MUX19 = [
	{ name: "XBAR_OUT_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_OUT_MUX19_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_OUT_MUX19_CLB3_OUT3", displayName: "CLB3_OUT3" },
]
let XBAR_OutputMuxConfig_MUX20 = [
	{ name: "XBAR_OUT_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_OUT_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX20_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_OUT_MUX20_CLB3_OUT4", displayName: "CLB3_OUT4" },
]
let XBAR_OutputMuxConfig_MUX21 = [
	{ name: "XBAR_OUT_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_OUT_MUX21_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX21_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_OUT_MUX21_CLB3_OUT5", displayName: "CLB3_OUT5" },
]
let XBAR_OutputMuxConfig_MUX22 = [
	{ name: "XBAR_OUT_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_OUT_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX22_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_OUT_MUX22_CLB3_OUT6", displayName: "CLB3_OUT6" },
]
let XBAR_OutputMuxConfig_MUX23 = [
	{ name: "XBAR_OUT_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_OUT_MUX23_ADCA_EXTMUXSEL0", displayName: "ADCA EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX23_ADCC_EXTMUXSEL0", displayName: "ADCC EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX23_ADCE_EXTMUXSEL0", displayName: "ADCE EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX23_CLB3_OUT7", displayName: "CLB3_OUT7" },
]
let XBAR_OutputMuxConfig_MUX24 = [
	{ name: "XBAR_OUT_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_OUT_MUX24_ADCA_EXTMUXSEL1", displayName: "ADCA EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX24_ADCC_EXTMUXSEL1", displayName: "ADCC EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX24_ADCE_EXTMUXSEL1", displayName: "ADCE EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX24_CLB4_OUT0", displayName: "CLB4_OUT0" },
	{ name: "XBAR_OUT_MUX24_XTRIP_OUT7", displayName: "OUTPUTXBAR7" },
]
let XBAR_OutputMuxConfig_MUX25 = [
	{ name: "XBAR_OUT_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_OUT_MUX25_ADCA_EXTMUXSEL2", displayName: "ADCA EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX25_ADCC_EXTMUXSEL2", displayName: "ADCC EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX25_ADCE_EXTMUXSEL2", displayName: "ADCE EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX25_CLB4_OUT1", displayName: "CLB4_OUT1" },
	{ name: "XBAR_OUT_MUX25_XTRIP_OUT8", displayName: "OUTPUTXBAR8" },
]
let XBAR_OutputMuxConfig_MUX26 = [
	{ name: "XBAR_OUT_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_OUT_MUX26_ADCA_EXTMUXSEL3", displayName: "ADCA EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX26_ADCC_EXTMUXSEL3", displayName: "ADCC EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX26_ADCE_EXTMUXSEL3", displayName: "ADCE EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX26_CLB4_OUT2", displayName: "CLB4_OUT2" },
]
let XBAR_OutputMuxConfig_MUX27 = [
	{ name: "XBAR_OUT_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_OUT_MUX27_ADCB_EXTMUXSEL0", displayName: "ADCB EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX27_ADCD_EXTMUXSEL0", displayName: "ADCD EXTMUXSEL0" },
	{ name: "XBAR_OUT_MUX27_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX27_CLB4_OUT3", displayName: "CLB4_OUT3" },
]
let XBAR_OutputMuxConfig_MUX28 = [
	{ name: "XBAR_OUT_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_OUT_MUX28_ADCB_EXTMUXSEL1", displayName: "ADCB EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX28_ADCD_EXTMUXSEL1", displayName: "ADCD EXTMUXSEL1" },
	{ name: "XBAR_OUT_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX28_CLB4_OUT4", displayName: "CLB4_OUT4" },
]
let XBAR_OutputMuxConfig_MUX29 = [
	{ name: "XBAR_OUT_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_OUT_MUX29_ADCB_EXTMUXSEL2", displayName: "ADCB EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX29_ADCD_EXTMUXSEL2", displayName: "ADCD EXTMUXSEL2" },
	{ name: "XBAR_OUT_MUX29_CLB4_OUT5", displayName: "CLB4_OUT5" },
]
let XBAR_OutputMuxConfig_MUX30 = [
	{ name: "XBAR_OUT_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_OUT_MUX30_ADCB_EXTMUXSEL3", displayName: "ADCB EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX30_ADCD_EXTMUXSEL3", displayName: "ADCD EXTMUXSEL3" },
	{ name: "XBAR_OUT_MUX30_EPG1_OUT0", displayName: "EPG1OUT0" },
	{ name: "XBAR_OUT_MUX30_CLB4_OUT6", displayName: "CLB4_OUT6" },
	{ name: "XBAR_OUT_MUX30_EPG1_OUT2", displayName: "EPG1 OUT2" },
]
let XBAR_OutputMuxConfig_MUX31 = [
	{ name: "XBAR_OUT_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_OUT_MUX31_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_OUT_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_OUT_MUX31_EPG1_OUT1", displayName: "EPG1 OUT1" },
	{ name: "XBAR_OUT_MUX31_CLB4_OUT7", displayName: "CLB4_OUT7" },
	{ name: "XBAR_OUT_MUX31_EPG1_OUT3", displayName: "EPG1 OUT3" },
]
let XBAR_OutputMuxConfig_All_MUXES = [
	XBAR_OutputMuxConfig_MUX00,
	XBAR_OutputMuxConfig_MUX01,
	XBAR_OutputMuxConfig_MUX02,
	XBAR_OutputMuxConfig_MUX03,
	XBAR_OutputMuxConfig_MUX04,
	XBAR_OutputMuxConfig_MUX05,
	XBAR_OutputMuxConfig_MUX06,
	XBAR_OutputMuxConfig_MUX07,
	XBAR_OutputMuxConfig_MUX08,
	XBAR_OutputMuxConfig_MUX09,
	XBAR_OutputMuxConfig_MUX10,
	XBAR_OutputMuxConfig_MUX11,
	XBAR_OutputMuxConfig_MUX12,
	XBAR_OutputMuxConfig_MUX13,
	XBAR_OutputMuxConfig_MUX14,
	XBAR_OutputMuxConfig_MUX15,
	XBAR_OutputMuxConfig_MUX16,
	XBAR_OutputMuxConfig_MUX17,
	XBAR_OutputMuxConfig_MUX18,
	XBAR_OutputMuxConfig_MUX19,
	XBAR_OutputMuxConfig_MUX20,
	XBAR_OutputMuxConfig_MUX21,
	XBAR_OutputMuxConfig_MUX22,
	XBAR_OutputMuxConfig_MUX23,
	XBAR_OutputMuxConfig_MUX24,
	XBAR_OutputMuxConfig_MUX25,
	XBAR_OutputMuxConfig_MUX26,
	XBAR_OutputMuxConfig_MUX27,
	XBAR_OutputMuxConfig_MUX28,
	XBAR_OutputMuxConfig_MUX29,
	XBAR_OutputMuxConfig_MUX30,
	XBAR_OutputMuxConfig_MUX31,
]
let XBAR_EPWMMuxConfig_MUX00 = [
	{ name: "XBAR_EPWM_MUX00_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_EPWM_MUX00_CMPSS1_CTRIPH_OR_L", displayName: "CMPSS1 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_EPWM_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
]
let XBAR_EPWMMuxConfig_MUX01 = [
	{ name: "XBAR_EPWM_MUX01_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_EPWM_MUX01_INPUTXBAR1_INPUT1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_EPWM_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_EPWM_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
]
let XBAR_EPWMMuxConfig_MUX02 = [
	{ name: "XBAR_EPWM_MUX02_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_EPWM_MUX02_CMPSS2_CTRIPH_OR_L", displayName: "CMPSS2 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_EPWM_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
]
let XBAR_EPWMMuxConfig_MUX03 = [
	{ name: "XBAR_EPWM_MUX03_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_EPWM_MUX03_INPUTXBAR1_INPUT2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_EPWM_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_EPWM_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
]
let XBAR_EPWMMuxConfig_MUX04 = [
	{ name: "XBAR_EPWM_MUX04_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_EPWM_MUX04_CMPSS3_CTRIPH_OR_L", displayName: "CMPSS3 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
]
let XBAR_EPWMMuxConfig_MUX05 = [
	{ name: "XBAR_EPWM_MUX05_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_EPWM_MUX05_INPUTXBAR1_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_EPWM_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_EPWM_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
]
let XBAR_EPWMMuxConfig_MUX06 = [
	{ name: "XBAR_EPWM_MUX06_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_EPWM_MUX06_CMPSS4_CTRIPH_OR_L", displayName: "CMPSS4 CTRIPH OR L" },
	{ name: "XBAR_EPWM_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
]
let XBAR_EPWMMuxConfig_MUX07 = [
	{ name: "XBAR_EPWM_MUX07_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_EPWM_MUX07_INPUTXBAR1_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_EPWM_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_EPWM_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
]
let XBAR_EPWMMuxConfig_MUX08 = [
	{ name: "XBAR_EPWM_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
]
let XBAR_EPWMMuxConfig_MUX09 = [
	{ name: "XBAR_EPWM_MUX09_INPUTXBAR1_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_EPWM_MUX09_CLB3_OUT4", displayName: "CLB3_OUT4" },
	{ name: "XBAR_EPWM_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
]
let XBAR_EPWMMuxConfig_MUX10 = [
	{ name: "XBAR_EPWM_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
]
let XBAR_EPWMMuxConfig_MUX11 = [
	{ name: "XBAR_EPWM_MUX11_INPUTXBAR1_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_EPWM_MUX11_CLB3_OUT5", displayName: "CLB3_OUT5" },
	{ name: "XBAR_EPWM_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
]
let XBAR_EPWMMuxConfig_MUX12 = [
	{ name: "XBAR_EPWM_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
]
let XBAR_EPWMMuxConfig_MUX13 = [
	{ name: "XBAR_EPWM_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_EPWM_MUX13_CLB4_OUT4", displayName: "CLB4_OUT4" },
	{ name: "XBAR_EPWM_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
]
let XBAR_EPWMMuxConfig_MUX14 = [
	{ name: "XBAR_EPWM_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_EPWM_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
]
let XBAR_EPWMMuxConfig_MUX15 = [
	{ name: "XBAR_EPWM_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_EPWM_MUX15_CLB4_OUT5", displayName: "CLB4_OUT5" },
	{ name: "XBAR_EPWM_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
]
let XBAR_EPWMMuxConfig_MUX16 = [
	{ name: "XBAR_EPWM_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_EPWM_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX16_ADCEEVT1", displayName: "ADCEEVT1" },
]
let XBAR_EPWMMuxConfig_MUX17 = [
	{ name: "XBAR_EPWM_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_EPWM_MUX17_INPUTXBAR1_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_EPWM_MUX17_CLBINPUTXBAR7", displayName: "CLBINPUTXBAR7" },
	{ name: "XBAR_EPWM_MUX17_CLAHALT", displayName: "CLAHALT" },
]
let XBAR_EPWMMuxConfig_MUX18 = [
	{ name: "XBAR_EPWM_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_EPWM_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX18_ADCEEVT2", displayName: "ADCEEVT2" },
]
let XBAR_EPWMMuxConfig_MUX19 = [
	{ name: "XBAR_EPWM_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_EPWM_MUX19_INPUTXBAR1_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_EPWM_MUX19_CLBINPUTXBAR8", displayName: "CLBINPUTXBAR8" },
	{ name: "XBAR_EPWM_MUX19_ERRORSTS", displayName: "ERRORSTS" },
]
let XBAR_EPWMMuxConfig_MUX20 = [
	{ name: "XBAR_EPWM_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_EPWM_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_EPWM_MUX20_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_EPWM_MUX20_FSIA_RX_TRIG1", displayName: "FSIA RX TRIG1" },
]
let XBAR_EPWMMuxConfig_MUX21 = [
	{ name: "XBAR_EPWM_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_EPWM_MUX21_INPUTXBAR1_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_EPWM_MUX21_CLBINPUTXBAR9", displayName: "CLBINPUTXBAR9" },
]
let XBAR_EPWMMuxConfig_MUX22 = [
	{ name: "XBAR_EPWM_MUX22_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_EPWM_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_EPWM_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
]
let XBAR_EPWMMuxConfig_MUX23 = [
	{ name: "XBAR_EPWM_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_EPWM_MUX23_INPUTXBAR1_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_EPWM_MUX23_CLBINPUTXBAR10", displayName: "CLBINPUTXBAR10" },
]
let XBAR_EPWMMuxConfig_MUX24 = [
	{ name: "XBAR_EPWM_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_EPWM_MUX24_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
]
let XBAR_EPWMMuxConfig_MUX25 = [
	{ name: "XBAR_EPWM_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_EPWM_MUX25_INPUTXBAR1_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_EPWM_MUX25_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_EPWM_MUX25_CLBINPUTXBAR11", displayName: "CLBINPUTXBAR11" },
]
let XBAR_EPWMMuxConfig_MUX26 = [
	{ name: "XBAR_EPWM_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_EPWM_MUX26_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
]
let XBAR_EPWMMuxConfig_MUX27 = [
	{ name: "XBAR_EPWM_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_EPWM_MUX27_INPUTXBAR1_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_EPWM_MUX27_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_EPWM_MUX27_CLBINPUTXBAR12", displayName: "CLBINPUTXBAR12" },
]
let XBAR_EPWMMuxConfig_MUX28 = [
	{ name: "XBAR_EPWM_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_EPWM_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
]
let XBAR_EPWMMuxConfig_MUX29 = [
	{ name: "XBAR_EPWM_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_EPWM_MUX29_INPUTXBAR1_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_EPWM_MUX29_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_EPWM_MUX29_CLBINPUTXBAR13", displayName: "CLBINPUTXBAR13" },
]
let XBAR_EPWMMuxConfig_MUX30 = [
	{ name: "XBAR_EPWM_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_EPWM_MUX30_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
]
let XBAR_EPWMMuxConfig_MUX31 = [
	{ name: "XBAR_EPWM_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_EPWM_MUX31_INPUTXBAR1_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_EPWM_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_EPWM_MUX31_CLBINPUTXBAR14", displayName: "CLBINPUTXBAR14" },
]
let XBAR_EPWMMuxConfig_All_MUXES = [
	XBAR_EPWMMuxConfig_MUX00,
	XBAR_EPWMMuxConfig_MUX01,
	XBAR_EPWMMuxConfig_MUX02,
	XBAR_EPWMMuxConfig_MUX03,
	XBAR_EPWMMuxConfig_MUX04,
	XBAR_EPWMMuxConfig_MUX05,
	XBAR_EPWMMuxConfig_MUX06,
	XBAR_EPWMMuxConfig_MUX07,
	XBAR_EPWMMuxConfig_MUX08,
	XBAR_EPWMMuxConfig_MUX09,
	XBAR_EPWMMuxConfig_MUX10,
	XBAR_EPWMMuxConfig_MUX11,
	XBAR_EPWMMuxConfig_MUX12,
	XBAR_EPWMMuxConfig_MUX13,
	XBAR_EPWMMuxConfig_MUX14,
	XBAR_EPWMMuxConfig_MUX15,
	XBAR_EPWMMuxConfig_MUX16,
	XBAR_EPWMMuxConfig_MUX17,
	XBAR_EPWMMuxConfig_MUX18,
	XBAR_EPWMMuxConfig_MUX19,
	XBAR_EPWMMuxConfig_MUX20,
	XBAR_EPWMMuxConfig_MUX21,
	XBAR_EPWMMuxConfig_MUX22,
	XBAR_EPWMMuxConfig_MUX23,
	XBAR_EPWMMuxConfig_MUX24,
	XBAR_EPWMMuxConfig_MUX25,
	XBAR_EPWMMuxConfig_MUX26,
	XBAR_EPWMMuxConfig_MUX27,
	XBAR_EPWMMuxConfig_MUX28,
	XBAR_EPWMMuxConfig_MUX29,
	XBAR_EPWMMuxConfig_MUX30,
	XBAR_EPWMMuxConfig_MUX31,
]
let XBAR_CLBMuxConfig_MUX00 = [
	{ name: "XBAR_CLB_MUX00_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_CLB_MUX00_CMPSS1_CTRIPH_OR_L", displayName: "CMPSS1 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX00_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_CLB_MUX00_ECAP1_OUT", displayName: "ECAP1 OUT" },
]
let XBAR_CLBMuxConfig_MUX01 = [
	{ name: "XBAR_CLB_MUX01_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_CLB_MUX01_INPUTXBAR1_INPUT1", displayName: "INPUTXBAR1 INPUT1" },
	{ name: "XBAR_CLB_MUX01_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_CLB_MUX01_ADCCEVT1", displayName: "ADCCEVT1" },
]
let XBAR_CLBMuxConfig_MUX02 = [
	{ name: "XBAR_CLB_MUX02_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_CLB_MUX02_CMPSS2_CTRIPH_OR_L", displayName: "CMPSS2 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX02_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_CLB_MUX02_ECAP2_OUT", displayName: "ECAP2 OUT" },
]
let XBAR_CLBMuxConfig_MUX03 = [
	{ name: "XBAR_CLB_MUX03_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_CLB_MUX03_INPUTXBAR1_INPUT2", displayName: "INPUTXBAR1 INPUT2" },
	{ name: "XBAR_CLB_MUX03_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_CLB_MUX03_ADCCEVT2", displayName: "ADCCEVT2" },
]
let XBAR_CLBMuxConfig_MUX04 = [
	{ name: "XBAR_CLB_MUX04_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_CLB_MUX04_CMPSS3_CTRIPH_OR_L", displayName: "CMPSS3 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX04_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_CLB_MUX04_SD1FLT1_COMPZ", displayName: "SD1FLT1_COMPZ" },
]
let XBAR_CLBMuxConfig_MUX05 = [
	{ name: "XBAR_CLB_MUX05_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_CLB_MUX05_INPUTXBAR1_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_CLB_MUX05_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_CLB_MUX05_ADCCEVT3", displayName: "ADCCEVT3" },
]
let XBAR_CLBMuxConfig_MUX06 = [
	{ name: "XBAR_CLB_MUX06_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_CLB_MUX06_CMPSS4_CTRIPH_OR_L", displayName: "CMPSS4 CTRIPH OR L" },
	{ name: "XBAR_CLB_MUX06_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_CLB_MUX06_SD2FLT1_COMPZ", displayName: "SD2FLT1_COMPZ" },
]
let XBAR_CLBMuxConfig_MUX07 = [
	{ name: "XBAR_CLB_MUX07_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_CLB_MUX07_INPUTXBAR1_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_CLB_MUX07_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_CLB_MUX07_ADCCEVT4", displayName: "ADCCEVT4" },
]
let XBAR_CLBMuxConfig_MUX08 = [
	{ name: "XBAR_CLB_MUX08_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_CLB_MUX08_SD2FLT2_COMPZ", displayName: "SD2FLT2_COMPZ" },
]
let XBAR_CLBMuxConfig_MUX09 = [
	{ name: "XBAR_CLB_MUX09_INPUTXBAR1_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_CLB_MUX09_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_CLB_MUX09_ADCDEVT1", displayName: "ADCDEVT1" },
]
let XBAR_CLBMuxConfig_MUX10 = [
	{ name: "XBAR_CLB_MUX10_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_CLB_MUX10_SD2FLT3_COMPZ", displayName: "SD2FLT3_COMPZ" },
]
let XBAR_CLBMuxConfig_MUX11 = [
	{ name: "XBAR_CLB_MUX11_INPUTXBAR1_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_CLB_MUX11_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_CLB_MUX11_ADCDEVT2", displayName: "ADCDEVT2" },
]
let XBAR_CLBMuxConfig_MUX12 = [
	{ name: "XBAR_CLB_MUX12_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_CLB_MUX12_SD2FLT4_COMPZ", displayName: "SD2FLT4_COMPZ" },
]
let XBAR_CLBMuxConfig_MUX13 = [
	{ name: "XBAR_CLB_MUX13_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_CLB_MUX13_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_CLB_MUX13_ADCDEVT3", displayName: "ADCDEVT3" },
]
let XBAR_CLBMuxConfig_MUX14 = [
	{ name: "XBAR_CLB_MUX14_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_CLB_MUX14_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
]
let XBAR_CLBMuxConfig_MUX15 = [
	{ name: "XBAR_CLB_MUX15_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_CLB_MUX15_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_CLB_MUX15_ADCDEVT4", displayName: "ADCDEVT4" },
]
let XBAR_CLBMuxConfig_MUX16 = [
	{ name: "XBAR_CLB_MUX16_SD1FLT1_COMPH", displayName: "SD1FLT1_COMPH" },
	{ name: "XBAR_CLB_MUX16_SD1FLT1_COMPH_OR_COMPL", displayName: "SD1FLT_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX16_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_CLB_MUX16_FSIA_RX_TRIG3", displayName: "FSIA RX TRIG3" },
]
let XBAR_CLBMuxConfig_MUX17 = [
	{ name: "XBAR_CLB_MUX17_SD1FLT1_COMPL", displayName: "SD1FLT1_COMPL" },
	{ name: "XBAR_CLB_MUX17_INPUTXBAR1_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_CLB_MUX17_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_CLB_MUX17_CLAHALT", displayName: "CLAHALT" },
]
let XBAR_CLBMuxConfig_MUX18 = [
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPH", displayName: "SD1FLT2_COMPH" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPH_OR_COMPL", displayName: "SD1FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_COMPZ", displayName: "SD1FLT2_COMPZ" },
	{ name: "XBAR_CLB_MUX18_SD1FLT2_DRINT", displayName: "SD1FLT2_DRINT" },
]
let XBAR_CLBMuxConfig_MUX19 = [
	{ name: "XBAR_CLB_MUX19_SD1FLT2_COMPL", displayName: "SD1FLT2_COMPL" },
	{ name: "XBAR_CLB_MUX19_INPUTXBAR1_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_CLB_MUX19_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_CLB_MUX19_ERRORSTS", displayName: "ERRORSTS" },
]
let XBAR_CLBMuxConfig_MUX20 = [
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPH", displayName: "SD1FLT3_COMPH" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPH_OR_COMPL", displayName: "SD1FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_COMPZ", displayName: "SD1FLT3_COMPZ" },
	{ name: "XBAR_CLB_MUX20_SD1FLT3_DRINT", displayName: "SD1FLT3_DRINT" },
]
let XBAR_CLBMuxConfig_MUX21 = [
	{ name: "XBAR_CLB_MUX21_SD1FLT3_COMPL", displayName: "SD1FLT3_COMPL" },
	{ name: "XBAR_CLB_MUX21_INPUTXBAR1_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_CLB_MUX21_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_CLB_MUX21_SD1FLT1_DRINT", displayName: "SD1FLT1_DRINT" },
]
let XBAR_CLBMuxConfig_MUX22 = [
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPH", displayName: "SD1FLT4_COMPH" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPH_OR_COMPL", displayName: "SD1FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_COMPZ", displayName: "SD1FLT4_COMPZ" },
	{ name: "XBAR_CLB_MUX22_SD1FLT4_DRINT", displayName: "SD1FLT4_DRINT" },
]
let XBAR_CLBMuxConfig_MUX23 = [
	{ name: "XBAR_CLB_MUX23_SD1FLT4_COMPL", displayName: "SD1FLT4_COMPL" },
	{ name: "XBAR_CLB_MUX23_INPUTXBAR1_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_CLB_MUX23_ADCEEVT4", displayName: "ADCEEVT4" },
]
let XBAR_CLBMuxConfig_MUX24 = [
	{ name: "XBAR_CLB_MUX24_SD2FLT1_COMPH", displayName: "SD2FLT1_COMPH" },
	{ name: "XBAR_CLB_MUX24_SD2FLT1_COMPH_OR_COMPL", displayName: "SD2FLT1_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX24_CPU1_ERADEVT8", displayName: "CPU1 ERADEVT8" },
	{ name: "XBAR_CLB_MUX24_SD2FLT1_DRINT", displayName: "SD2FLT1_DRINT" },
]
let XBAR_CLBMuxConfig_MUX25 = [
	{ name: "XBAR_CLB_MUX25_SD2FLT1_COMPL", displayName: "SD2FLT1_COMPL" },
	{ name: "XBAR_CLB_MUX25_INPUTXBAR1_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_CLB_MUX25_MCANA_FEVT0", displayName: "MCANA FEVT0" },
]
let XBAR_CLBMuxConfig_MUX26 = [
	{ name: "XBAR_CLB_MUX26_SD2FLT2_COMPH", displayName: "SD2FLT2_COMPH" },
	{ name: "XBAR_CLB_MUX26_SD2FLT2_COMPH_OR_COMPL", displayName: "SD2FLT2_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX26_CPU1_ERADEVT9", displayName: "CPU1 ERADEVT9" },
]
let XBAR_CLBMuxConfig_MUX27 = [
	{ name: "XBAR_CLB_MUX27_SD2FLT2_COMPL", displayName: "SD2FLT2_COMPL" },
	{ name: "XBAR_CLB_MUX27_INPUTXBAR1_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_CLB_MUX27_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_CLB_MUX27_SD2FLT2_DRINT", displayName: "SD2FLT2_DRINT" },
]
let XBAR_CLBMuxConfig_MUX28 = [
	{ name: "XBAR_CLB_MUX28_SD2FLT3_COMPH", displayName: "SD2FLT3_COMPH" },
	{ name: "XBAR_CLB_MUX28_SD2FLT3_COMPH_OR_COMPL", displayName: "SD2FLT3_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX28_CPU1_ERADEVT10", displayName: "CPU1 ERADEVT10" },
]
let XBAR_CLBMuxConfig_MUX29 = [
	{ name: "XBAR_CLB_MUX29_SD2FLT3_COMPL", displayName: "SD2FLT3_COMPL" },
	{ name: "XBAR_CLB_MUX29_INPUTXBAR1_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_CLB_MUX29_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_CLB_MUX29_SD2FLT3_DRINT", displayName: "SD2FLT3_DRINT" },
]
let XBAR_CLBMuxConfig_MUX30 = [
	{ name: "XBAR_CLB_MUX30_SD2FLT4_COMPH", displayName: "SD2FLT4_COMPH" },
	{ name: "XBAR_CLB_MUX30_SD2FLT4_COMPH_OR_COMPL", displayName: "SD2FLT4_COMPH_OR_COMPL" },
	{ name: "XBAR_CLB_MUX30_CPU1_ERADEVT11", displayName: "CPU1 ERADEVT11" },
]
let XBAR_CLBMuxConfig_MUX31 = [
	{ name: "XBAR_CLB_MUX31_SD2FLT4_COMPL", displayName: "SD2FLT4_COMPL" },
	{ name: "XBAR_CLB_MUX31_INPUTXBAR1_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_CLB_MUX31_ERRORSTS", displayName: "ERRORSTS" },
	{ name: "XBAR_CLB_MUX31_SD2FLT4_DRINT", displayName: "SD2FLT4_DRINT" },
]
let XBAR_CLBMuxConfig_All_MUXES = [
	XBAR_CLBMuxConfig_MUX00,
	XBAR_CLBMuxConfig_MUX01,
	XBAR_CLBMuxConfig_MUX02,
	XBAR_CLBMuxConfig_MUX03,
	XBAR_CLBMuxConfig_MUX04,
	XBAR_CLBMuxConfig_MUX05,
	XBAR_CLBMuxConfig_MUX06,
	XBAR_CLBMuxConfig_MUX07,
	XBAR_CLBMuxConfig_MUX08,
	XBAR_CLBMuxConfig_MUX09,
	XBAR_CLBMuxConfig_MUX10,
	XBAR_CLBMuxConfig_MUX11,
	XBAR_CLBMuxConfig_MUX12,
	XBAR_CLBMuxConfig_MUX13,
	XBAR_CLBMuxConfig_MUX14,
	XBAR_CLBMuxConfig_MUX15,
	XBAR_CLBMuxConfig_MUX16,
	XBAR_CLBMuxConfig_MUX17,
	XBAR_CLBMuxConfig_MUX18,
	XBAR_CLBMuxConfig_MUX19,
	XBAR_CLBMuxConfig_MUX20,
	XBAR_CLBMuxConfig_MUX21,
	XBAR_CLBMuxConfig_MUX22,
	XBAR_CLBMuxConfig_MUX23,
	XBAR_CLBMuxConfig_MUX24,
	XBAR_CLBMuxConfig_MUX25,
	XBAR_CLBMuxConfig_MUX26,
	XBAR_CLBMuxConfig_MUX27,
	XBAR_CLBMuxConfig_MUX28,
	XBAR_CLBMuxConfig_MUX29,
	XBAR_CLBMuxConfig_MUX30,
	XBAR_CLBMuxConfig_MUX31,
]
module.exports = {
	XBAR_MUXES: XBAR_MUXES,
	XBAR_OutputNum: XBAR_OutputNum,
	XBAR_TripNum: XBAR_TripNum,
	XBAR_AuxSigNum: XBAR_AuxSigNum,
	XBAR_InputNum: XBAR_InputNum,
	XBAR_OutputMuxConfig: XBAR_OutputMuxConfig,
	XBAR_EPWMMuxConfig: XBAR_EPWMMuxConfig,
	XBAR_CLBMuxConfig: XBAR_CLBMuxConfig,
	XBAR_InputFlag: XBAR_InputFlag,
	XBAR_OutputMuxConfig_All_MUXES: XBAR_OutputMuxConfig_All_MUXES,
	XBAR_EPWMMuxConfig_All_MUXES: XBAR_EPWMMuxConfig_All_MUXES,
	XBAR_CLBMuxConfig_All_MUXES: XBAR_CLBMuxConfig_All_MUXES,
}
