let XBARRegisters = [
	{ name: "FLG1", description: "X-Bar Input Flag Register 1", offset: "0x0",
		bits: [
			{ name: "CMPSS1_CTRIPL", description: "Input Flag for CMPSS1.CTRIPL Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CMPSS1_CTRIPH", description: "Input Flag for CMPSS1.CTRIPH Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CMPSS2_CTRIPL", description: "Input Flag for CMPSS2.CTRIPL Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CMPSS2_CTRIPH", description: "Input Flag for CMPSS2.CTRIPH Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "CMPSS3_CTRIPL", description: "Input Flag for CMPSS3.CTRIPL Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CMPSS3_CTRIPH", description: "Input Flag for CMPSS3.CTRIPH Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CMPSS4_CTRIPL", description: "Input Flag for CMPSS4.CTRIPL Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "CMPSS4_CTRIPH", description: "Input Flag for CMPSS4.CTRIPH Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "CMPSS5_CTRIPL", description: "Input Flag for CMPSS5.CTRIPL Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CMPSS5_CTRIPH", description: "Input Flag for CMPSS5.CTRIPH Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CMPSS6_CTRIPL", description: "Input Flag for CMPSS6.CTRIPL Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "CMPSS6_CTRIPH", description: "Input Flag for CMPSS6.CTRIPH Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CMPSS7_CTRIPL", description: "Input Flag for CMPSS7.CTRIPL Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CMPSS7_CTRIPH", description: "Input Flag for CMPSS7.CTRIPH Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CMPSS8_CTRIPL", description: "Input Flag for CMPSS8.CTRIPL Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CMPSS8_CTRIPH", description: "Input Flag for CMPSS8.CTRIPH Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CMPSS1_CTRIPOUTL", description: "Input Flag for CMPSS1.CTRIPOUTL Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CMPSS1_CTRIPOUTH", description: "Input Flag for CMPSS1.CTRIPOUTH Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CMPSS2_CTRIPOUTL", description: "Input Flag for CMPSS2.CTRIPOUTL Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CMPSS2_CTRIPOUTH", description: "Input Flag for CMPSS2.CTRIPOUTH Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CMPSS3_CTRIPOUTL", description: "Input Flag for CMPSS3.CTRIPOUTL Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CMPSS3_CTRIPOUTH", description: "Input Flag for CMPSS3.CTRIPOUTH Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CMPSS4_CTRIPOUTL", description: "Input Flag for CMPSS4.CTRIPOUTL Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CMPSS4_CTRIPOUTH", description: "Input Flag for CMPSS4.CTRIPOUTH Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CMPSS5_CTRIPOUTL", description: "Input Flag for CMPSS5.CTRIPOUTL Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CMPSS5_CTRIPOUTH", description: "Input Flag for CMPSS5.CTRIPOUTH Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CMPSS6_CTRIPOUTL", description: "Input Flag for CMPSS6.CTRIPOUTL Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CMPSS6_CTRIPOUTH", description: "Input Flag for CMPSS6.CTRIPOUTH Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CMPSS7_CTRIPOUTL", description: "Input Flag for CMPSS7.CTRIPOUTL Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CMPSS7_CTRIPOUTH", description: "Input Flag for CMPSS7.CTRIPOUTH Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CMPSS8_CTRIPOUTL", description: "Input Flag for CMPSS8.CTRIPOUTL Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CMPSS8_CTRIPOUTH", description: "Input Flag for CMPSS8.CTRIPOUTH Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG2", description: "X-Bar Input Flag Register 2", offset: "0x2",
		bits: [
			{ name: "INPUT1", description: "Input Flag for INPUT1 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "INPUT2", description: "Input Flag for INPUT2 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "INPUT3", description: "Input Flag for INPUT3 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "INPUT4", description: "Input Flag for INPUT4 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "INPUT5", description: "Input Flag for INPUT5 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "INPUT6", description: "Input Flag for INPUT6 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "ADCSOCA", description: "Input Flag for ADCSOCA Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "ADCSOCB", description: "Input Flag for ADCSOCB Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "INPUT7", description: "Input Flag for INPUT7 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "INPUT8", description: "Input Flag for INPUT8 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "INPUT9", description: "Input Flag for INPUT9 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "INPUT10", description: "Input Flag for INPUT10\ Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "INPUT11", description: "Input Flag for INPUT11 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INPUT12", description: "Input Flag for INPUT12 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INPUT13", description: "Input Flag for INPUT13 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INPUT14", description: "Input Flag for INPUT14 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ECAP1_OUT", description: "Input Flag for ECAP1.OUT Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ECAP2_OUT", description: "Input Flag for ECAP2.OUT Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ECAP3_OUT", description: "Input Flag for ECAP3.OUT Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ECAP4_OUT", description: "Input Flag for ECAP4.OUT Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ECAP5_OUT", description: "Input Flag for ECAP5.OUT Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ECAP6_OUT", description: "Input Flag for ECAP6.OUT Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "EXTSYNCOUT", description: "Input Flag for EXTSYNCOUT Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ADCAEVT1", description: "Input Flag for ADCAEVT1 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ADCAEVT2", description: "Input Flag for ADCAEVT2 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ADCAEVT3", description: "Input Flag for ADCAEVT3 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ADCAEVT4", description: "Input Flag for ADCAEVT4 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ADCBEVT1", description: "Input Flag for ADCBEVT1 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ADCBEVT2", description: "Input Flag for ADCBEVT2 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ADCBEVT3", description: "Input Flag for ADCBEVT3 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ADCBEVT4", description: "Input Flag for ADCBEVT4 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ADCCEVT1", description: "Input Flag for ADCCEVT1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG3", description: "X-Bar Input Flag Register 3", offset: "0x4",
		bits: [
			{ name: "ADCCEVT2", description: "Input Flag for ADCCEVT2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ADCCEVT3", description: "Input Flag for ADCCEVT3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ADCCEVT4", description: "Input Flag for ADCCEVT4 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "SD1FLT1_COMPL", description: "Input Flag for SD1FLT1.COMPL Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "SD1FLT1_COMPH", description: "Input Flag for SD1FLT1.COMPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "SD1FLT2_COMPL", description: "Input Flag for SD1FLT2.COMPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "SD1FLT2_COMPH", description: "Input Flag for SD1FLT2.COMPH Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "SD1FLT3_COMPL", description: "Input Flag for SD1FLT3.COMPL Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "SD1FLT3_COMPH", description: "Input Flag for SD1FLT3.COMPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "SD1FLT4_COMPL", description: "Input Flag for SD1FLT4.COMPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "SD1FLT4_COMPH", description: "Input Flag for SD1FLT4.COMPH Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "SD2FLT1_COMPL", description: "Input Flag for SD2FLT1.COMPL Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "SD2FLT1_COMPH", description: "Input Flag for SD2FLT1.COMPH Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "SD2FLT2_COMPL", description: "Input Flag for SD2FLT2.COMPL Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "SD2FLT2_COMPH", description: "Input Flag for SD2FLT2.COMPH Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "SD2FLT3_COMPL", description: "Input Flag for SD2FLT3.COMPL Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "SD2FLT3_COMPH", description: "Input Flag for SD2FLT3.COMPH Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "SD2FLT4_COMPL", description: "Input Flag for SD2FLT4.COMPL Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "SD2FLT4_COMPH", description: "Input Flag for SD2FLT4.COMPH Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ECAP7_OUT", description: "Input Flag for ECAP7.OUT Signal", size: "1", shift: "23", mask: "0x800000" },
		]
	},
	{ name: "FLG4", description: "X-Bar Input Flag Register 4", offset: "0x6",
		bits: [
			{ name: "MCANA_FEVT0", description: "Input Flag for MCANA_FEVT0 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "MCANA_FEVT1", description: "Input Flag for MCANA_FEVT1 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "MCANA_FEVT2", description: "Input Flag for MCANA_FEVT2 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CLB1_OUT4", description: "Input Flag for CLB1_4.1 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CLB1_OUT5", description: "Input Flag for CLB1_5.1 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CLB2_OUT4", description: "Input Flag for CLB2_4.1 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CLB2_OUT5", description: "Input Flag for CLB2_5.1 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CLB3_OUT4", description: "Input Flag for CLB3_4.1 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CLB3_OUT5", description: "Input Flag for CLB3_5.1 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CLB4_OUT4", description: "Input Flag for CLB4_4.1 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CLB4_OUT5", description: "Input Flag for CLB4_5.1 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CLB5_OUT4", description: "Input Latch for CLB5_OUT4 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CLB5_OUT5", description: "Input Latch for CLB5_OUT5 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CLB6_OUT4", description: "Input Latch for CLB6_OUT4 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CLB6_OUT5", description: "Input Latch for CLB6_OUT5 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ERRORSTS_ERROR", description: "Input Latch for ERRORSTS_ERROR Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ECATSYNC0", description: "Input Latch for ECATSYNC0 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ECATSYNC1", description: "Input Latch for ECATSYNC1 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CLAHALT", description: "Input Latch for CLAHALT Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG5", description: "X-Bar Input Flag Register 5", offset: "0x8",
		bits: [
			{ name: "EPWM1_TRIPOUT", description: "Input Flag for EPWM1_TRIPOUT Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_TRIPOUT", description: "Input Flag for EPWM2_TRIPOUT Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_TRIPOUT", description: "Input Flag for EPWM3_TRIPOUT Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_TRIPOUT", description: "Input Flag for EPWM4_TRIPOUT Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_TRIPOUT", description: "Input Flag for EPWM5_TRIPOUT Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_TRIPOUT", description: "Input Flag for EPWM6_TRIPOUT Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_TRIPOUT", description: "Input Flag for EPWM7_TRIPOUT Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_TRIPOUT", description: "Input Flag for EPWM8_TRIPOUT Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_TRIPOUT", description: "Input Flag for EPWM9_TRIPOUT Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_TRIPOUT", description: "Input Flag for EPWM10_TRIPOUT Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_TRIPOUT", description: "Input Flag for EPWM11_TRIPOUT Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_TRIPOUT", description: "Input Flag for EPWM12_TRIPOUT Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_TRIPOUT", description: "Input Flag for EPWM13_TRIPOUT Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_TRIPOUT", description: "Input Flag for EPWM14_TRIPOUT Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_TRIPOUT", description: "Input Flag for EPWM15_TRIPOUT Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_TRIPOUT", description: "Input Flag for EPWM16_TRIPOUT Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_TRIPOUT", description: "Input Flag for EPWM17_TRIPOUT Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_TRIPOUT", description: "Input Flag for EPWM18_TRIPOUT Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "FLG6", description: "X-Bar Input Flag Register 6", offset: "0xA",
		bits: [
			{ name: "EPWM1_DEL_TRIP", description: "Input Flag for EPWM1_DEL_TRIP Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_DEL_TRIP", description: "Input Flag for EPWM2_DEL_TRIP Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_DEL_TRIP", description: "Input Flag for EPWM3_DEL_TRIP Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_DEL_TRIP", description: "Input Flag for EPWM4_DEL_TRIP Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_DEL_TRIP", description: "Input Flag for EPWM5_DEL_TRIP Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_DEL_TRIP", description: "Input Flag for EPWM6_DEL_TRIP Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_DEL_TRIP", description: "Input Flag for EPWM7_DEL_TRIP Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_DEL_TRIP", description: "Input Flag for EPWM8_DEL_TRIP Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_DEL_TRIP", description: "Input Flag for EPWM9_DEL_TRIP Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_DEL_TRIP", description: "Input Flag for EPWM10_DEL_TRIP Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_DEL_TRIP", description: "Input Flag for EPWM11_DEL_TRIP Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_DEL_TRIP", description: "Input Flag for EPWM12_DEL_TRIP Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_DEL_TRIP", description: "Input Flag for EPWM13_DEL_TRIP Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_DEL_TRIP", description: "Input Flag for EPWM14_DEL_TRIP Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_DEL_TRIP", description: "Input Flag for EPWM15_DEL_TRIP Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_DEL_TRIP", description: "Input Flag for EPWM16_DEL_TRIP Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_DEL_TRIP", description: "Input Flag for EPWM17_DEL_TRIP Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_DEL_TRIP", description: "Input Flag for EPWM18_DEL_TRIP Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "FLG7", description: "X-Bar Input Flag Register 7", offset: "0xC",
		bits: [
			{ name: "EPWM1_DEL_ACTIVE", description: "Input Flag for EPWM1_DEL_ACTIVE Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_DEL_ACTIVE", description: "Input Flag for EPWM2_DEL_ACTIVE Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_DEL_ACTIVE", description: "Input Flag for EPWM3_DEL_ACTIVE Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_DEL_ACTIVE", description: "Input Flag for EPWM4_DEL_ACTIVE Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_DEL_ACTIVE", description: "Input Flag for EPWM5_DEL_ACTIVE Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_DEL_ACTIVE", description: "Input Flag for EPWM6_DEL_ACTIVE Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_DEL_ACTIVE", description: "Input Flag for EPWM7_DEL_ACTIVE Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_DEL_ACTIVE", description: "Input Flag for EPWM8_DEL_ACTIVE Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_DEL_ACTIVE", description: "Input Flag for EPWM9_DEL_ACTIVE Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_DEL_ACTIVE", description: "Input Flag for EPWM10_DEL_ACTIVE Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_DEL_ACTIVE", description: "Input Flag for EPWM11_DEL_ACTIVE Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_DEL_ACTIVE", description: "Input Flag for EPWM12_DEL_ACTIVE Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_DEL_ACTIVE", description: "Input Flag for EPWM13_DEL_ACTIVE Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_DEL_ACTIVE", description: "Input Flag for EPWM14_DEL_ACTIVE Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_DEL_ACTIVE", description: "Input Flag for EPWM15_DEL_ACTIVE Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_DEL_ACTIVE", description: "Input Flag for EPWM16_DEL_ACTIVE Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_DEL_ACTIVE", description: "Input Flag for EPWM17_DEL_ACTIVE Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_DEL_ACTIVE", description: "Input Flag for EPWM18_DEL_ACTIVE Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "FLG8", description: "X-Bar Input Flag Register 8", offset: "0xE",
		bits: [
			{ name: "ETPWM1_A0_SCLK", description: "Input Flag for ETPWM1_A0_sclk Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ETPWM1_B0_SCLK", description: "Input Flag for ETPWM1_B0_sclk Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ETPWM2_A0_SCLK", description: "Input Flag for ETPWM2_A0_sclk Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "ETPWM2_B0_SCLK", description: "Input Flag for ETPWM2_B0_sclk Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "ETPWM3_A0_SCLK", description: "Input Flag for ETPWM3_A0_sclk Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "ETPWM3_B0_SCLK", description: "Input Flag for ETPWM3_B0_sclk Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "ETPWM4_A0_SCLK", description: "Input Flag for ETPWM4_A0_sclk Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "ETPWM4_B0_SCLK", description: "Input Flag for ETPWM4_B0_sclk Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "ETPWM5_A0_SCLK", description: "Input Flag for ETPWM5_A0_sclk Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "ETPWM5_B0_SCLK", description: "Input Flag for ETPWM5_B0_sclk Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "ETPWM6_A0_SCLK", description: "Input Flag for ETPWM6_A0_sclk Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "ETPWM6_B0_SCLK", description: "Input Flag for ETPWM6_B0_sclk Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ETPWM7_A0_SCLK", description: "Input Flag for ETPWM7_A0_sclk Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ETPWM7_B0_SCLK", description: "Input Flag for ETPWM7_B0_sclk Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ETPWM8_A0_SCLK", description: "Input Flag for ETPWM8_A0_sclk Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ETPWM8_B0_SCLK", description: "Input Flag for ETPWM8_B0_sclk Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ETPWM9_A0_SCLK", description: "Input Flag for ETPWM9_A0_sclk Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ETPWM9_B0_SCLK", description: "Input Flag for ETPWM9_B0_sclk Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ETPWM10_A0_SCLK", description: "Input Flag for ETPWM10_A0_sclk Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ETPWM10_B0_SCLK", description: "Input Flag for ETPWM10_B0_sclk Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ETPWM11_A0_SCLK", description: "Input Flag for ETPWM11_A0_sclk Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ETPWM11_B0_SCLK", description: "Input Flag for ETPWM11_B0_sclk Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ETPWM12_A0_SCLK", description: "Input Flag for ETPWM12_A0_sclk Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ETPWM12_B0_SCLK", description: "Input Flag for ETPWM12_B0_sclk Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ETPWM13_A0_SCLK", description: "Input Flag for ETPWM13_A0_sclk Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ETPWM13_B0_SCLK", description: "Input Flag for ETPWM13_B0_sclk Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ETPWM14_A0_SCLK", description: "Input Flag for ETPWM14_A0_sclk Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ETPWM14_B0_SCLK", description: "Input Flag for ETPWM14_B0_sclk Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ETPWM15_A0_SCLK", description: "Input Flag for ETPWM15_A0_sclk Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ETPWM15_B0_SCLK", description: "Input Flag for ETPWM15_B0_sclk Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ETPWM16_A0_SCLK", description: "Input Flag for ETPWM16_A0_sclk Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ETPWM16_B0_SCLK", description: "Input Flag for ETPWM16_B0_sclk Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG9", description: "X-Bar Input Flag Register 9", offset: "0x10",
		bits: [
			{ name: "ETPWM17_A0_SCLK", description: "Input Flag for ETPWM17_A0_sclk Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ETPWM17_B0_SCLK", description: "Input Flag for ETPWM17_B0_sclk Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ETPWM18_A0_SCLK", description: "Input Flag for ETPWM18_A0_sclk Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "ETPWM18_B0_SCLK", description: "Input Flag for ETPWM18_B0_sclk Signal", size: "1", shift: "3", mask: "0x8" },
		]
	},
	{ name: "FLG10", description: "X-Bar Input Flag Register 10", offset: "0x12",
		bits: [
			{ name: "MDL1_OUTA", description: "Input Flag for MDL1_OUTA Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "MDL1_OUTB", description: "Input Flag for MDL1_OUTB Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "MDL2_OUTA", description: "Input Flag for MDL2_OUTA Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "MDL2_OUTB", description: "Input Flag for MDL2_OUTB Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "MDL3_OUTA", description: "Input Flag for MDL3_OUTA Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "MDL3_OUTB", description: "Input Flag for MDL3_OUTB Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "MDL4_OUTA", description: "Input Flag for MDL4_OUTA Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "MDL4_OUTB", description: "Input Flag for MDL4_OUTB Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "MDL5_OUTA", description: "Input Flag for MDL5_OUTA Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "MDL5_OUTB", description: "Input Flag for MDL5_OUTB Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "MDL6_OUTA", description: "Input Flag for MDL6_OUTA Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "MDL6_OUTB", description: "Input Flag for MDL6_OUTB Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "MDL7_OUTA", description: "Input Flag for MDL7_OUTA Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MDL7_OUTB", description: "Input Flag for MDL7_OUTB Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MDL8_OUTA", description: "Input Flag for MDL8_OUTA Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MDL8_OUTB", description: "Input Flag for MDL8_OUTB Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MDL9_OUTA", description: "Input Flag for MDL9_OUTA Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MDL9_OUTB", description: "Input Flag for MDL9_OUTB Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MDL10_OUTA", description: "Input Flag for MDL10_OUTA Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MDL10_OUTB", description: "Input Flag for MDL10_OUTB Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MDL11_OUTA", description: "Input Flag for MDL11_OUTA Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MDL11_OUTB", description: "Input Flag for MDL11_OUTB Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MDL12_OUTA", description: "Input Flag for MDL12_OUTA Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MDL12_OUTB", description: "Input Flag for MDL12_OUTB Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MDL13_OUTA", description: "Input Flag for MDL13_OUTA Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MDL13_OUTB", description: "Input Flag for MDL13_OUTB Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MDL14_OUTA", description: "Input Flag for MDL14_OUTA Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MDL14_OUTB", description: "Input Flag for MDL14_OUTB Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MDL15_OUTA", description: "Input Flag for MDL15_OUTA Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MDL15_OUTB", description: "Input Flag for MDL15_OUTB Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MDL16_OUTA", description: "Input Flag for MDL16_OUTA Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MDL16_OUTB", description: "Input Flag for MDL16_OUTB Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG11", description: "X-Bar Input Flag Register 11", offset: "0x14",
		bits: [
			{ name: "MDL17_OUTA", description: "Input Flag for MDL17_OUTA Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "MDL17_OUTB", description: "Input Flag for MDL17_OUTB Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "MDL18_OUTA", description: "Input Flag for MDL18_OUTA Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "MDL18_OUTB", description: "Input Flag for MDL18_OUTB Signal", size: "1", shift: "3", mask: "0x8" },
		]
	},
	{ name: "FLG12", description: "X-Bar Input Flag Register 12", offset: "0x16",
		bits: [
			{ name: "CLB1_OUT0", description: "Input Flag for CLB1_OUT0 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CLB1_OUT1", description: "Input Flag for CLB1_OUT1 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CLB1_OUT2", description: "Input Flag for CLB1_OUT2 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CLB1_OUT3", description: "Input Flag for CLB1_OUT3 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "CLB1_OUT6", description: "Input Flag for CLB1_OUT6 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CLB1_OUT7", description: "Input Flag for CLB1_OUT7 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CLB2_OUT0", description: "Input Flag for CLB2_OUT0 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "CLB2_OUT1", description: "Input Flag for CLB2_OUT1 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "CLB2_OUT2", description: "Input Flag for CLB2_OUT2 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CLB2_OUT3", description: "Input Flag for CLB2_OUT3 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CLB2_OUT6", description: "Input Flag for CLB2_OUT6 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "CLB2_OUT7", description: "Input Flag for CLB2_OUT7 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CLB3_OUT0", description: "Input Flag for CLB3_OUT0 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CLB3_OUT1", description: "Input Flag for CLB3_OUT1 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CLB3_OUT2", description: "Input Flag for CLB3_OUT2 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CLB3_OUT3", description: "Input Flag for CLB3_OUT3 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CLB3_OUT6", description: "Input Flag for CLB3_OUT6 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CLB3_OUT7", description: "Input Flag for CLB3_OUT7 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CLB4_OUT0", description: "Input Flag for CLB4_OUT0 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CLB4_OUT1", description: "Input Flag for CLB4_OUT1 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CLB4_OUT2", description: "Input Flag for CLB4_OUT2 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CLB4_OUT3", description: "Input Flag for CLB4_OUT3 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CLB4_OUT6", description: "Input Flag for CLB4_OUT6 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CLB4_OUT7", description: "Input Flag for CLB4_OUT7 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CLB5_OUT0", description: "Input Flag for CLB5_OUT0 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CLB5_OUT1", description: "Input Flag for CLB5_OUT1 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CLB5_OUT2", description: "Input Flag for CLB5_OUT2 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CLB5_OUT3", description: "Input Flag for CLB5_OUT3 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CLB5_OUT6", description: "Input Flag for CLB5_OUT6 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CLB5_OUT7", description: "Input Flag for CLB5_OUT7 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CLB6_OUT0", description: "Input Flag for CLB6_OUT0 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CLB6_OUT1", description: "Input Flag for CLB6_OUT1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG13", description: "X-Bar Input Flag Register 13", offset: "0x18",
		bits: [
			{ name: "CLB6_OUT2", description: "Input Flag for CLB6_OUT2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CLB6_OUT3", description: "Input Flag for CLB6_OUT3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CLB6_OUT6", description: "Input Flag for CLB6_OUT6 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CLB6_OUT7", description: "Input Flag for CLB6_OUT7 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "XTRIPOUT1", description: "Input Flag for XTRIPOUT1 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "XTRIPOUT2", description: "Input Flag for XTRIPOUT2 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "XTRIPOUT3", description: "Input Flag for XTRIPOUT3 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "XTRIPOUT4", description: "Input Flag for XTRIPOUT4 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "XTRIPOUT5", description: "Input Flag for XTRIPOUT5 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "XTRIPOUT6", description: "Input Flag for XTRIPOUT6 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "XTRIPOUT7", description: "Input Flag for XTRIPOUT7 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "XTRIPOUT8", description: "Input Flag for XTRIPOUT8 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ADCA_EXTMUXSEL0", description: "Input Flag for ADCA_EXTMUXSEL0 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ADCA_EXTMUXSEL1", description: "Input Flag for ADCA_EXTMUXSEL1 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ADCA_EXTMUXSEL2", description: "Input Flag for ADCA_EXTMUXSEL2 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ADCA_EXTMUXSEL3", description: "Input Flag for ADCA_EXTMUXSEL3 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ADCB_EXTMUXSEL0", description: "Input Flag for ADCB_EXTMUXSEL0 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ADCB_EXTMUXSEL1", description: "Input Flag for ADCB_EXTMUXSEL1 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ADCB_EXTMUXSEL2", description: "Input Flag for ADCB_EXTMUXSEL2 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ADCB_EXTMUXSEL3", description: "Input Flag for ADCB_EXTMUXSEL3 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ADCC_EXTMUXSEL0", description: "Input Flag for ADCC_EXTMUXSEL0 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ADCC_EXTMUXSEL1", description: "Input Flag for ADCC_EXTMUXSEL1 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ADCC_EXTMUXSEL2", description: "Input Flag for ADCC_EXTMUXSEL2 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ADCC_EXTMUXSEL3", description: "Input Flag for ADCC_EXTMUXSEL3 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "PIEERR", description: "Input Flag for PIEERR Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ECCERR", description: "Input Flag for ECCERR Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "EPG1_EPGOUT0", description: "Input Flag for EPG1_EPGOUT0 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "EPG1_EPGOUT1", description: "Input Flag for EPG1_EPGOUT1 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "EPG1_EPGOUT2", description: "Input Flag for EPG1_EPGOUT2 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "EPG1_EPGOUT3", description: "Input Flag for EPG1_EPGOUT3 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG14", description: "X-Bar Input Flag Register 14", offset: "0x1A",
		bits: [
			{ name: "SD3FLT1_COMPH", description: "Input Flag for SD3FLT1_COMPH Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "SD3FLT1_COMPL", description: "Input Flag for SD3FLT1_COMPL Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "SD3FLT2_COMPH", description: "Input Flag for SD3FLT2_COMPH Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "SD3FLT2_COMPL", description: "Input Flag for SD3FLT2_COMPL Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "SD3FLT3_COMPH", description: "Input Flag for SD3FLT3_COMPH Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "SD3FLT3_COMPL", description: "Input Flag for SD3FLT3_COMPL Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "SD3FLT4_COMPH", description: "Input Flag for SD3FLT4_COMPH Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "SD3FLT4_COMPL", description: "Input Flag for SD3FLT4_COMPL Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "SD4FLT1_COMPH", description: "Input Flag for SD4FLT1_COMPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "SD4FLT1_COMPL", description: "Input Flag for SD4FLT1_COMPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "SD4FLT2_COMPH", description: "Input Flag for SD4FLT2_COMPH Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "SD4FLT2_COMPL", description: "Input Flag for SD4FLT2_COMPL Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "SD4FLT3_COMPH", description: "Input Flag for SD4FLT3_COMPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "SD4FLT3_COMPL", description: "Input Flag for SD4FLT3_COMPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "SD4FLT4_COMPH", description: "Input Flag for SD4FLT4_COMPH Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "SD4FLT4_COMPL", description: "Input Flag for SD4FLT4_COMPL Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "INPUTXBAR2_INPUT10", description: "Input Flag for INPUTXBAR2_INPUT10 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "INPUTXBAR2_INPUT11", description: "Input Flag for INPUTXBAR2_INPUT11 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "INPUTXBAR2_INPUT12", description: "Input Flag for INPUTXBAR2_INPUT12 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "INPUTXBAR2_INPUT13", description: "Input Flag for INPUTXBAR2_INPUT13 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "INPUTXBAR2_INPUT14", description: "Input Flag for INPUTXBAR2_INPUT14 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "INPUTXBAR2_INPUT7", description: "Input Flag for INPUTXBAR2_INPUT7 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "INPUTXBAR2_INPUT8", description: "Input Flag for INPUTXBAR2_INPUT8 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "INPUTXBAR2_INPUT9", description: "Input Flag for INPUTXBAR2_INPUT9 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MCANB_FEVT0", description: "Input Flag for MCANB_FEVT0 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MCANB_FEVT1", description: "Input Flag for MCANB_FEVT1 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MCANB_FEVT2", description: "Input Flag for MCANB_FEVT2 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "FSIA_RX_TRIG1", description: "Input Flag for FSIA_RX_TRIG1 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "FSIB_RX_TRIG1", description: "Input Flag for FSIB_RX_TRIG1 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "FSIC_RX_TRIG1", description: "Input Flag for FSIC_RX_TRIG1 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "FSID_RX_TRIG1", description: "Input Flag for FSID_RX_TRIG1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "FLG15", description: "X-Bar Input Flag Register 15", offset: "0x1C",
		bits: [
			{ name: "FSIRXA_TRIG_2", description: "Input Flag for FSIRXA_TRIG_2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "FSIRXA_TRIG_3", description: "Input Flag for FSIRXA_TRIG_3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "FSIRXB_TRIG_2", description: "Input Flag for FSIRXB_TRIG_2 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "FSIRXB_TRIG_3", description: "Input Flag for FSIRXB_TRIG_3 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "FSIRXC_TRIG_2", description: "Input Flag for FSIRXC_TRIG_2 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "FSIRXC_TRIG_3", description: "Input Flag for FSIRXC_TRIG_3 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "FSIRXD_TRIG_2", description: "Input Flag for FSIRXD_TRIG_2 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "FSIRXD_TRIG_3", description: "Input Flag for FSIRXD_TRIG_3 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "ECAP1_TRIPOUT", description: "Input Flag for ECAP1_TRIPOUT Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "ECAP2_TRIPOUT", description: "Input Flag for ECAP2_TRIPOUT Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "ECAP3_TRIPOUT", description: "Input Flag for ECAP3_TRIPOUT Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "ECAP4_TRIPOUT", description: "Input Flag for ECAP4_TRIPOUT Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ECAP5_TRIPOUT", description: "Input Flag for ECAP5_TRIPOUT Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ECAP6_TRIPOUT", description: "Input Flag for ECAP6_TRIPOUT Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CPU1ERADEVT10", description: "Input Flag for CPU1ERADEVT10 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CPU1ERADEVT11", description: "Input Flag for CPU1ERADEVT11 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CPU1ERADEVT8", description: "Input Flag for CPU1ERADEVT8 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CPU1ERADEVT9", description: "Input Flag for CPU1ERADEVT9 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CPU1_ADCCHECKEVT1", description: "Input Flag for CPU1_ADCCHECKEVT1 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CPU1_ADCCHECKEVT2", description: "Input Flag for CPU1_ADCCHECKEVT2 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CPU1_ADCCHECKEVT3", description: "Input Flag for CPU1_ADCCHECKEVT3 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CPU1_ADCCHECKEVT4", description: "Input Flag for CPU1_ADCCHECKEVT4 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CPU2ERADEVT10", description: "Input Flag for CPU2ERADEVT10 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CPU2ERADEVT11", description: "Input Flag for CPU2ERADEVT11 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CPU2ERADEVT8", description: "Input Flag for CPU2ERADEVT8 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CPU2ERADEVT9", description: "Input Flag for CPU2ERADEVT9 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CPU2_ADCCHECKEVT1", description: "Input Flag for CPU2_ADCCHECKEVT1 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CPU2_ADCCHECKEVT2", description: "Input Flag for CPU2_ADCCHECKEVT2 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CPU2_ADCCHECKEVT3", description: "Input Flag for CPU2_ADCCHECKEVT3 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CPU2_ADCCHECKEVT4", description: "Input Flag for CPU2_ADCCHECKEVT4 Signal", size: "1", shift: "29", mask: "0x20000000" },
		]
	},
	{ name: "FLG16", description: "X-Bar Input Flag Register 16", offset: "0x1E",
		bits: [
			{ name: "CMPSS9_CTRIPH", description: "Input Flag for CMPSS9_CTRIPH Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CMPSS9_CTRIPL", description: "Input Flag for CMPSS9_CTRIPL Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CMPSS9_CTRIPOUTH", description: "Input Flag for CMPSS9_CTRIPOUTH Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CMPSS9_CTRIPOUTL", description: "Input Flag for CMPSS9_CTRIPOUTL Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "CMPSS10_CTRIPH", description: "Input Flag for CMPSS10_CTRIPH Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CMPSS10_CTRIPL", description: "Input Flag for CMPSS10_CTRIPL Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CMPSS10_CTRIPOUTH", description: "Input Flag for CMPSS10_CTRIPOUTH Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "CMPSS10_CTRIPOUTL", description: "Input Flag for CMPSS10_CTRIPOUTL Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "CMPSS11_CTRIPH", description: "Input Flag for CMPSS11_CTRIPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CMPSS11_CTRIPL", description: "Input Flag for CMPSS11_CTRIPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CMPSS11_CTRIPOUTH", description: "Input Flag for CMPSS11_CTRIPOUTH Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "CMPSS11_CTRIPOUTL", description: "Input Flag for CMPSS11_CTRIPOUTL Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CMPSS12_CTRIPH", description: "Input Flag for CMPSS12_CTRIPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CMPSS12_CTRIPL", description: "Input Flag for CMPSS12_CTRIPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CMPSS12_CTRIPOUTH", description: "Input Flag for CMPSS12_CTRIPOUTH Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CMPSS12_CTRIPOUTL", description: "Input Flag for CMPSS12_CTRIPOUTL Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "XCLKOUT", description: "Input Flag for XCLKOUT Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR1", description: "X-Bar Input Flag Clear Register 1", offset: "0x20",
		bits: [
			{ name: "CMPSS1_CTRIPL", description: "Input Flag Clear for CMPSS1.CTRIPL Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CMPSS1_CTRIPH", description: "Input Flag Clear for CMPSS1.CTRIPH Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CMPSS2_CTRIPL", description: "Input Flag Clear for CMPSS2.CTRIPL Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CMPSS2_CTRIPH", description: "Input Flag Clear for CMPSS2.CTRIPH Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "CMPSS3_CTRIPL", description: "Input Flag Clear for CMPSS3.CTRIPL Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CMPSS3_CTRIPH", description: "Input Flag Clear for CMPSS3.CTRIPH Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CMPSS4_CTRIPL", description: "Input Flag Clear for CMPSS4.CTRIPL Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "CMPSS4_CTRIPH", description: "Input Flag Clear for CMPSS4.CTRIPH Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "CMPSS5_CTRIPL", description: "Input Flag Clear for CMPSS5.CTRIPL Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CMPSS5_CTRIPH", description: "Input Flag Clear for CMPSS5.CTRIPH Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CMPSS6_CTRIPL", description: "Input Flag Clear for CMPSS6.CTRIPL Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "CMPSS6_CTRIPH", description: "Input Flag Clear for CMPSS6.CTRIPH Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CMPSS7_CTRIPL", description: "Input Flag Clear for CMPSS7.CTRIPL Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CMPSS7_CTRIPH", description: "Input Flag Clear for CMPSS7.CTRIPH Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CMPSS8_CTRIPL", description: "Input Flag Clear for CMPSS8.CTRIPL Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CMPSS8_CTRIPH", description: "Input Flag Clear for CMPSS8.CTRIPH Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CMPSS1_CTRIPOUTL", description: "Input Flag Clear for CMPSS1.CTRIPOUTL Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CMPSS1_CTRIPOUTH", description: "Input Flag Clear for CMPSS1.CTRIPOUTH Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CMPSS2_CTRIPOUTL", description: "Input Flag Clear for CMPSS2.CTRIPOUTL Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CMPSS2_CTRIPOUTH", description: "Input Flag Clear for CMPSS2.CTRIPOUTH Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CMPSS3_CTRIPOUTL", description: "Input Flag Clear for CMPSS3.CTRIPOUTL Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CMPSS3_CTRIPOUTH", description: "Input Flag Clear for CMPSS3.CTRIPOUTH Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CMPSS4_CTRIPOUTL", description: "Input Flag Clear for CMPSS4.CTRIPOUTL Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CMPSS4_CTRIPOUTH", description: "Input Flag Clear for CMPSS4.CTRIPOUTH Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CMPSS5_CTRIPOUTL", description: "Input Flag Clear for CMPSS5.CTRIPOUTL Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CMPSS5_CTRIPOUTH", description: "Input Flag Clear for CMPSS5.CTRIPOUTH Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CMPSS6_CTRIPOUTL", description: "Input Flag Clear for CMPSS6.CTRIPOUTL Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CMPSS6_CTRIPOUTH", description: "Input Flag Clear for CMPSS6.CTRIPOUTH Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CMPSS7_CTRIPOUTL", description: "Input Flag Clear for CMPSS7.CTRIPOUTL Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CMPSS7_CTRIPOUTH", description: "Input Flag Clear for CMPSS7.CTRIPOUTH Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CMPSS8_CTRIPOUTL", description: "Input Flag Clear for CMPSS8.CTRIPOUTL Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CMPSS8_CTRIPOUTH", description: "Input Flag Clear for CMPSS8.CTRIPOUTH Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR2", description: "X-Bar Input Flag Clear Register 2", offset: "0x22",
		bits: [
			{ name: "INPUT1", description: "Input Flag Clear for INPUT1 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "INPUT2", description: "Input Flag Clear for INPUT2 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "INPUT3", description: "Input Flag Clear for INPUT3 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "INPUT4", description: "Input Flag Clear for INPUT4 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "INPUT5", description: "Input Flag Clear for INPUT5 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "INPUT6", description: "Input Flag Clear for INPUT6 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "ADCSOCA", description: "Input Flag Clear for ADCSOCA Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "ADCSOCB", description: "Input Flag Clear for ADCSOCB Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "INPUT7", description: "Input Flag Clear for INPUT7 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "INPUT8", description: "Input Flag Clear for INPUT8 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "INPUT9", description: "Input Flag Clear for INPUT9 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "INPUT10", description: "Input Flag Clear for INPUT10 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "INPUT11", description: "Input Flag Clear for INPUT11 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INPUT12", description: "Input Flag Clear for INPUT12 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INPUT13", description: "Input Flag Clear for INPUT13 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INPUT14", description: "Input Flag Clear for INPUT14 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ECAP1_OUT", description: "Input Flag Clear for ECAP1.OUT Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ECAP2_OUT", description: "Input Flag Clear for ECAP2.OUT Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ECAP3_OUT", description: "Input Flag Clear for ECAP3.OUT Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ECAP4_OUT", description: "Input Flag Clear for ECAP4.OUT Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ECAP5_OUT", description: "Input Flag Clear for ECAP5.OUT Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ECAP6_OUT", description: "Input Flag Clear for ECAP6.OUT Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "EXTSYNCOUT", description: "Input Flag Clear for EXTSYNCOUT Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ADCAEVT1", description: "Input Flag Clear for ADCAEVT1 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ADCAEVT2", description: "Input Flag Clear for ADCAEVT2 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ADCAEVT3", description: "Input Flag Clear for ADCAEVT3 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ADCAEVT4", description: "Input Flag Clear for ADCAEVT4 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ADCBEVT1", description: "Input Flag Clear for ADCBEVT1 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ADCBEVT2", description: "Input Flag Clear for ADCBEVT2 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ADCBEVT3", description: "Input Flag Clear for ADCBEVT3 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ADCBEVT4", description: "Input Flag Clear for ADCBEVT4 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ADCCEVT1", description: "Input Flag Clear for ADCCEVT1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR3", description: "X-Bar Input Flag Clear Register 3", offset: "0x24",
		bits: [
			{ name: "ADCCEVT2", description: "Input Flag Clear for ADCCEVT2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ADCCEVT3", description: "Input Flag Clear for ADCCEVT3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ADCCEVT4", description: "Input Flag Clear for ADCCEVT4 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "SD1FLT1_COMPL", description: "Input Flag Clear for SD1FLT1.COMPL Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "SD1FLT1_COMPH", description: "Input Flag Clear for SD1FLT1.COMPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "SD1FLT2_COMPL", description: "Input Flag Clear for SD1FLT2.COMPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "SD1FLT2_COMPH", description: "Input Flag Clear for SD1FLT2.COMPH Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "SD1FLT3_COMPL", description: "Input Flag Clear for SD1FLT3.COMPL Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "SD1FLT3_COMPH", description: "Input Flag Clear for SD1FLT3.COMPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "SD1FLT4_COMPL", description: "Input Flag Clear for SD1FLT4.COMPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "SD1FLT4_COMPH", description: "Input Flag Clear for SD1FLT4.COMPH Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "SD2FLT1_COMPL", description: "Input Flag Clear for SD2FLT1.COMPL Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "SD2FLT1_COMPH", description: "Input Flag Clear for SD2FLT1.COMPH Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "SD2FLT2_COMPL", description: "Input Flag Clear for SD2FLT2.COMPL Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "SD2FLT2_COMPH", description: "Input Flag Clear for SD2FLT2.COMPH Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "SD2FLT3_COMPL", description: "Input Flag Clear for SD2FLT3.COMPL Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "SD2FLT3_COMPH", description: "Input Flag Clear for SD2FLT3.COMPH Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "SD2FLT4_COMPL", description: "Input Flag Clear for SD2FLT4.COMPL Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "SD2FLT4_COMPH", description: "Input Flag Clear for SD2FLT4.COMPH Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ECAP7_OUT", description: "Input Flag clear for ECAP7.OUT Signal", size: "1", shift: "23", mask: "0x800000" },
		]
	},
	{ name: "CLR4", description: "X-Bar Input Flag Clear Register 4", offset: "0x26",
		bits: [
			{ name: "MCANA_FEVT0", description: "Input Flag clear for MCANA_FEVT0 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "MCANA_FEVT1", description: "Input Flag clear for MCANA_FEVT1 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "MCANA_FEVT2", description: "Input Flag clear for MCANA_FEVT2 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CLB1_OUT4", description: "Input Flag clear for CLB1_4.1 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CLB1_OUT5", description: "Input Flag clear for CLB1_5.1 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CLB2_OUT4", description: "Input Flag clear for CLB2_4.1 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CLB2_OUT5", description: "Input Flag clear for CLB2_5.1 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CLB3_OUT4", description: "Input Flag clear for CLB3_4.1 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CLB3_OUT5", description: "Input Flag clear for CLB3_5.1 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CLB4_OUT4", description: "Input Flag clear for CLB4_4.1 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CLB4_OUT5", description: "Input Flag clear for CLB4_5.1 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CLB5_OUT4", description: "Input Latch clear for CLB5_OUT4 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CLB5_OUT5", description: "Input Latch clear for CLB5_OUT5 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CLB6_OUT4", description: "Input Latch clear for CLB6_OUT4 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CLB6_OUT5", description: "Input Latch clear for CLB6_OUT5 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ERRORSTS_ERROR", description: "Input Latch clear for ERRORSTS_ERROR Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ECATSYNC0", description: "Input Latch clear for ECATSYNC0 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ECATSYNC1", description: "Input Latch clear for ECATSYNC1 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CLAHALT", description: "Input Flag clear for CLAHALT Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR5", description: "X-Bar Input Flag Clear Register 5", offset: "0x28",
		bits: [
			{ name: "EPWM1_TRIPOUT", description: "Input Flag clear for EPWM1_TRIPOUT Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_TRIPOUT", description: "Input Flag clear for EPWM2_TRIPOUT Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_TRIPOUT", description: "Input Flag clear for EPWM3_TRIPOUT Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_TRIPOUT", description: "Input Flag clear for EPWM4_TRIPOUT Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_TRIPOUT", description: "Input Flag clear for EPWM5_TRIPOUT Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_TRIPOUT", description: "Input Flag clear for EPWM6_TRIPOUT Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_TRIPOUT", description: "Input Flag clear for EPWM7_TRIPOUT Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_TRIPOUT", description: "Input Flag clear for EPWM8_TRIPOUT Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_TRIPOUT", description: "Input Flag clear for EPWM9_TRIPOUT Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_TRIPOUT", description: "Input Flag clear for EPWM10_TRIPOUT Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_TRIPOUT", description: "Input Flag clear for EPWM11_TRIPOUT Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_TRIPOUT", description: "Input Flag clear for EPWM12_TRIPOUT Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_TRIPOUT", description: "Input Flag clear for EPWM13_TRIPOUT Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_TRIPOUT", description: "Input Flag clear for EPWM14_TRIPOUT Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_TRIPOUT", description: "Input Flag clear for EPWM15_TRIPOUT Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_TRIPOUT", description: "Input Flag clear for EPWM16_TRIPOUT Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_TRIPOUT", description: "Input Flag clear for EPWM17_TRIPOUT Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_TRIPOUT", description: "Input Flag clear for EPWM18_TRIPOUT Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "CLR6", description: "X-Bar Input Flag Clear Register 6", offset: "0x2A",
		bits: [
			{ name: "EPWM1_DEL_TRIP", description: "Input Flag clear for EPWM1_DEL_TRIP Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_DEL_TRIP", description: "Input Flag clear for EPWM2_DEL_TRIP Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_DEL_TRIP", description: "Input Flag clear for EPWM3_DEL_TRIP Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_DEL_TRIP", description: "Input Flag clear for EPWM4_DEL_TRIP Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_DEL_TRIP", description: "Input Flag clear for EPWM5_DEL_TRIP Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_DEL_TRIP", description: "Input Flag clear for EPWM6_DEL_TRIP Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_DEL_TRIP", description: "Input Flag clear for EPWM7_DEL_TRIP Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_DEL_TRIP", description: "Input Flag clear for EPWM8_DEL_TRIP Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_DEL_TRIP", description: "Input Flag clear for EPWM9_DEL_TRIP Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_DEL_TRIP", description: "Input Flag clear for EPWM10_DEL_TRIP Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_DEL_TRIP", description: "Input Flag clear for EPWM11_DEL_TRIP Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_DEL_TRIP", description: "Input Flag clear for EPWM12_DEL_TRIP Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_DEL_TRIP", description: "Input Flag clear for EPWM13_DEL_TRIP Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_DEL_TRIP", description: "Input Flag clear for EPWM14_DEL_TRIP Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_DEL_TRIP", description: "Input Flag clear for EPWM15_DEL_TRIP Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_DEL_TRIP", description: "Input Flag clear for EPWM16_DEL_TRIP Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_DEL_TRIP", description: "Input Flag clear for EPWM17_DEL_TRIP Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_DEL_TRIP", description: "Input Flag clear for EPWM18_DEL_TRIP Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "CLR7", description: "X-Bar Input Flag Clear Register 7", offset: "0x2C",
		bits: [
			{ name: "EPWM1_DEL_ACTIVE", description: "Input Flag clear for EPWM1_DEL_ACTIVE Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "EPWM2_DEL_ACTIVE", description: "Input Flag clear for EPWM2_DEL_ACTIVE Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "EPWM3_DEL_ACTIVE", description: "Input Flag clear for EPWM3_DEL_ACTIVE Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "EPWM4_DEL_ACTIVE", description: "Input Flag clear for EPWM4_DEL_ACTIVE Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "EPWM5_DEL_ACTIVE", description: "Input Flag clear for EPWM5_DEL_ACTIVE Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "EPWM6_DEL_ACTIVE", description: "Input Flag clear for EPWM6_DEL_ACTIVE Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "EPWM7_DEL_ACTIVE", description: "Input Flag clear for EPWM7_DEL_ACTIVE Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "EPWM8_DEL_ACTIVE", description: "Input Flag clear for EPWM8_DEL_ACTIVE Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "EPWM9_DEL_ACTIVE", description: "Input Flag clear for EPWM9_DEL_ACTIVE Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "EPWM10_DEL_ACTIVE", description: "Input Flag clear for EPWM10_DEL_ACTIVE Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "EPWM11_DEL_ACTIVE", description: "Input Flag clear for EPWM11_DEL_ACTIVE Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "EPWM12_DEL_ACTIVE", description: "Input Flag clear for EPWM12_DEL_ACTIVE Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "EPWM13_DEL_ACTIVE", description: "Input Flag clear for EPWM13_DEL_ACTIVE Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EPWM14_DEL_ACTIVE", description: "Input Flag clear for EPWM14_DEL_ACTIVE Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "EPWM15_DEL_ACTIVE", description: "Input Flag clear for EPWM15_DEL_ACTIVE Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "EPWM16_DEL_ACTIVE", description: "Input Flag clear for EPWM16_DEL_ACTIVE Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "EPWM17_DEL_ACTIVE", description: "Input Flag clear for EPWM17_DEL_ACTIVE Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "EPWM18_DEL_ACTIVE", description: "Input Flag clear for EPWM18_DEL_ACTIVE Signal", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "CLR8", description: "X-Bar Input Flag Clear Register 8", offset: "0x2E",
		bits: [
			{ name: "ETPWM1_A0_SCLK", description: "Input Flag clear for ETPWM1_A0_sclk Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ETPWM1_B0_SCLK", description: "Input Flag clear for ETPWM1_B0_sclk Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ETPWM2_A0_SCLK", description: "Input Flag clear for ETPWM2_A0_sclk Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "ETPWM2_B0_SCLK", description: "Input Flag clear for ETPWM2_B0_sclk Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "ETPWM3_A0_SCLK", description: "Input Flag clear for ETPWM3_A0_sclk Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "ETPWM3_B0_SCLK", description: "Input Flag clear for ETPWM3_B0_sclk Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "ETPWM4_A0_SCLK", description: "Input Flag clear for ETPWM4_A0_sclk Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "ETPWM4_B0_SCLK", description: "Input Flag clear for ETPWM4_B0_sclk Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "ETPWM5_A0_SCLK", description: "Input Flag clear for ETPWM5_A0_sclk Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "ETPWM5_B0_SCLK", description: "Input Flag clear for ETPWM5_B0_sclk Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "ETPWM6_A0_SCLK", description: "Input Flag clear for ETPWM6_A0_sclk Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "ETPWM6_B0_SCLK", description: "Input Flag clear for ETPWM6_B0_sclk Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ETPWM7_A0_SCLK", description: "Input Flag clear for ETPWM7_A0_sclk Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ETPWM7_B0_SCLK", description: "Input Flag clear for ETPWM7_B0_sclk Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ETPWM8_A0_SCLK", description: "Input Flag clear for ETPWM8_A0_sclk Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ETPWM8_B0_SCLK", description: "Input Flag clear for ETPWM8_B0_sclk Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ETPWM9_A0_SCLK", description: "Input Flag clear for ETPWM9_A0_sclk Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ETPWM9_B0_SCLK", description: "Input Flag clear for ETPWM9_B0_sclk Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ETPWM10_A0_SCLK", description: "Input Flag clear for ETPWM10_A0_sclk Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ETPWM10_B0_SCLK", description: "Input Flag clear for ETPWM10_B0_sclk Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ETPWM11_A0_SCLK", description: "Input Flag clear for ETPWM11_A0_sclk Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ETPWM11_B0_SCLK", description: "Input Flag clear for ETPWM11_B0_sclk Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ETPWM12_A0_SCLK", description: "Input Flag clear for ETPWM12_A0_sclk Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ETPWM12_B0_SCLK", description: "Input Flag clear for ETPWM12_B0_sclk Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ETPWM13_A0_SCLK", description: "Input Flag clear for ETPWM13_A0_sclk Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ETPWM13_B0_SCLK", description: "Input Flag clear for ETPWM13_B0_sclk Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ETPWM14_A0_SCLK", description: "Input Flag clear for ETPWM14_A0_sclk Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ETPWM14_B0_SCLK", description: "Input Flag clear for ETPWM14_B0_sclk Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ETPWM15_A0_SCLK", description: "Input Flag clear for ETPWM15_A0_sclk Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ETPWM15_B0_SCLK", description: "Input Flag clear for ETPWM15_B0_sclk Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ETPWM16_A0_SCLK", description: "Input Flag clear for ETPWM16_A0_sclk Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ETPWM16_B0_SCLK", description: "Input Flag clear for ETPWM16_B0_sclk Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR9", description: "X-Bar Input Flag Clear Register 9", offset: "0x30",
		bits: [
			{ name: "ETPWM17_A0_SCLK", description: "Input Flag clear for ETPWM17_A0_sclk Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "ETPWM17_B0_SCLK", description: "Input Flag clear for ETPWM17_B0_sclk Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "ETPWM18_A0_SCLK", description: "Input Flag clear for ETPWM18_A0_sclk Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "ETPWM18_B0_SCLK", description: "Input Flag clear for ETPWM18_B0_sclk Signal", size: "1", shift: "3", mask: "0x8" },
		]
	},
	{ name: "CLR10", description: "X-Bar Input Flag Clear Register 10", offset: "0x32",
		bits: [
			{ name: "MDL1_OUTA", description: "Input Flag clear for MDL1_OUTA Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "MDL1_OUTB", description: "Input Flag clear for MDL1_OUTB Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "MDL2_OUTA", description: "Input Flag clear for MDL2_OUTA Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "MDL2_OUTB", description: "Input Flag clear for MDL2_OUTB Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "MDL3_OUTA", description: "Input Flag clear for MDL3_OUTA Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "MDL3_OUTB", description: "Input Flag clear for MDL3_OUTB Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "MDL4_OUTA", description: "Input Flag clear for MDL4_OUTA Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "MDL4_OUTB", description: "Input Flag clear for MDL4_OUTB Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "MDL5_OUTA", description: "Input Flag clear for MDL5_OUTA Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "MDL5_OUTB", description: "Input Flag clear for MDL5_OUTB Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "MDL6_OUTA", description: "Input Flag clear for MDL6_OUTA Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "MDL6_OUTB", description: "Input Flag clear for MDL6_OUTB Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "MDL7_OUTA", description: "Input Flag clear for MDL7_OUTA Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MDL7_OUTB", description: "Input Flag clear for MDL7_OUTB Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MDL8_OUTA", description: "Input Flag clear for MDL8_OUTA Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MDL8_OUTB", description: "Input Flag clear for MDL8_OUTB Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MDL9_OUTA", description: "Input Flag clear for MDL9_OUTA Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MDL9_OUTB", description: "Input Flag clear for MDL9_OUTB Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MDL10_OUTA", description: "Input Flag clear for MDL10_OUTA Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MDL10_OUTB", description: "Input Flag clear for MDL10_OUTB Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MDL11_OUTA", description: "Input Flag clear for MDL11_OUTA Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MDL11_OUTB", description: "Input Flag clear for MDL11_OUTB Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MDL12_OUTA", description: "Input Flag clear for MDL12_OUTA Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MDL12_OUTB", description: "Input Flag clear for MDL12_OUTB Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MDL13_OUTA", description: "Input Flag clear for MDL13_OUTA Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MDL13_OUTB", description: "Input Flag clear for MDL13_OUTB Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MDL14_OUTA", description: "Input Flag clear for MDL14_OUTA Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MDL14_OUTB", description: "Input Flag clear for MDL14_OUTB Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MDL15_OUTA", description: "Input Flag clear for MDL15_OUTA Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MDL15_OUTB", description: "Input Flag clear for MDL15_OUTB Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MDL16_OUTA", description: "Input Flag clear for MDL16_OUTA Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MDL16_OUTB", description: "Input Flag clear for MDL16_OUTB Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR11", description: "X-Bar Input Flag Clear Register 11", offset: "0x34",
		bits: [
			{ name: "MDL17_OUTA", description: "Input Flag clear for MDL17_OUTA Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "MDL17_OUTB", description: "Input Flag clear for MDL17_OUTB Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "MDL18_OUTA", description: "Input Flag clear for MDL18_OUTA Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "MDL18_OUTB", description: "Input Flag clear for MDL18_OUTB Signal", size: "1", shift: "3", mask: "0x8" },
		]
	},
	{ name: "CLR12", description: "X-Bar Input Flag Clear Register 12", offset: "0x36",
		bits: [
			{ name: "CLB1_OUT0", description: "Input Flag clear for CLB1_OUT0 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CLB1_OUT1", description: "Input Flag clear for CLB1_OUT1 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CLB1_OUT2", description: "Input Flag clear for CLB1_OUT2 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CLB1_OUT3", description: "Input Flag clear for CLB1_OUT3 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "CLB1_OUT6", description: "Input Flag clear for CLB1_OUT6 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CLB1_OUT7", description: "Input Flag clear for CLB1_OUT7 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CLB2_OUT0", description: "Input Flag clear for CLB2_OUT0 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "CLB2_OUT1", description: "Input Flag clear for CLB2_OUT1 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "CLB2_OUT2", description: "Input Flag clear for CLB2_OUT2 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CLB2_OUT3", description: "Input Flag clear for CLB2_OUT3 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CLB2_OUT6", description: "Input Flag clear for CLB2_OUT6 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "CLB2_OUT7", description: "Input Flag clear for CLB2_OUT7 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "CLB3_OUT0", description: "Input Flag clear for CLB3_OUT0 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CLB3_OUT1", description: "Input Flag clear for CLB3_OUT1 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CLB3_OUT2", description: "Input Flag clear for CLB3_OUT2 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CLB3_OUT3", description: "Input Flag clear for CLB3_OUT3 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CLB3_OUT6", description: "Input Flag clear for CLB3_OUT6 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CLB3_OUT7", description: "Input Flag clear for CLB3_OUT7 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CLB4_OUT0", description: "Input Flag clear for CLB4_OUT0 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CLB4_OUT1", description: "Input Flag clear for CLB4_OUT1 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CLB4_OUT2", description: "Input Flag clear for CLB4_OUT2 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CLB4_OUT3", description: "Input Flag clear for CLB4_OUT3 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CLB4_OUT6", description: "Input Flag clear for CLB4_OUT6 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CLB4_OUT7", description: "Input Flag clear for CLB4_OUT7 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CLB5_OUT0", description: "Input Flag clear for CLB5_OUT0 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CLB5_OUT1", description: "Input Flag clear for CLB5_OUT1 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CLB5_OUT2", description: "Input Flag clear for CLB5_OUT2 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CLB5_OUT3", description: "Input Flag clear for CLB5_OUT3 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CLB5_OUT6", description: "Input Flag clear for CLB5_OUT6 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CLB5_OUT7", description: "Input Flag clear for CLB5_OUT7 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CLB6_OUT0", description: "Input Flag clear for CLB6_OUT0 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CLB6_OUT1", description: "Input Flag clear for CLB6_OUT1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR13", description: "X-Bar Input Flag Clear Register 13", offset: "0x38",
		bits: [
			{ name: "CLB6_OUT2", description: "Input Flag clear for CLB6_OUT2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CLB6_OUT3", description: "Input Flag clear for CLB6_OUT3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CLB6_OUT6", description: "Input Flag clear for CLB6_OUT6 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "CLB6_OUT7", description: "Input Flag clear for CLB6_OUT7 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "XTRIPOUT1", description: "Input Flag clear for XTRIPOUT1 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "XTRIPOUT2", description: "Input Flag clear for XTRIPOUT2 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "XTRIPOUT3", description: "Input Flag clear for XTRIPOUT3 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "XTRIPOUT4", description: "Input Flag clear for XTRIPOUT4 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "XTRIPOUT5", description: "Input Flag clear for XTRIPOUT5 Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "XTRIPOUT6", description: "Input Flag clear for XTRIPOUT6 Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "XTRIPOUT7", description: "Input Flag clear for XTRIPOUT7 Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "XTRIPOUT8", description: "Input Flag clear for XTRIPOUT8 Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ADCA_EXTMUXSEL0", description: "Input Flag clear for ADCA_EXTMUXSEL0 Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ADCA_EXTMUXSEL1", description: "Input Flag clear for ADCA_EXTMUXSEL1 Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ADCA_EXTMUXSEL2", description: "Input Flag clear for ADCA_EXTMUXSEL2 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ADCA_EXTMUXSEL3", description: "Input Flag clear for ADCA_EXTMUXSEL3 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ADCB_EXTMUXSEL0", description: "Input Flag clear for ADCB_EXTMUXSEL0 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ADCB_EXTMUXSEL1", description: "Input Flag clear for ADCB_EXTMUXSEL1 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ADCB_EXTMUXSEL2", description: "Input Flag clear for ADCB_EXTMUXSEL2 Signal", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ADCB_EXTMUXSEL3", description: "Input Flag clear for ADCB_EXTMUXSEL3 Signal", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ADCC_EXTMUXSEL0", description: "Input Flag clear for ADCC_EXTMUXSEL0 Signal", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ADCC_EXTMUXSEL1", description: "Input Flag clear for ADCC_EXTMUXSEL1 Signal", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ADCC_EXTMUXSEL2", description: "Input Flag clear for ADCC_EXTMUXSEL2 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ADCC_EXTMUXSEL3", description: "Input Flag clear for ADCC_EXTMUXSEL3 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "PIEERR", description: "Input Flag clear for PIEERR Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ECCERR", description: "Input Flag clear for ECCERR Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "EPG1_EPGOUT0", description: "Input Flag clear for EPG1_EPGOUT0 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "EPG1_EPGOUT1", description: "Input Flag clear for EPG1_EPGOUT1 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "EPG1_EPGOUT2", description: "Input Flag clear for EPG1_EPGOUT2 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "EPG1_EPGOUT3", description: "Input Flag clear for EPG1_EPGOUT3 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR14", description: "X-Bar Input Flag Clear Register 14", offset: "0x3A",
		bits: [
			{ name: "SD3FLT1_COMPH", description: "Input Flag clear for SD3FLT1_COMPH Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "SD3FLT1_COMPL", description: "Input Flag clear for SD3FLT1_COMPL Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "SD3FLT2_COMPH", description: "Input Flag clear for SD3FLT2_COMPH Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "SD3FLT2_COMPL", description: "Input Flag clear for SD3FLT2_COMPL Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "SD3FLT3_COMPH", description: "Input Flag clear for SD3FLT3_COMPH Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "SD3FLT3_COMPL", description: "Input Flag clear for SD3FLT3_COMPL Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "SD3FLT4_COMPH", description: "Input Flag clear for SD3FLT4_COMPH Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "SD3FLT4_COMPL", description: "Input Flag clear for SD3FLT4_COMPL Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "SD4FLT1_COMPH", description: "Input Flag clear for SD4FLT1_COMPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "SD4FLT1_COMPL", description: "Input Flag clear for SD4FLT1_COMPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "SD4FLT2_COMPH", description: "Input Flag clear for SD4FLT2_COMPH Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "SD4FLT2_COMPL", description: "Input Flag clear for SD4FLT2_COMPL Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "SD4FLT3_COMPH", description: "Input Flag clear for SD4FLT3_COMPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "SD4FLT3_COMPL", description: "Input Flag clear for SD4FLT3_COMPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "SD4FLT4_COMPH", description: "Input Flag clear for SD4FLT4_COMPH Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "SD4FLT4_COMPL", description: "Input Flag clear for SD4FLT4_COMPL Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "INPUTXBAR2_INPUT10", description: "Input Flag clear for INPUTXBAR2_INPUT10", size: "1", shift: "17", mask: "0x20000" },
			{ name: "INPUTXBAR2_INPUT11", description: "Input Flag clear for INPUTXBAR2_INPUT11", size: "1", shift: "18", mask: "0x40000" },
			{ name: "INPUTXBAR2_INPUT12", description: "Input Flag clear for INPUTXBAR2_INPUT12", size: "1", shift: "19", mask: "0x80000" },
			{ name: "INPUTXBAR2_INPUT13", description: "Input Flag clear for INPUTXBAR2_INPUT13", size: "1", shift: "20", mask: "0x100000" },
			{ name: "INPUTXBAR2_INPUT14", description: "Input Flag clear for INPUTXBAR2_INPUT14", size: "1", shift: "21", mask: "0x200000" },
			{ name: "INPUTXBAR2_INPUT7", description: "Input Flag clear for INPUTXBAR2_INPUT7", size: "1", shift: "22", mask: "0x400000" },
			{ name: "INPUTXBAR2_INPUT8", description: "Input Flag clear for INPUTXBAR2_INPUT8", size: "1", shift: "23", mask: "0x800000" },
			{ name: "INPUTXBAR2_INPUT9", description: "Input Flag clear for INPUTXBAR2_INPUT9", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MCANB_FEVT0", description: "Input Flag clear for MCANB_FEVT0 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MCANB_FEVT1", description: "Input Flag clear for MCANB_FEVT1 Signal", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MCANB_FEVT2", description: "Input Flag clear for MCANB_FEVT2 Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "FSIA_RX_TRIG1", description: "Input Flag clear for FSIA_RX_TRIG1 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "FSIB_RX_TRIG1", description: "Input Flag clear for FSIB_RX_TRIG1 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "FSIC_RX_TRIG1", description: "Input Flag clear for FSIC_RX_TRIG1 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "FSID_RX_TRIG1", description: "Input Flag clear for FSID_RX_TRIG1 Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "CLR15", description: "X-Bar Input Flag Clear Register 15", offset: "0x3C",
		bits: [
			{ name: "FSIRXA_TRIG_2", description: "Input Flag clear for FSIRXA_TRIG_2 Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "FSIRXA_TRIG_3", description: "Input Flag clear for FSIRXA_TRIG_3 Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "FSIRXB_TRIG_2", description: "Input Flag clear for FSIRXB_TRIG_2 Signal", size: "1", shift: "2", mask: "0x4" },
			{ name: "FSIRXB_TRIG_3", description: "Input Flag clear for FSIRXB_TRIG_3 Signal", size: "1", shift: "3", mask: "0x8" },
			{ name: "FSIRXC_TRIG_2", description: "Input Flag clear for FSIRXC_TRIG_2 Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "FSIRXC_TRIG_3", description: "Input Flag clear for FSIRXC_TRIG_3 Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "FSIRXD_TRIG_2", description: "Input Flag clear for FSIRXD_TRIG_2 Signal", size: "1", shift: "6", mask: "0x40" },
			{ name: "FSIRXD_TRIG_3", description: "Input Flag clear for FSIRXD_TRIG_3 Signal", size: "1", shift: "7", mask: "0x80" },
			{ name: "ECAP1_TRIPOUT", description: "Input Flag clear for ECAP1_TRIPOUT Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "ECAP2_TRIPOUT", description: "Input Flag clear for ECAP2_TRIPOUT Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "ECAP3_TRIPOUT", description: "Input Flag clear for ECAP3_TRIPOUT Signal", size: "1", shift: "10", mask: "0x400" },
			{ name: "ECAP4_TRIPOUT", description: "Input Flag clear for ECAP4_TRIPOUT Signal", size: "1", shift: "11", mask: "0x800" },
			{ name: "ECAP5_TRIPOUT", description: "Input Flag clear for ECAP5_TRIPOUT Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ECAP6_TRIPOUT", description: "Input Flag clear for ECAP6_TRIPOUT Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CPU1ERADEVT10", description: "Input Flag clear for CPU1ERADEVT10 Signal", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CPU1ERADEVT11", description: "Input Flag clear for CPU1ERADEVT11 Signal", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CPU1ERADEVT8", description: "Input Flag clear for CPU1ERADEVT8 Signal", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CPU1ERADEVT9", description: "Input Flag clear for CPU1ERADEVT9 Signal", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CPU1_ADCCHECKEVT1", description: "Input Flag clear for CPU1_ADCCHECKEVT1", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CPU1_ADCCHECKEVT2", description: "Input Flag clear for CPU1_ADCCHECKEVT2", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CPU1_ADCCHECKEVT3", description: "Input Flag clear for CPU1_ADCCHECKEVT3", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CPU1_ADCCHECKEVT4", description: "Input Flag clear for CPU1_ADCCHECKEVT4", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CPU2ERADEVT10", description: "Input Flag clear for CPU2ERADEVT10 Signal", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CPU2ERADEVT11", description: "Input Flag clear for CPU2ERADEVT11 Signal", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CPU2ERADEVT8", description: "Input Flag clear for CPU2ERADEVT8 Signal", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CPU2ERADEVT9", description: "Input Flag clear for CPU2ERADEVT9 Signal", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CPU2_ADCCHECKEVT1", description: "Input Flag clear for CPU2_ADCCHECKEVT1", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CPU2_ADCCHECKEVT2", description: "Input Flag clear for CPU2_ADCCHECKEVT2", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CPU2_ADCCHECKEVT3", description: "Input Flag clear for CPU2_ADCCHECKEVT3", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CPU2_ADCCHECKEVT4", description: "Input Flag clear for CPU2_ADCCHECKEVT4", size: "1", shift: "29", mask: "0x20000000" },
		]
	},
	{ name: "CLR16", description: "X-Bar Input Flag Clear Register 16", offset: "0x3E",
		bits: [
			{ name: "CMPSS9_CTRIPH", description: "Input Flag clear for CMPSS9_CTRIPH Signal", size: "1", shift: "0", mask: "0x1" },
			{ name: "CMPSS9_CTRIPL", description: "Input Flag clear for CMPSS9_CTRIPL Signal", size: "1", shift: "1", mask: "0x2" },
			{ name: "CMPSS9_CTRIPOUTH", description: "Input Flag clear for CMPSS9_CTRIPOUTH", size: "1", shift: "2", mask: "0x4" },
			{ name: "CMPSS9_CTRIPOUTL", description: "Input Flag clear for CMPSS9_CTRIPOUTL", size: "1", shift: "3", mask: "0x8" },
			{ name: "CMPSS10_CTRIPH", description: "Input Flag clear for CMPSS10_CTRIPH Signal", size: "1", shift: "4", mask: "0x10" },
			{ name: "CMPSS10_CTRIPL", description: "Input Flag clear for CMPSS10_CTRIPL Signal", size: "1", shift: "5", mask: "0x20" },
			{ name: "CMPSS10_CTRIPOUTH", description: "Input Flag clear for CMPSS10_CTRIPOUTH", size: "1", shift: "6", mask: "0x40" },
			{ name: "CMPSS10_CTRIPOUTL", description: "Input Flag clear for CMPSS10_CTRIPOUTL", size: "1", shift: "7", mask: "0x80" },
			{ name: "CMPSS11_CTRIPH", description: "Input Flag clear for CMPSS11_CTRIPH Signal", size: "1", shift: "8", mask: "0x100" },
			{ name: "CMPSS11_CTRIPL", description: "Input Flag clear for CMPSS11_CTRIPL Signal", size: "1", shift: "9", mask: "0x200" },
			{ name: "CMPSS11_CTRIPOUTH", description: "Input Flag clear for CMPSS11_CTRIPOUTH", size: "1", shift: "10", mask: "0x400" },
			{ name: "CMPSS11_CTRIPOUTL", description: "Input Flag clear for CMPSS11_CTRIPOUTL", size: "1", shift: "11", mask: "0x800" },
			{ name: "CMPSS12_CTRIPH", description: "Input Flag clear for CMPSS12_CTRIPH Signal", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CMPSS12_CTRIPL", description: "Input Flag clear for CMPSS12_CTRIPL Signal", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CMPSS12_CTRIPOUTH", description: "Input Flag clear for CMPSS12_CTRIPOUTH", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CMPSS12_CTRIPOUTL", description: "Input Flag clear for CMPSS12_CTRIPOUTL", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CLB5_4_1", description: "Input Flag clear for CLB5_4_1  Signal", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CLB5_5_1", description: "Input Flag clear for CLB5_5_1 Signal", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CLB6_4_1", description: "Input Flag clear for CLB6_4_1 Signal", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CLB6_5_1", description: "Input Flag clear for CLB6_5_1 Signal", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "XCLKOUT", description: "Input Flag clear for XCLKOUT Signal", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
];
module.exports = {
	XBARRegisters: XBARRegisters,
}
