let interrupts = [
	{ int_define_name: "INT_TIMER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 1 Interrupt" },
	{ int_define_name: "INT_TIMER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "CPU Timer 2 Interrupt" },
	{ int_define_name: "INT_DATALOG", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Datalogging Interrupt" },
	{ int_define_name: "INT_RTOS", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "RTOS Interrupt from ERAD" },
	{ int_define_name: "INT_EMU", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Emulation Interrupt" },
	{ int_define_name: "INT_NMI", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Non-Maskable Interrupt" },
	{ int_define_name: "INT_ILLEGAL", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "Illegal Operation Trap" },
	{ int_define_name: "INT_USER1", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 1" },
	{ int_define_name: "INT_USER2", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 2" },
	{ int_define_name: "INT_USER3", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 3" },
	{ int_define_name: "INT_USER4", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 4" },
	{ int_define_name: "INT_USER5", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 5" },
	{ int_define_name: "INT_USER6", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 6" },
	{ int_define_name: "INT_USER7", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 7" },
	{ int_define_name: "INT_USER8", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 8" },
	{ int_define_name: "INT_USER9", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 9" },
	{ int_define_name: "INT_USER10", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 10" },
	{ int_define_name: "INT_USER11", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 11" },
	{ int_define_name: "INT_USER12", int_group_channel_number: "OTHER", int_group_number: "", int_channel_number: "", int_description: "User Defined Trap 12" },
	{ int_define_name: "INT_ADCA1", int_group_channel_number: "1.1", int_group_number: "1", int_channel_number: "1", int_description: "ADCA Interrupt 1" },
	{ int_define_name: "INT_ADCB1", int_group_channel_number: "1.2", int_group_number: "1", int_channel_number: "2", int_description: "ADCB Interrupt 1" },
	{ int_define_name: "INT_ADCC1", int_group_channel_number: "1.3", int_group_number: "1", int_channel_number: "3", int_description: "ADCC Interrupt 1" },
	{ int_define_name: "INT_XINT1", int_group_channel_number: "1.4", int_group_number: "1", int_channel_number: "4", int_description: "XINT1 Interrupt" },
	{ int_define_name: "INT_XINT2", int_group_channel_number: "1.5", int_group_number: "1", int_channel_number: "5", int_description: "XINT2 Interrupt" },
	{ int_define_name: "INT_TIMER0", int_group_channel_number: "1.7", int_group_number: "1", int_channel_number: "7", int_description: "Timer 0 Interrupt" },
	{ int_define_name: "INT_WAKE", int_group_channel_number: "1.8", int_group_number: "1", int_channel_number: "8", int_description: "Standby and Halt Wakeup Interrupt" },
	{ int_define_name: "INT_EPWM1_TZ", int_group_channel_number: "2.1", int_group_number: "2", int_channel_number: "1", int_description: "ePWM1 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM2_TZ", int_group_channel_number: "2.2", int_group_number: "2", int_channel_number: "2", int_description: "ePWM2 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM3_TZ", int_group_channel_number: "2.3", int_group_number: "2", int_channel_number: "3", int_description: "ePWM3 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM4_TZ", int_group_channel_number: "2.4", int_group_number: "2", int_channel_number: "4", int_description: "ePWM4 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM5_TZ", int_group_channel_number: "2.5", int_group_number: "2", int_channel_number: "5", int_description: "ePWM5 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM6_TZ", int_group_channel_number: "2.6", int_group_number: "2", int_channel_number: "6", int_description: "ePWM6 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM7_TZ", int_group_channel_number: "2.7", int_group_number: "2", int_channel_number: "7", int_description: "ePWM7 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM8_TZ", int_group_channel_number: "2.8", int_group_number: "2", int_channel_number: "8", int_description: "ePWM8 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM1", int_group_channel_number: "3.1", int_group_number: "3", int_channel_number: "1", int_description: "ePWM1 Interrupt" },
	{ int_define_name: "INT_EPWM2", int_group_channel_number: "3.2", int_group_number: "3", int_channel_number: "2", int_description: "ePWM2 Interrupt" },
	{ int_define_name: "INT_EPWM3", int_group_channel_number: "3.3", int_group_number: "3", int_channel_number: "3", int_description: "ePWM3 Interrupt" },
	{ int_define_name: "INT_EPWM4", int_group_channel_number: "3.4", int_group_number: "3", int_channel_number: "4", int_description: "ePWM4 Interrupt" },
	{ int_define_name: "INT_EPWM5", int_group_channel_number: "3.5", int_group_number: "3", int_channel_number: "5", int_description: "ePWM5 Interrupt" },
	{ int_define_name: "INT_EPWM6", int_group_channel_number: "3.6", int_group_number: "3", int_channel_number: "6", int_description: "ePWM6 Interrupt" },
	{ int_define_name: "INT_EPWM7", int_group_channel_number: "3.7", int_group_number: "3", int_channel_number: "7", int_description: "ePWM7 Interrupt" },
	{ int_define_name: "INT_EPWM8", int_group_channel_number: "3.8", int_group_number: "3", int_channel_number: "8", int_description: "ePWM8 Interrupt" },
	{ int_define_name: "INT_ECAP1", int_group_channel_number: "4.1", int_group_number: "4", int_channel_number: "1", int_description: "eCAP1 Interrupt" },
	{ int_define_name: "INT_ECAP2", int_group_channel_number: "4.2", int_group_number: "4", int_channel_number: "2", int_description: "eCAP2 Interrupt" },
	{ int_define_name: "INT_ECAP3", int_group_channel_number: "4.3", int_group_number: "4", int_channel_number: "3", int_description: "eCAP3 Interrupt" },
	{ int_define_name: "INT_ECAP4", int_group_channel_number: "4.4", int_group_number: "4", int_channel_number: "4", int_description: "eCAP4 Interrupt" },
	{ int_define_name: "INT_ECAP5", int_group_channel_number: "4.5", int_group_number: "4", int_channel_number: "5", int_description: "eCAP5 Interrupt" },
	{ int_define_name: "INT_ECAP6", int_group_channel_number: "4.6", int_group_number: "4", int_channel_number: "6", int_description: "eCAP6 Interrupt" },
	{ int_define_name: "INT_ECAP7", int_group_channel_number: "4.7", int_group_number: "4", int_channel_number: "7", int_description: "eCAP7 Interrupt" },
	{ int_define_name: "INT_EQEP1", int_group_channel_number: "5.1", int_group_number: "5", int_channel_number: "1", int_description: "eQEP1 Interrupt" },
	{ int_define_name: "INT_EQEP2", int_group_channel_number: "5.2", int_group_number: "5", int_channel_number: "2", int_description: "eQEP2 Interrupt" },
	{ int_define_name: "INT_EQEP3", int_group_channel_number: "5.3", int_group_number: "5", int_channel_number: "3", int_description: "eQEP3 Interrupt" },
	{ int_define_name: "INT_EQEP4", int_group_channel_number: "5.4", int_group_number: "5", int_channel_number: "4", int_description: "eQEP4 Interrupt" },
	{ int_define_name: "INT_CLB1", int_group_channel_number: "5.5", int_group_number: "5", int_channel_number: "5", int_description: "CLB1 (Reconfigurable Logic) Interrupt" },
	{ int_define_name: "INT_CLB2", int_group_channel_number: "5.6", int_group_number: "5", int_channel_number: "6", int_description: "CLB2 (Reconfigurable Logic) Interrupt" },
	{ int_define_name: "INT_CLB3", int_group_channel_number: "5.7", int_group_number: "5", int_channel_number: "7", int_description: "CLB3 (Reconfigurable Logic) Interrupt" },
	{ int_define_name: "INT_CLB4", int_group_channel_number: "5.8", int_group_number: "5", int_channel_number: "8", int_description: "CLB4 (Reconfigurable Logic) Interrupt" },
	{ int_define_name: "INT_SPIA_RX", int_group_channel_number: "6.1", int_group_number: "6", int_channel_number: "1", int_description: "SPIA Receive Interrupt" },
	{ int_define_name: "INT_SPIA_TX", int_group_channel_number: "6.2", int_group_number: "6", int_channel_number: "2", int_description: "SPIA Transmit Interrupt" },
	{ int_define_name: "INT_SPIB_RX", int_group_channel_number: "6.3", int_group_number: "6", int_channel_number: "3", int_description: "SPIB Receive Interrupt" },
	{ int_define_name: "INT_SPIB_TX", int_group_channel_number: "6.4", int_group_number: "6", int_channel_number: "4", int_description: "SPIB Transmit Interrupt" },
	{ int_define_name: "INT_LINA_0", int_group_channel_number: "6.5", int_group_number: "6", int_channel_number: "5", int_description: "LINA Interrupt0" },
	{ int_define_name: "INT_LINA_1", int_group_channel_number: "6.6", int_group_number: "6", int_channel_number: "6", int_description: "LINA Interrupt1" },
	{ int_define_name: "INT_LINB_0", int_group_channel_number: "6.7", int_group_number: "6", int_channel_number: "7", int_description: "LINB Interrupt0" },
	{ int_define_name: "INT_LINB_1", int_group_channel_number: "6.8", int_group_number: "6", int_channel_number: "8", int_description: "LINB Interrupt1" },
	{ int_define_name: "INT_DMA_CH1", int_group_channel_number: "7.1", int_group_number: "7", int_channel_number: "1", int_description: "DMA Channel 1 Interrupt" },
	{ int_define_name: "INT_DMA_CH2", int_group_channel_number: "7.2", int_group_number: "7", int_channel_number: "2", int_description: "DMA Channel 2 Interrupt" },
	{ int_define_name: "INT_DMA_CH3", int_group_channel_number: "7.3", int_group_number: "7", int_channel_number: "3", int_description: "DMA Channel 3 Interrupt" },
	{ int_define_name: "INT_DMA_CH4", int_group_channel_number: "7.4", int_group_number: "7", int_channel_number: "4", int_description: "DMA Channel 4 Interrupt" },
	{ int_define_name: "INT_DMA_CH5", int_group_channel_number: "7.5", int_group_number: "7", int_channel_number: "5", int_description: "DMA Channel 5 Interrupt" },
	{ int_define_name: "INT_DMA_CH6", int_group_channel_number: "7.6", int_group_number: "7", int_channel_number: "6", int_description: "DMA Channel 6 Interrupt" },
	{ int_define_name: "INT_EQEP5", int_group_channel_number: "7.7", int_group_number: "7", int_channel_number: "7", int_description: "eQEP5 Interrupt" },
	{ int_define_name: "INT_EQEP6", int_group_channel_number: "7.8", int_group_number: "7", int_channel_number: "8", int_description: "eQEP6 Interrupt" },
	{ int_define_name: "INT_I2CA", int_group_channel_number: "8.1", int_group_number: "8", int_channel_number: "1", int_description: "I2CA Interrupt 1" },
	{ int_define_name: "INT_I2CA_FIFO", int_group_channel_number: "8.2", int_group_number: "8", int_channel_number: "2", int_description: "I2CA Interrupt 2" },
	{ int_define_name: "INT_I2CB", int_group_channel_number: "8.3", int_group_number: "8", int_channel_number: "3", int_description: "I2CB Interrupt 1" },
	{ int_define_name: "INT_I2CB_FIFO", int_group_channel_number: "8.4", int_group_number: "8", int_channel_number: "4", int_description: "I2CB Interrupt 2" },
	{ int_define_name: "INT_UARTA", int_group_channel_number: "8.5", int_group_number: "8", int_channel_number: "5", int_description: "UARTA Interrupt" },
	{ int_define_name: "INT_UARTB", int_group_channel_number: "8.6", int_group_number: "8", int_channel_number: "6", int_description: "UARTB Interrupt" },
	{ int_define_name: "INT_EPWM17_TZ", int_group_channel_number: "8.7", int_group_number: "8", int_channel_number: "7", int_description: "ePWM17 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM18_TZ", int_group_channel_number: "8.8", int_group_number: "8", int_channel_number: "8", int_description: "ePWM18 Trip Zone Interrupt" },
	{ int_define_name: "INT_SCIA_RX", int_group_channel_number: "9.1", int_group_number: "9", int_channel_number: "1", int_description: "SCIA Receive Interrupt" },
	{ int_define_name: "INT_SCIA_TX", int_group_channel_number: "9.2", int_group_number: "9", int_channel_number: "2", int_description: "SCIA Transmit Interrupt" },
	{ int_define_name: "INT_SCIB_RX", int_group_channel_number: "9.3", int_group_number: "9", int_channel_number: "3", int_description: "SCIB Receive Interrupt" },
	{ int_define_name: "INT_SCIB_TX", int_group_channel_number: "9.4", int_group_number: "9", int_channel_number: "4", int_description: "SCIB Transmit Interrupt" },
	{ int_define_name: "INT_CANA0", int_group_channel_number: "9.5", int_group_number: "9", int_channel_number: "5", int_description: "CANA Interrupt 0" },
	{ int_define_name: "INT_CANA1", int_group_channel_number: "9.6", int_group_number: "9", int_channel_number: "6", int_description: "CANA Interrupt 1" },
	{ int_define_name: "INT_EPWM17", int_group_channel_number: "9.7", int_group_number: "9", int_channel_number: "7", int_description: "ePWM17 Interrupt" },
	{ int_define_name: "INT_EPWM18", int_group_channel_number: "9.8", int_group_number: "9", int_channel_number: "8", int_description: "ePWM18 Interrupt" },
	{ int_define_name: "INT_ADCA_EVT", int_group_channel_number: "10.1", int_group_number: "10", int_channel_number: "1", int_description: "ADCA Event Interrupt" },
	{ int_define_name: "INT_ADCA2", int_group_channel_number: "10.2", int_group_number: "10", int_channel_number: "2", int_description: "ADCA Interrupt 2" },
	{ int_define_name: "INT_ADCA3", int_group_channel_number: "10.3", int_group_number: "10", int_channel_number: "3", int_description: "ADCA Interrupt 3" },
	{ int_define_name: "INT_ADCA4", int_group_channel_number: "10.4", int_group_number: "10", int_channel_number: "4", int_description: "ADCA Interrupt 4" },
	{ int_define_name: "INT_ADCB_EVT", int_group_channel_number: "10.5", int_group_number: "10", int_channel_number: "5", int_description: "ADCB Event Interrupt" },
	{ int_define_name: "INT_ADCB2", int_group_channel_number: "10.6", int_group_number: "10", int_channel_number: "6", int_description: "ADCB Interrupt 2" },
	{ int_define_name: "INT_ADCB3", int_group_channel_number: "10.7", int_group_number: "10", int_channel_number: "7", int_description: "ADCB Interrupt 3" },
	{ int_define_name: "INT_ADCB4", int_group_channel_number: "10.8", int_group_number: "10", int_channel_number: "8", int_description: "ADCB Interrupt 4" },
	{ int_define_name: "INT_CLA1_1", int_group_channel_number: "11.1", int_group_number: "11", int_channel_number: "1", int_description: "CLA1 Interrupt 1" },
	{ int_define_name: "INT_CLA1_2", int_group_channel_number: "11.2", int_group_number: "11", int_channel_number: "2", int_description: "CLA1 Interrupt 2" },
	{ int_define_name: "INT_CLA1_3", int_group_channel_number: "11.3", int_group_number: "11", int_channel_number: "3", int_description: "CLA1 Interrupt 3" },
	{ int_define_name: "INT_CLA1_4", int_group_channel_number: "11.4", int_group_number: "11", int_channel_number: "4", int_description: "CLA1 Interrupt 4" },
	{ int_define_name: "INT_CLA1_5", int_group_channel_number: "11.5", int_group_number: "11", int_channel_number: "5", int_description: "CLA1 Interrupt 5" },
	{ int_define_name: "INT_CLA1_6", int_group_channel_number: "11.6", int_group_number: "11", int_channel_number: "6", int_description: "CLA1 Interrupt 6" },
	{ int_define_name: "INT_CLA1_7", int_group_channel_number: "11.7", int_group_number: "11", int_channel_number: "7", int_description: "CLA1 Interrupt 7" },
	{ int_define_name: "INT_CLA1_8", int_group_channel_number: "11.8", int_group_number: "11", int_channel_number: "8", int_description: "CLA1 Interrupt 8" },
	{ int_define_name: "INT_XINT3", int_group_channel_number: "12.1", int_group_number: "12", int_channel_number: "1", int_description: "XINT3 Interrupt" },
	{ int_define_name: "INT_XINT4", int_group_channel_number: "12.2", int_group_number: "12", int_channel_number: "2", int_description: "XINT4 Interrupt" },
	{ int_define_name: "INT_XINT5", int_group_channel_number: "12.3", int_group_number: "12", int_channel_number: "3", int_description: "XINT5 Interrupt" },
	{ int_define_name: "INT_MPOST", int_group_channel_number: "12.4", int_group_number: "12", int_channel_number: "4", int_description: "MPOST Interrupt" },
	{ int_define_name: "INT_FLSS", int_group_channel_number: "12.5", int_group_number: "12", int_channel_number: "5", int_description: "FLSS Interrupt" },
	{ int_define_name: "INT_FPU_OVERFLOW", int_group_channel_number: "12.7", int_group_number: "12", int_channel_number: "7", int_description: "FPU Overflow Interrupt" },
	{ int_define_name: "INT_FPU_UNDERFLOW", int_group_channel_number: "12.8", int_group_number: "12", int_channel_number: "8", int_description: "FPU Underflow Interrupt" },
	{ int_define_name: "INT_I2CA_HIGH", int_group_channel_number: "1.9", int_group_number: "1", int_channel_number: "9", int_description: "I2CA Interrupt high priority" },
	{ int_define_name: "INT_SYS_ERR", int_group_channel_number: "1.10", int_group_number: "1", int_channel_number: "10", int_description: "SYS_ERR interrupt" },
	{ int_define_name: "INT_ECATSYNC0", int_group_channel_number: "1.11", int_group_number: "1", int_channel_number: "11", int_description: "ECATSYNC0 Interrupt" },
	{ int_define_name: "INT_ECAT", int_group_channel_number: "1.12", int_group_number: "1", int_channel_number: "12", int_description: "ECAT Interrupt" },
	{ int_define_name: "INT_CIPC0", int_group_channel_number: "1.13", int_group_number: "1", int_channel_number: "13", int_description: "IPC Interrupt 0" },
	{ int_define_name: "INT_CIPC1", int_group_channel_number: "1.14", int_group_number: "1", int_channel_number: "14", int_description: "IPC Interrupt 1" },
	{ int_define_name: "INT_CIPC2", int_group_channel_number: "1.15", int_group_number: "1", int_channel_number: "15", int_description: "IPC Interrupt 2" },
	{ int_define_name: "INT_CIPC3", int_group_channel_number: "1.16", int_group_number: "1", int_channel_number: "16", int_description: "IPC Interrupt 3" },
	{ int_define_name: "INT_EPWM9_TZ", int_group_channel_number: "2.9", int_group_number: "2", int_channel_number: "9", int_description: "ePWM9 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM10_TZ", int_group_channel_number: "2.10", int_group_number: "2", int_channel_number: "10", int_description: "ePWM10 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM11_TZ", int_group_channel_number: "2.11", int_group_number: "2", int_channel_number: "11", int_description: "ePWM11 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM12_TZ", int_group_channel_number: "2.12", int_group_number: "2", int_channel_number: "12", int_description: "ePWM12 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM13_TZ", int_group_channel_number: "2.13", int_group_number: "2", int_channel_number: "13", int_description: "ePWM13 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM14_TZ", int_group_channel_number: "2.14", int_group_number: "2", int_channel_number: "14", int_description: "ePWM14 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM15_TZ", int_group_channel_number: "2.15", int_group_number: "2", int_channel_number: "15", int_description: "ePWM15 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM16_TZ", int_group_channel_number: "2.16", int_group_number: "2", int_channel_number: "16", int_description: "ePWM16 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM9", int_group_channel_number: "3.9", int_group_number: "3", int_channel_number: "9", int_description: "ePWM9 Interrupt" },
	{ int_define_name: "INT_EPWM10", int_group_channel_number: "3.10", int_group_number: "3", int_channel_number: "10", int_description: "ePWM10 Interrupt" },
	{ int_define_name: "INT_EPWM11", int_group_channel_number: "3.11", int_group_number: "3", int_channel_number: "11", int_description: "ePWM11 Interrupt" },
	{ int_define_name: "INT_EPWM12", int_group_channel_number: "3.12", int_group_number: "3", int_channel_number: "12", int_description: "ePWM12 Interrupt" },
	{ int_define_name: "INT_EPWM13", int_group_channel_number: "3.13", int_group_number: "3", int_channel_number: "13", int_description: "ePWM13 Interrupt" },
	{ int_define_name: "INT_EPWM14", int_group_channel_number: "3.14", int_group_number: "3", int_channel_number: "14", int_description: "ePWM14 Interrupt" },
	{ int_define_name: "INT_EPWM15", int_group_channel_number: "3.15", int_group_number: "3", int_channel_number: "15", int_description: "ePWM15 Interrupt" },
	{ int_define_name: "INT_EPWM16", int_group_channel_number: "3.16", int_group_number: "3", int_channel_number: "16", int_description: "ePWM16 Interrupt" },
	{ int_define_name: "INT_FSITXA1", int_group_channel_number: "4.9", int_group_number: "4", int_channel_number: "9", int_description: "FSITXA_INT1 Interrupt" },
	{ int_define_name: "INT_FSITXA2", int_group_channel_number: "4.10", int_group_number: "4", int_channel_number: "10", int_description: "FSITXA_INT2 Interrupt" },
	{ int_define_name: "INT_FSITXB1", int_group_channel_number: "4.11", int_group_number: "4", int_channel_number: "11", int_description: "FSITXB_INT1 Interrupt" },
	{ int_define_name: "INT_FSITXB2", int_group_channel_number: "4.12", int_group_number: "4", int_channel_number: "12", int_description: "FSITXB_INT2 Interrupt" },
	{ int_define_name: "INT_FSIRXA1", int_group_channel_number: "4.13", int_group_number: "4", int_channel_number: "13", int_description: "FSIRXA_INT1 Interrupt" },
	{ int_define_name: "INT_FSIRXA2", int_group_channel_number: "4.14", int_group_number: "4", int_channel_number: "14", int_description: "FSIRXA_INT2 Interrupt" },
	{ int_define_name: "INT_FSIRXB1", int_group_channel_number: "4.15", int_group_number: "4", int_channel_number: "15", int_description: "FSIRXB_INT1 Interrupt" },
	{ int_define_name: "INT_FSIRXB2", int_group_channel_number: "4.16", int_group_number: "4", int_channel_number: "16", int_description: "FSIRXB_INT2 Interrupt" },
	{ int_define_name: "INT_SDFM1", int_group_channel_number: "5.9", int_group_number: "5", int_channel_number: "9", int_description: "SDFM1 Interrupt" },
	{ int_define_name: "INT_SDFM2", int_group_channel_number: "5.10", int_group_number: "5", int_channel_number: "10", int_description: "SDFM2 Interrupt" },
	{ int_define_name: "INT_ECATRST", int_group_channel_number: "5.11", int_group_number: "5", int_channel_number: "11", int_description: "ECATRST Interrupt" },
	{ int_define_name: "INT_ECATSYNC1", int_group_channel_number: "5.12", int_group_number: "5", int_channel_number: "12", int_description: "ECATSYNC1 Interrupt" },
	{ int_define_name: "INT_SDFM1DR1", int_group_channel_number: "5.13", int_group_number: "5", int_channel_number: "13", int_description: "SDFM1DR1 Interrupt" },
	{ int_define_name: "INT_SDFM1DR2", int_group_channel_number: "5.14", int_group_number: "5", int_channel_number: "14", int_description: "SDFM1DR2 Interrupt" },
	{ int_define_name: "INT_SDFM1DR3", int_group_channel_number: "5.15", int_group_number: "5", int_channel_number: "15", int_description: "SDFM1DR3 Interrupt" },
	{ int_define_name: "INT_SDFM1DR4", int_group_channel_number: "5.16", int_group_number: "5", int_channel_number: "16", int_description: "SDFM1DR4 Interrupt" },
	{ int_define_name: "INT_SPIC_RX", int_group_channel_number: "6.9", int_group_number: "6", int_channel_number: "9", int_description: "SPIC Receive Interrupt" },
	{ int_define_name: "INT_SPIC_TX", int_group_channel_number: "6.10", int_group_number: "6", int_channel_number: "10", int_description: "SPIC Transmit Interrupt" },
	{ int_define_name: "INT_SPID_RX", int_group_channel_number: "6.11", int_group_number: "6", int_channel_number: "11", int_description: "SPID Receive Interrupt" },
	{ int_define_name: "INT_SPID_TX", int_group_channel_number: "6.12", int_group_number: "6", int_channel_number: "12", int_description: "SPID Transmit Interrupt" },
	{ int_define_name: "INT_SDFM2DR1", int_group_channel_number: "6.13", int_group_number: "6", int_channel_number: "13", int_description: "SDFM2DR1 Interrupt" },
	{ int_define_name: "INT_SDFM2DR2", int_group_channel_number: "6.14", int_group_number: "6", int_channel_number: "14", int_description: "SDFM2DR2 Interrupt" },
	{ int_define_name: "INT_SDFM2DR3", int_group_channel_number: "6.15", int_group_number: "6", int_channel_number: "15", int_description: "SDFM2DR3 Interrupt" },
	{ int_define_name: "INT_SDFM2DR4", int_group_channel_number: "6.16", int_group_number: "6", int_channel_number: "16", int_description: "SDFM2DR4 Interrupt" },
	{ int_define_name: "INT_FSIRXC1", int_group_channel_number: "7.9", int_group_number: "7", int_channel_number: "9", int_description: "FSIRXC_INT1 Interrupt" },
	{ int_define_name: "INT_FSIRXC2", int_group_channel_number: "7.10", int_group_number: "7", int_channel_number: "10", int_description: "FSIRXC_INT2 Interrupt" },
	{ int_define_name: "INT_FSIRXD1", int_group_channel_number: "7.11", int_group_number: "7", int_channel_number: "11", int_description: "FSIRXD_INT1 Interrupt" },
	{ int_define_name: "INT_FSIRXD2", int_group_channel_number: "7.12", int_group_number: "7", int_channel_number: "12", int_description: "FSIRXA_INT2 Interrupt" },
	{ int_define_name: "INT_SDFM3DR1", int_group_channel_number: "7.13", int_group_number: "7", int_channel_number: "13", int_description: "SDFM3DR1 Interrupt" },
	{ int_define_name: "INT_SDFM3DR2", int_group_channel_number: "7.14", int_group_number: "7", int_channel_number: "14", int_description: "SDFM3DR2 Interrupt" },
	{ int_define_name: "INT_SDFM3DR3", int_group_channel_number: "7.15", int_group_number: "7", int_channel_number: "15", int_description: "SDFM3DR3 Interrupt" },
	{ int_define_name: "INT_SDFM3DR4", int_group_channel_number: "7.16", int_group_number: "7", int_channel_number: "16", int_description: "SDFM3DR4 Interrupt" },
	{ int_define_name: "INT_SDFM3", int_group_channel_number: "8.11", int_group_number: "8", int_channel_number: "11", int_description: "SDFM3 Interrupt" },
	{ int_define_name: "INT_SDFM4", int_group_channel_number: "8.12", int_group_number: "8", int_channel_number: "12", int_description: "SDFM4 Interrupt" },
	{ int_define_name: "INT_CLB5", int_group_channel_number: "8.13", int_group_number: "8", int_channel_number: "13", int_description: "CLB5 Interrupt" },
	{ int_define_name: "INT_CLB6", int_group_channel_number: "8.14", int_group_number: "8", int_channel_number: "14", int_description: "CLB6 Interrupt" },
	{ int_define_name: "INT_MCANA_0", int_group_channel_number: "9.9", int_group_number: "9", int_channel_number: "9", int_description: "MCANSSA0" },
	{ int_define_name: "INT_MCANA_1", int_group_channel_number: "9.10", int_group_number: "9", int_channel_number: "10", int_description: "MCANSSA1" },
	{ int_define_name: "INT_MCANA_ECC", int_group_channel_number: "9.11", int_group_number: "9", int_channel_number: "11", int_description: "MCANSSA_ECC_CORR_PLS" },
	{ int_define_name: "INT_MCANA_WAKE", int_group_channel_number: "9.12", int_group_number: "9", int_channel_number: "12", int_description: "MCANSSA_WAKE_AND_TS_PLS" },
	{ int_define_name: "INT_PMBUSA", int_group_channel_number: "9.13", int_group_number: "9", int_channel_number: "13", int_description: "PMBUSA  Interrupt" },
	{ int_define_name: "INT_AES_SINTREQUEST", int_group_channel_number: "9.14", int_group_number: "9", int_channel_number: "14", int_description: "AES Interrupt" },
	{ int_define_name: "INT_USBA", int_group_channel_number: "9.15", int_group_number: "9", int_channel_number: "15", int_description: "USBA Interrupt" },
	{ int_define_name: "INT_ADCC_EVT", int_group_channel_number: "10.9", int_group_number: "10", int_channel_number: "9", int_description: "ADCC Event Interrupt" },
	{ int_define_name: "INT_ADCC2", int_group_channel_number: "10.10", int_group_number: "10", int_channel_number: "10", int_description: "ADCC Interrupt 2" },
	{ int_define_name: "INT_ADCC3", int_group_channel_number: "10.11", int_group_number: "10", int_channel_number: "11", int_description: "ADCC Interrupt 3" },
	{ int_define_name: "INT_ADCC4", int_group_channel_number: "10.12", int_group_number: "10", int_channel_number: "12", int_description: "ADCC Interrupt 4" },
	{ int_define_name: "INT_ADCCHECKINT", int_group_channel_number: "10.16", int_group_number: "10", int_channel_number: "16", int_description: "Interrupt from ADC Safety Checked Module" },
	{ int_define_name: "INT_MCANB_0", int_group_channel_number: "11.9", int_group_number: "11", int_channel_number: "9", int_description: "MCANSSB0" },
	{ int_define_name: "INT_MCANB_1", int_group_channel_number: "11.10", int_group_number: "11", int_channel_number: "10", int_description: "MCANSSB1" },
	{ int_define_name: "INT_MCANB_ECC", int_group_channel_number: "11.11", int_group_number: "11", int_channel_number: "11", int_description: "MCANSSB_ECC_CORR_PLS" },
	{ int_define_name: "INT_MCANB_WAKE", int_group_channel_number: "11.12", int_group_number: "11", int_channel_number: "12", int_description: "MCANSSB_WAKE_AND_TS_PLS" },
	{ int_define_name: "INT_SDFM4DR1", int_group_channel_number: "11.13", int_group_number: "11", int_channel_number: "13", int_description: "SDFM4DR1 Interrupt" },
	{ int_define_name: "INT_SDFM4DR2", int_group_channel_number: "11.14", int_group_number: "11", int_channel_number: "14", int_description: "SDFM4DR2 Interrupt" },
	{ int_define_name: "INT_SDFM4DR3", int_group_channel_number: "11.15", int_group_number: "11", int_channel_number: "15", int_description: "SDFM4DR3 Interrupt" },
	{ int_define_name: "INT_SDFM4DR4", int_group_channel_number: "11.16", int_group_number: "11", int_channel_number: "16", int_description: "SDFM4DR4 Interrupt" },
	{ int_define_name: "INT_ECAP6_2", int_group_channel_number: "12.10", int_group_number: "12", int_channel_number: "10", int_description: "eCAP6_2 Interrupt" },
	{ int_define_name: "INT_ECAP7_2", int_group_channel_number: "12.11", int_group_number: "12", int_channel_number: "11", int_description: "eCAP7_2 Interrupt" },
	{ int_define_name: "INT_CPUCRC", int_group_channel_number: "12.13", int_group_number: "12", int_channel_number: "13", int_description: "CPU BGCRC" },
	{ int_define_name: "INT_CLA1CRC", int_group_channel_number: "12.14", int_group_number: "12", int_channel_number: "14", int_description: "CLA1 BGCRC" },
	{ int_define_name: "INT_CLA_OVERFLOW", int_group_channel_number: "12.15", int_group_number: "12", int_channel_number: "15", int_description: "CLA Overflow Interrupt" },
	{ int_define_name: "INT_CLA_UNDERFLOW", int_group_channel_number: "12.16", int_group_number: "12", int_channel_number: "16", int_description: "CLA Underflow Interrupt" },
];
module.exports = {
	interrupts: interrupts,
}
