//Add watch window variables
expRemoveAll()
expAdd("x1", getNatural())
expAdd("x2", getNatural())
expAdd("y", getNatural())
expAdd("y1", getNatural())
expAdd("y2", getNatural())
expAdd("y3", getNatural())
expAdd("w1", getNatural())
expAdd("w2", getNatural())
expAdd("z", getNatural())
expAdd("z1", getNatural())
expAdd("z2", getNatural())
expAdd("z3", getNatural())
expAdd("z4", getNatural())
expAdd("z5", getNatural())
expAdd("z6", getNatural())
expAdd("c", getNatural())
expAdd("pass", getNatural())
expAdd("fail", getNatural())