let AcessProtectionRAMs = {
    "f28p65x" : [
    {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS8", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS9", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS4", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
	{name: "MEMCFG_SECT_MSGCPUTOCPU0", access : ['FETCHPROT', 'CPUWRPROT']},
	{name: "MEMCFG_SECT_MSGCPUTOCPU1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "EMIF1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    ],

    "f28p55x" : [
        {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS8", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "LS9", access : ['FETCHPROT', 'CPUWRPROT']},
        {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
        {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
        {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
        {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
        ],

    "f280013x" : [
    {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "PIEVECT", access : ['CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    "f280015x" : [
    {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "PIEVECT", access : ['CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    "f28002x" : [
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT', 'HICWRPROT']},
    ],
    
    "f28003x" : [
    {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT', 'HICWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT', 'HICWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT', 'HICWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT', 'HICWRPROT']},
    ],
    
    "f28004x" : [
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    ],
    
    "f2807x" : [
    {name : "D0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS4", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS5", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS6", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS7", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS8", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS9", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS10", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS11", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS12", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS13", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS14", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS15", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF2", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    "f2837xd" : [
    {name : "D0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS4", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS5", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS6", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS7", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS8", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS9", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS10", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS11", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS12", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS13", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS14", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS15", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF2", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    "f2837xs" : [
    {name : "D0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS4", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS5", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS6", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS7", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS8", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS9", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS10", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS11", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS12", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS13", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS14", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS15", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF2", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    "f2838x" : [
    {name : "M0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "M1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "D1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS0", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS1", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS2", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS3", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS4", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS5", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS6", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "LS7", access : ['FETCHPROT', 'CPUWRPROT']},
    {name : "GS0", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS2", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS3", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS4", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS5", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS6", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS7", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS8", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS9", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS10", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS11", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS12", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS13", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS14", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "GS15", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "MSGCPUTOCPU0", access : ['CPUWRPROT', 'DMAWRPROT']},
    {name : "MSGCPUTOCPU1", access : ['CPUWRPROT', 'DMAWRPROT']},
    {name : "MSGCPUTOCM0", access : ['CPUWRPROT', 'DMAWRPROT']},
    {name : "MSGCPUTOCM1", access : ['CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF1", access : ['FETCHPROT', 'CPUWRPROT', 'DMAWRPROT']},
    {name : "EMIF2", access : ['FETCHPROT', 'CPUWRPROT']},
    ],
    
    }
    
    exports = {
        AcessProtectionRAMs
    }
    