#ifndef INPUT_CONFIG_H_
#define INPUT_CONFIG_H_

#define FE_RAW
#define FE_FRAME_SIZE 128
#define FE_STACKING_CHANNELS 3
#define FE_STACKING_FRAME_WIDTH 128
#define FE_HL 1
#define FE_OFFSET 0
#define FE_SCALE 1
#define FE_MIN_FFT_BIN 1
#define FE_FFT_BIN_SIZE 0
#define FE_NUM_FRAME_CONCAT 1
#define FE_NN_OUT_SIZE 6
#define FE_FFT_STAGES 7
#define FE_FEATURE_SIZE_PER_FRAME 128

#endif /* INPUT_CONFIG_H_ */
