#ifndef DRIVER_TINIE_NPU_MAPPING_H_
#define DRIVER_TINIE_NPU_MAPPING_H_

//*****************************************************************************
// MEMCFG
//*****************************************************************************
#define MEMCFG_GSXACCPROT0_NPU_WRPROT_GS0  MEMCFG_GSXACCPROT0_TINIE_WRPROT_GS0
#define MEMCFG_NMVIOL_NPUREAD              MEMCFG_NMVIOL_TINIEREAD
#define MEMCFG_NMVIOL_NPUWRITE             MEMCFG_NMVIOL_TINIEWRITE
#define MEMCFG_O_NMNPURDAVADDR             MEMCFG_O_NMTINIERDAVADDR
#define MEMCFG_O_NMNPUWRAVADDR             MEMCFG_O_NMTINIEWRAVADDR
#define MEMCFG_O_UCNPUREADDR               MEMCFG_O_UCTINIEREADDR
#define MEMCFG_GSXACCPROT0_NPU_WRPROT_GS0  MEMCFG_GSXACCPROT0_TINIE_WRPROT_GS0
#define MEMCFG_GSXACCPROT0_NPU_WRPROT_GS1  MEMCFG_GSXACCPROT0_TINIE_WRPROT_GS1
#define MEMCFG_GSXACCPROT0_NPU_WRPROT_GS2  MEMCFG_GSXACCPROT0_TINIE_WRPROT_GS2
#define MEMCFG_GSXACCPROT0_NPU_WRPROT_GS3  MEMCFG_GSXACCPROT0_TINIE_WRPROT_GS3
#define MEMCFG_NMAVFLG_NPUREAD             MEMCFG_NMAVFLG_TINIEREAD
#define MEMCFG_NMAVFLG_NPUWRITE            MEMCFG_NMAVFLG_TINIEWRITE
#define MEMCFG_NMAVSET_NPUREAD             MEMCFG_NMAVSET_TINIEREAD
#define MEMCFG_NMAVSET_NPUWRITE            MEMCFG_NMAVSET_TINIEWRITE
#define MEMCFG_NMAVCLR_NPUREAD             MEMCFG_NMAVCLR_TINIEREAD
#define MEMCFG_NMAVCLR_NPUWRITE            MEMCFG_NMAVCLR_TINIEWRITE
#define MEMCFG_NMAVINTEN_NPUREAD           MEMCFG_NMAVINTEN_TINIEREAD
#define MEMCFG_NMAVINTEN_NPUWRITE          MEMCFG_NMAVINTEN_TINIEWRITE
#define MEMCFG_UCERRFLG_NPURDERR           MEMCFG_UCERRFLG_TINIERDERR
#define MEMCFG_UCERRSET_NPURDERR           MEMCFG_UCERRSET_TINIERDERR
#define MEMCFG_UCERRCLR_NPURDERR           MEMCFG_UCERRCLR_TINIERDERR


//*****************************************************************************
// SysCtrl
//*****************************************************************************
#define SYSCTL_PERIPH_CLK_NPU           SYSCTL_PERIPH_CLK_TINIE
#define SYSCTL_PERIPH_RES_NPU           SYSCTL_PERIPH_RES_TINIE
#define SYSCTL_NPUCLK_DIV_1             SYSCTL_TINIECLK_DIV_1
#define SYSCTL_NPUCLK_DIV_2             SYSCTL_TINIECLK_DIV_2
#define SysCtl_NPUCLKDivider            SysCtl_TINIECLKDivider
#define SysCtl_setNPUClockDivider       SysCtl_setTINIEClockDivider
#define SYSCTL_SOFTPRES30_NPU           SYSCTL_SOFTPRES30_TINIE
#define SYSCTL_PERCLKDIVSEL_NPUCLKDIV   SYSCTL_PERCLKDIVSEL_TINIECLKDIV
#define SYSCTL_PCLKCR12_NPU             SYSCTL_PCLKCR12_TINIE

#endif /* DRIVER_TINIE_NPU_MAPPING_H_ */
